### ISSUE TITLE
请问考虑添加基础的用户管理功能吗？

### ISSUE THREAD

**Issue by woodchen-ink** [Kerwin1202/chatgpt-web#100]
1. 比如已注册用户账户的停用功能？就是展示所有已注册账号，并且添加一个状态，开启/停用

2. 还有顺便问下，如果镜像升级而不想影响数据库，是不是在docker-compose.yml里把添加mongodb的代码删除就可以了？

请教一下，还有感谢大佬的贡献

**Comment by Kerwin1202** [comment]
1. 目前没有 后续会考虑
2. 升级镜像  `docker pull kerwin1202/chatgpt-web ` 然后 `docker-compose up -d`  不需要改什么

**Comment by woodchen-ink** [comment]
> 1. 目前没有 后续会考虑
> 2. 升级镜像  `docker pull kerwin1202/chatgpt-web ` 然后 `docker-compose up -d`  不需要改什么

明白，感谢回复
