### ISSUE TITLE
请教一下，这个API余额是在什么情况下会重新请求？显示新的额度？

### ISSUE THREAD

**Issue by woodchen-ink** [Kerwin1202/chatgpt-web#101]
![image](https://user-images.githubusercontent.com/95951386/236293754-e27d80e1-a4db-4c42-b460-f6086f1b3faf.png)

我是通过docker部署在一台服务器上的，然后在另一台服务器部署前端，通过docker的端口请求，我从前端或者docker访问都是没变。
我把key改成一个5美金额度的之后，这个API余额还是显示16块多

**Comment by Kerwin1202** [comment]
因为有的人网络比较慢（比如我自己）所以每 60 分钟缓存一次

**Comment by woodchen-ink** [comment]
> 因为有的人网络比较慢（比如我自己）所以每 60 分钟缓存一次

明白，感谢回复
