### ISSUE TITLE
SMTP不支持gmail吗？

### ISSUE THREAD

**Issue by superen7527** [Kerwin1202/chatgpt-web#103]
用 587 开启tsl 提示： 38FB72B417740000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

用 465 提示： Unexpected socket close (要等很久)

**Comment by liusanp** [comment]
![image](https://user-images.githubusercontent.com/13930358/236434922-d224b101-cf76-4124-b191-abd251d0ab3e.png)
outlook邮箱的加密方法是STARTTLS，也会报这个错，是不是也不支持？

**Comment by huangwb8** [comment]
@superen7527  @liusanp  

QQ邮箱你值得拥有，一直很稳 (ฅ´ω`ฅ)

**Comment by Fugitive844** [comment]
我用的就是gmail，没问题

**Comment by EvanDbg** [comment]
注意使用 应用密码 而不是账号密码 设置gmail邮箱

**Comment by lszhwxa** [comment]
端口用465，谷歌账号打开二次验证，生成gmail专用密码登录就行

**Comment by superen7527** [comment]
> 注意使用 应用密码 而不是账号密码 设置gmail邮箱

https://support.google.com/mail/answer/7126229?visit_id=638189777334370624-2049726782&hl=zh-Hans&rd=1#zippy=%2C%E7%AC%AC-%E6%AD%A5%E5%9C%A8%E7%94%B5%E5%AD%90%E9%82%AE%E4%BB%B6%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%B8%AD%E6%9B%B4%E6%94%B9-smtp-%E5%92%8C%E5%85%B6%E4%BB%96%E8%AE%BE%E7%BD%AE

这里面说密码是 "您的 Gmail 密码"

**Comment by superen7527** [comment]
> 端口用465，谷歌账号打开二次验证，生成gmail专用密码登录就行

感谢 解决了 https://west2.cn/2315.html
