### ISSUE TITLE
希望可以按用户区分，分别使用不同的模型

### ISSUE THREAD

**Issue by jjustwin** [Kerwin1202/chatgpt-web#104]
1.登录用户可以使用gpt-4，未登录使用gpt-3
2.或者有地方可以配置，不同的用户使用不同的模型

**Comment by njukiller** [comment]
我也希望有这个功能，或者让用户在新建对话的时候选择模型，根据不同对话切换模型

**Comment by Kerwin1202** [comment]
那你们是觉得这个由 使用者控制呢，还是由管理员控制比较好，以及还是都支持，比如给一些范围之类的。。

**Comment by njukiller** [comment]
我觉得是这样设置
1. 管理员可以控制用户界面是否可以选择gpt4，比如管理如果禁用了这个用户的gpt4权限，客户端就没有这个选项，或者选择gpt4就报错
2. 管理员为用户启用了gpt4，用户可以在创建新对话的时候选择gpt4模型，或者是在界面中选择默认gpt4模型

更进一步的功能，比如管理员可以控制用户每天或者每小时可以发起多少个gpt4对话之类的

**Comment by Kerwin1202** [comment]
已加

**Comment by jjustwin** [comment]
> 已加

作者你好，我刚把几个角色分开配置了，配置如下：

**Comment by Kerwin1202** [comment]
都是 api key? 没有 是 access token ？

**Comment by jjustwin** [comment]
> 都是 api key? 没有 是 access token ？

是的，没有用access token。而且api key都是同一个
