### ISSUE TITLE
非容器部署，如何配置相关参数

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#105]
大佬，如果不采用docker容器部署，本地编译打包部署的话，连接数据库、邮箱等相关配置在哪里进行修改

**Comment by 2716xzw** [comment]
> 大佬，如果不采用docker容器部署，本地编译打包部署的话，连接数据库、邮箱等相关配置在哪里进行修改

修改.env文件

**Comment by dqzboy** [comment]
好的 我试试

**Comment by dqzboy** [comment]
大佬，我部署完之后为啥没有网站设置配置呢？
![image](https://user-images.githubusercontent.com/42825450/236617219-edc22ea5-6a52-4990-ad18-ed340c5e5549.png)

![image](https://user-images.githubusercontent.com/42825450/236617233-17d31eba-fe06-4a37-afda-ad0ed1d2ff80.png)

**Comment by dqzboy** [comment]
> 大佬，我部署完之后为啥没有网站设置配置呢？ ![image](https://user-images.githubusercontent.com/42825450/236617219-edc22ea5-6a52-4990-ad18-ed340c5e5549.png)
> 
> ![image](https://user-images.githubusercontent.com/42825450/236617233-17d31eba-fe06-4a37-afda-ad0ed1d2ff80.png)

可以了 原来是需要使用超级管理员邮箱进行注册才可以；现在有个新的问题就是我在.env里面更改了网站名称，但是打开页面网站名称显示的 变量
![image](https://user-images.githubusercontent.com/42825450/236619073-cbbf3d08-e1b7-442b-9bef-55d8438b08a9.png)
