### ISSUE TITLE
数据库的含义

### ISSUE THREAD

**Issue by wangjueszu** [Kerwin1202/chatgpt-web#109]
chat_usage中
{
    _id: ObjectId('64561905********9168'),
    userId: '643370f********121b',
    roomId: 1681177602483,
    chatId: ObjectId('645618f********9167'),
    messageId: 'chatcmpl-7D8********BLjp7',
    promptTokens: 424,
    completionTokens: 415,
    totalTokens: 839,
    estimated: true,
    dateTime: 1683364101254
}
dateTime: 1683364101254 这个怎么换算成，我们的年月日呢？

**Comment by Fugitive844** [comment]
精确到毫秒的时间戳，自己转换下就行。

**Comment by wangjueszu** [comment]
根据你提供的时间戳 1683364101254，我可以将其转换为标准的日期时间格式，包括年、月、日、小时、分钟、秒和毫秒。这个时间戳代表的日期时间是：

2023年5月4日 16时15分1秒254毫秒

请注意，这个时间戳的基准时间点是 UTC 时间的 1970 年 1 月 1 日 0 时 0 分 0 秒。如果你想要将其转换为其他时区的本地时间，需要将其与本地时区的时差相加或相减。
----------------
谢谢了，似乎是正确的
