### ISSUE TITLE
这个项目有交流群么

### ISSUE THREAD

**Issue by wangjueszu** [Kerwin1202/chatgpt-web#110]
求问这个项目有交流群么？还主要大家就在github上讨论呢。

**Comment by huangwb8** [comment]
@wangjueszu 

据我所知，开发者似乎没有建交流群。

不过我有一个[tg群](https://t.me/benszhub)，里面玩chatGPT的小伙伴也使用这个项目。 我之前也出过详细教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。

@Kerwin1202 也在这个群里面，不过他比较少发言。
