### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#111]
敏感词测试报错，如下图：
![image](https://user-images.githubusercontent.com/42825450/236636410-27fdad46-4b51-4748-b466-523be4caa3ef.png)

**Comment by Kerwin1202** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/16319833/236657474-c9f4f2aa-d1b2-4ad2-8617-a4d5ac6703c0.png">

**Comment by dqzboy** [comment]
测试没问题了大佬，但是好像没生效呢  输入敏感词，回答也包含敏感词都没任何提醒

**Comment by dqzboy** [comment]
> 测试没问题了大佬，但是好像没生效呢 输入敏感词，回答也包含敏感词都没任何提醒

可以了，原来是对管理员账号不生效
