### ISSUE TITLE
我想迁移数据库里面的用户，怎么解密用户的密码。

### ISSUE THREAD

**Issue by HankMo** [Kerwin1202/chatgpt-web#114]
数据库里面用户的密码是加密的 ，有没有办法解密。

**Comment by zhujunsan** [comment]
用户密码是 密码本身+盐后取的 md5，单向，不能解码，只能验证。
以及，如果只是迁移的话，新服务那边的盐设置得一样就可以直接拷数据了。

**Comment by zcyxy1** [comment]
我是纯新人，刚接触1个月，请问一下你们说的这个数据库 是需要自己建立吗，还是已经建立在程序docker容器内了，我直接拉取这个docker 就包含了数据库吗？

**Comment by zhujunsan** [comment]
这个项目的docker镜像不含数据库，后端需要配置好MongoDB作为数据库，可以也是用docker起，也可以机器上直接装，或者装在别的机器上等等

**Comment by Kerwin1202** [comment]
不能解密
