### ISSUE TITLE
登入注册只能刷新页面才可以关闭吗？

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#117]
大佬，目前登入注册点开后，只能刷新页面才可以关闭吗？
![chatGPT-web](https://user-images.githubusercontent.com/42825450/236737861-9a45e32e-dd3a-4ba3-9330-c94fda6033be.gif)

**Comment by Kerwin1202** [comment]
是哦，影响不大吧。。。原来还是打开就弹窗 呢，现在还可以先看

**Comment by dqzboy** [comment]
好的。我个人觉得打开弹窗挺好的，目前国内对这块监管还是挺严的，如果公开对外访问的话，一下子就知道这个是做啥的站点，就会容易被封

**Comment by Kerwin1202** [comment]
所以支持了修改标题。。改了标题爬虫没爬到。 也有敏感词，加上敏感词，别人知道也没事吧。。别怕 除非你做到几十万人使用。。没人管你的

**Comment by dqzboy** [comment]
嗯嗯
