### ISSUE TITLE
请问怎么查看数据库呀

### ISSUE THREAD

**Issue by yigeimuya** [Kerwin1202/chatgpt-web#136]
用MongoDB Compass链接后好像没有看到用户表

**Comment by huangwb8** [comment]
@yigeimuya 

我推测，你应该是刚刚完成安装、没有改动任何配置的情况下去查看MongoDB的，所以没有看到用户表。 我印象中，应该是要在前端页面改动一些配置并保存后，才会在数据库里有相应的表体现。

我的教程在这里：  [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。其中，我使用的是Mongo Express。 MongoDB Compass我估计也是可以的，毕竟这是官方的工具。

**Comment by yigeimuya** [comment]
> @yigeimuya
> 
> 我推测，你应该是刚刚完成安装、没有更改任何配置的情况下去查看MongoDB的，所以没有看到用户表。我印像中，应该是要在前端面修改一些配置并保存后，才会在数据库里有相应的表现。
> 
> 我的教程在这里： [Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)。其中，我使用的是Mongo Express。MongoDB Compass我估计也是可以的，毕竟这是官方的工具。

嗯嗯是刚装好，可是我看我跨设备已经可以同步聊天记录，而且登录功能也正常了，不同设备也能登录，数据库是否应该已经是有建表了呀

**Comment by Kerwin1202** [comment]
这个需要配置看下，如果是按照这个配置的  可以 访问 ip:4321 看下

https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml
<img width="512" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/0f340d66-addd-4cb3-862e-c36686c0c3ff">

**Comment by yigeimuya** [comment]
> 这个需要配置看下，如果是按照这个配置的 可以 访问 ip:4321 看下
> 
> https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml <img alt="image" width="512" src="https://user-images.githubusercontent.com/16319833/239244874-0f340d66-addd-4cb3-862e-c36686c0c3ff.png">

可以了，谢谢。之前没有添加这个gui的配置，添加后可以了
