### ISSUE TITLE
如何在用户前端让用户自定义修改模型

### ISSUE THREAD

**Issue by luckywangxi** [Kerwin1202/chatgpt-web#142]

**Comment by Kerwin1202** [comment]
这个建议是什么，每个用户一个配置呢，还是每个对话一个配置呢

**Comment by magicdmer** [comment]
建议这个做成用户相关选项，比如我是管理员，我能自由选择gpt4和3，但是如果是普通用户，肯定不能让他选择gpt4，因为gpt4很贵，现在的设置是一视同仁，如果做了限制gpt3，管理员也没法用gpt4了

**Comment by Kerwin1202** [comment]
> > 这个建议是什么，每个用户一个配置呢，还是每个对话一个配置呢
> 
> 建议这个做成用户相关选项，比如我是管理员，我能自由选择gpt4和3，但是如果是普通用户，肯定不能让他选择gpt4，因为gpt4很贵，现在的设置是一视同仁，如果做了限制gpt3，管理员也没法用gpt4了
> 
> 如果做简单点，就是只搞个开关，是否允许该用户选择模型，而不用考虑具体允许那几个模型

最新版应该支持你说的这种吧，你试试？ 虽然不是对用户的

**Comment by magicdmer** [comment]
我免费给一些好友用，但是gpt4额度有限肯定就我自己用用，希望能区分一下用户或者用户组吧，这个设置

**Comment by Kerwin1202** [comment]
这个就是用户组啊，分配一下就好了，你可以给自己分配 admin 设置 key 为 gpt4 然后新建一个 key 去官网重新生成一个key  设置 3.5 设置user 或者guest 啥的 就可以了
<img width="631" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/9c8bb04d-d3b1-4cf7-83e5-832848e7c9b7">

**Comment by magicdmer** [comment]
> 这个就是用户组啊，分配一下就好了，你可以给自己分配 admin 设置 key 为 gpt4 然后新建一个 key 去官网重新生成一个key 设置 3.5 设置user 或者guest 啥的 就可以了 <img alt="image" width="631" src="https://user-images.githubusercontent.com/16319833/240623102-9c8bb04d-d3b1-4cf7-83e5-832848e7c9b7.png">

好的，我试试，我忘了多key这事了，以为一个账户就一个key，谢谢了
