### ISSUE TITLE
模型选择需求

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#147]
chatgpt ios客户端发布后似乎增加了2个针对移动设备的模型

模型名称
ext-davinci-002-render-sha-mobile
gpt-4-mobile

似乎速度飞快，是否能加入到模型选择当中

参考来源：
https://twitter.com/wong2_x/status/1659446644570750978
https://www.reddit.com/r/ChatGPT/comments/13lp72x/you_can_use_chatgpt_ios_models_on_desktop/

目前支持accesstoken；大佬看下能否接入呢？

**Comment by Kerwin1202** [comment]
<img width="1291" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/2c82b9f8-9dd8-4934-8c86-791a36e81834">
