### ISSUE TITLE
未来是否可以实现官方的联网功能？

### ISSUE THREAD

**Issue by SiMPlerMeta** [Kerwin1202/chatgpt-web#148]
大佬，后续是否可以实现官方的web-browsing功能，实现联网查询？

**Comment by Kerwin1202** [comment]
是哪里可以开启呢，，，我之前是用的一个浏览器插件开启的。。

**Comment by SiMPlerMeta** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/28827408/3289ff2b-5333-4615-9bf4-3770602d5ce7)
plus用户推送了实验功能，开启后，查询会联网查询最新的信息，并进行自动回复

**Comment by Kerwin1202** [comment]
plus 刚过期。。。麻了  不过我估计这个得底层api 先支持，除非 不用底层api  自己写

**Comment by SiMPlerMeta** [comment]
我从访问的URL看，确实是新增了一个联网的模型，但是目前api好像还不支持，我后台把model改成gpt-4-browsing，但是查询结果还是显示知识只到2021年9月
![image](https://github.com/Kerwin1202/chatgpt-web/assets/28827408/ec6c9345-5083-4a02-a517-29adb9782e23)

**Comment by Kerwin1202** [comment]
我会尝试增加这个模型，但是我看了别的项目有这个 估计是可以，但不确定有效 gpt-4-browsing，目前没有 4的 账号也没有plus

**Comment by luckywangxi** [comment]
gpt-4-browsing我已尝试，可以实现联网，但是要plus账号用access token，只需添加模型就行， plugin模型也可以添加
![image](https://github.com/Kerwin1202/chatgpt-web/assets/112324550/166adc04-a793-47a9-bce7-1a621a92c9c8)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/112324550/e3080421-9241-491d-92dd-518ca96e4257)

**Comment by Kerwin1202** [comment]
7d15760d28d2a49d2c9d25b543151f9d86b61275  这个加了
