### ISSUE TITLE
用docker compose报Missing OPENAI_API_KEY or OPENAI_ACCESS_TOKEN environment variable

### ISSUE THREAD

**Issue by yd1261137568** [Kerwin1202/chatgpt-web#151]
yml文件里面已经配置OPENAI_API_KEY了，请问这个怎么回事

**Comment by Kerwin1202** [comment]
这个设置一下看看，，如果还不行 截图看下
<img width="461" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/c81c6065-13ab-47d0-a107-04eeccf417bb">

**Comment by yd1261137568** [comment]
> 这个设置一下看，，如果还不行 截图看下 <img alt="图像" width="461" src="https://user-images.githubusercontent.com/16319833/239798134-c81c6065-13ab-47d0-a107-04eeccf417bb.png">
直接把yml文件复制下来做了一些改动
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33176197/fabd4442-2766-419b-8547-5267d97af5ef)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33176197/5d4af739-30f8-4251-b602-2c44ccb0597b)

**Comment by yd1261137568** [comment]
全部的yml
version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 二选一
      OPENAI_API_KEY: sk-xxxx
      # 二选一
      OPENAI_ACCESS_TOKEN: 
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://api.openai.com
      # ChatGPTAPI ChatGPTUnofficialProxyAPI
      OPENAI_API_MODEL: ChatGPTAPI
      # 反向代理，可选
      API_REVERSE_PROXY: 
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 600000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: 
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: 
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY: 
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: xxx
      # 网站名称
      SITE_TITLE: ChatGpt Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017'
      # 网站是否开启注册
      REGISTER_ENABLED: 'true'
      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
      REGISTER_MAILS: '@qq.com,@sina.com,@163.com'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: xxx
      # 开启注册之后 超级管理邮箱
      ROOT_USER: xxxx@qq.com
      # 开启注册之后 网站域名 不含 / 注册的时候发送验证邮箱使用
      SITE_DOMAIN: http://127.0.0.1:3002
      # 开启注册之后 发送验证邮箱配置
      SMTP_HOST: smtp.qq.com
      SMTP_PORT: 465
      SMTP_TSL: 'true'
      SMTP_USERNAME: xxxx@qq.com
      SMTP_PASSWORD: xxxxx
      # 是否开启敏感词审核, 因为响应结果是流式 所以暂时没审核
      AUDIT_ENABLED: 'false'
      # https://ai.baidu.com/ai-doc/ANTIPORN/Vk3h6xaga
      AUDIT_PROVIDER: baidu
      AUDIT_API_KEY: 
      AUDIT_API_SECRET: 
      AUDIT_TEXT_LABEL: 
    links:
      - database

  database:
    image: mongo
    container_name: chatgptweb-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxx
      MONGO_INITDB_DATABASE: chatgpt

volumes:
  mongodb: {}

**Comment by yd1261137568** [comment]
> 用了你的配置测试了下没有问题。。不过是个假的。。。怀疑你之前部分配置过错的，所以可以点击设置测试看
> 
> <img alt="图像" width="799" src="https://user-images.githubusercontent.com/16319833/239809572-25a478e3-daaa-4986-9eb4-962a10c94b95.png"> <img alt="图像" width="434" src="https://user-images.githubusercontent.com/16319833/239809705-6eaf8597-c219-4ede-bb69-8a3c3d5ab836.png"> <img alt="图像" width="806" src="https://user-images.githubusercontent.com/16319833/239809748-efa71f0d-6ed3-4dc7-b7a1-83153f2f35c8.png">

在设置里面配置了一下，没问题了，感谢
