### ISSUE TITLE
OPENAI_API_KEY方式启动后发送内容没链接到openai 提示 好像出错了，请稍后再试。

### ISSUE THREAD

**Issue by XIRALIP** [Kerwin1202/chatgpt-web#154]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/7464669/bc4ef922-b126-4bde-96d4-cd43d278a479)

这种错误日志怎么查看？

**Comment by XIRALIP** [comment]
systemMessage
: 
"You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."

**Comment by XIRALIP** [comment]
接口/api/chat-process 
request：
{"roomId":1684752807045,"uuid":1684761941708,"regenerate":false,"prompt":"测试","options":{},"systemMessage":"You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.","temperature":0.8,"top_p":1}
response：{}

这是为啥呢

**Comment by Kerwin1202** [comment]
这好像看不出啊。。
