### ISSUE TITLE
已经用了好久，有很多聊天记录，为什么统计不出来呢

### ISSUE THREAD

**Issue by JeazW** [Kerwin1202/chatgpt-web#156]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/75829171/bce88f55-8ca6-4184-9db9-7f163aba0030)

**Comment by Kerwin1202** [comment]
如果很重要。可以 https://github.com/Kerwin1202/chatgpt-web/pull/112#issue-1698872653 这里参考  不是很重要，可以后续新的会统计

**Comment by zhujunsan** [comment]
用的mongodb是什么版本的？

**Comment by jamebal** [comment]
我的也是这样，没有统计数据， MongoDB server version: 4.4.11

**Comment by zhujunsan** [comment]
我找了用4的朋友看，是有数据的，那看来不是版本问题。数据库里的 chat_usage 表能找条数据看下么？

**Comment by jamebal** [comment]
<img width="179" alt="截屏2023-05-23 12 01 56" src="https://github.com/Kerwin1202/chatgpt-web/assets/49510841/85d746b9-67b8-4a8e-92e6-7ab585415b42">

**Comment by zhujunsan** [comment]
所以连接mongo的这个账户，是没创建collection的权限的么？

**Comment by zhujunsan** [comment]
你创建个 chat_usage 的 collection 然后再问一句看看？

**Comment by jamebal** [comment]
<img width="216" alt="截屏2023-05-23 12 08 04" src="https://github.com/Kerwin1202/chatgpt-web/assets/49510841/45a81f96-e1ec-45a8-81c9-845af7fb152a">
创建了chat_usage，然后新建聊天问几个问题，还是没有

**Comment by zhujunsan** [comment]
hmmmm，很奇怪啊。确定代码版本没问题对吧？账户权限确认没问题么？看起来要么是没权限写入，要么是写入的代码没跑到？

**Comment by jamebal** [comment]
<img width="519" alt="截屏2023-05-23 16 43 42" src="https://github.com/Kerwin1202/chatgpt-web/assets/49510841/dcdbee2e-962f-4f8f-b045-2a8a933d7ab8">

我在本地跑了一下，result.data 里面没有detail和usage

**Comment by Kerwin1202** [comment]
access token 吧，这个好像是没有的

**Comment by jamebal** [comment]
是的，换成api就有了，但是换成api之后又把之前access token的记录统计进去了

**Comment by Kerwin1202** [comment]
因为 api 要单独维护上下文，所以会把当前对话历史一定数量传过去，所以会比较多，后续看简单优化下 也另外计算一下 access token的 使用

**Comment by jamebal** [comment]
大佬加油！如何这个统计是为了方便查看api的使用情况，那就不用统计access token的使用比较好
