### ISSUE TITLE
'Stop Responding'按钮没有真的停止

### ISSUE THREAD

**Issue by jamebal** [Kerwin1202/chatgpt-web#157]
AccessToken模式下，按下`Stop Responding`，再次提问会提示：ChatGPT error 429: {"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}

**Comment by zhujunsan** [comment]
api 模式也没真的停止。代码里就是前端停了，后端没停

**Comment by jamebal** [comment]
所以后端能停吗

**Comment by zhujunsan** [comment]
就，代码没处理，要支持的话需要改

**Comment by jamebal** [comment]
希望大佬支持下，感谢！GPT回复很慢的时候就要等半天

**Comment by zhujunsan** [comment]
上游依赖的 transitive-bullshit/chatgpt-api 库似乎也没提供这个支持
