### ISSUE TITLE
最新版本问题

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#158]
大佬，更新到最新版本之后，为啥普通用户设置里面也跟管理用户的界面一样呢？然后模型指定了之后，在前端页面还是显示的是所有的模型，是我哪块设置问题吗？
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/357afdf2-70e2-4b15-8c8a-4777f77660fd)

![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/a934c5ce-2c49-439f-a0d4-95cc38e435c6)

![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/e6f7b82e-47d4-441e-9e6e-2c034344a3db)

**Comment by Kerwin1202** [comment]
bug, 估计是我改权限导致的。 但是应该不能保存，晚点我隐藏下

另外 前端页面显示所有的，这个是没优化，确实应该优化为支持的模型。。

**Comment by dqzboy** [comment]
好的大佬，辛苦

**Comment by dqzboy** [comment]
User Roles 修改后 好像没变化

**Comment by Kerwin1202** [comment]
指的用户的 还是key的。。

**Comment by dqzboy** [comment]
Keys 管理里面的这个用户权限 这个是用户的权限吧？ 我改了没啥反应 哈哈哈

**Comment by Kerwin1202** [comment]
管理员。。

**Comment by dqzboy** [comment]
大佬 具体作用体现在哪块呢？没懂

**Comment by Kerwin1202** [comment]
我说错了，，我以为问的是 key 管理模块，，  这个权限，是和key 走的啊。。  就是 key 有一些权限 用户有一些权限，符合这个权限可以用对应的key

**Comment by dqzboy** [comment]
更新了，这就明白了  界面有显示了 哈哈

**Comment by dqzboy** [comment]
> 更新了，这就明白了 界面有显示了 哈哈

又有个新问题，对话模型 现在就剩下4个了吗？
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/228a3157-7374-4591-949c-2e22b82630ca)

**Comment by Kerwin1202** [comment]
好了。push 了   不过暂时不着急打包了。。下次再说

**Comment by dqzboy** [comment]
Guest权限，我的理解 应该是访客权限，也就是只能看不能问答吧？设置Guest好像跟USER权限一样

我是源码部署的，我服务器编译就行

**Comment by Kerwin1202** [comment]
其实名字随便的，我所想得是，自己用 admin 一般人用 guest 比如只给 gpt3.5  有的人想给他所有的 比如gpt4 但是我自己也要用  所以三个层级，，只有2个不够

**Comment by dqzboy** [comment]
哦哦 明白了

**Comment by Kerwin1202** [comment]
当然了，我估计搞反了，默认的是 user 了，换个理解一样

**Comment by dqzboy** [comment]
> > 更新了，这就明白了 界面有显示了 哈哈
> 
> 又有个新问题，对话模型 现在就剩下4个了吗？ ![image](https://user-images.githubusercontent.com/42825450/240166562-228a3157-7374-4591-949c-2e22b82630ca.png)

大佬。是这个问题也修复了吗？我这边重新构建之后还是一样的呢

**Comment by Kerwin1202** [comment]
估计代码不是最新的 你pull下

**Comment by dqzboy** [comment]
好了 可以了 感谢大佬

**Comment by dqzboy** [comment]
大佬，还有个问题需要请教下；目前我接口代理使用的go-chatgpt-api这个项目，他这个项目目前chatgptAPI跟AccessToekn的接口不一样，如果keys管理里面既有accesstoekn也有API，那么这个接口代理我看目前只能设置一个
ChatGPTUnofficialProxyAPI代理地址是：http://127.0.0.1:8080/chatgpt/conversation
ChatGPTAPI代理地址是：http://127.0.0.1:8080/platform

![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/af16d1b8-a020-4051-a954-fd7157b4325f)

**Comment by Kerwin1202** [comment]
一个是 api  一个是 accesstoken
<img width="618" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/ce8baf88-cd12-4d72-b246-7cef55f5091e">

**Comment by dqzboy** [comment]
明白了
