### ISSUE TITLE
2.13.0 最新版本问题

### ISSUE THREAD

**Issue by chilohwei** [Kerwin1202/chatgpt-web#159]
首先感谢作者，成功部署并使用了一段时间。今天看到更新了 2.13.0版本后，在服务器上用：
```
docker-compose pull
docker-compose up -d
```
拉取最新镜像并重新部署了下，目前功能使用正常。但是退出重新登录后，管理员账户失效了，无法看到用户管理等  tab 选项。另外在注册的时候提示：`Cannot read properties of null (reading 'config')` ，麻烦帮忙看一下是什么原因导致的，谢谢～

**Comment by Kerwin1202** [comment]
已经修了，过半小时或者一个小时等我发个新版本

**Comment by chilohwei** [comment]
> 已经修了，过半小时或者一个小时等我发个新版本

感谢，回复好快呀～
