### ISSUE TITLE
最新版本，只有三个模型可以选择

### ISSUE THREAD

**Issue by LannyChan** [Kerwin1202/chatgpt-web#162]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/74071703/e3c3a53e-b3fc-46f9-94e7-b378ce7f2ede)

**Comment by dqzboy** [comment]
拉最新代码进行更新

**Comment by SiMPlerMeta** [comment]
这个模型后面对应的数字是啥意思呀

**Comment by SiMPlerMeta** [comment]
哦哦，了解了
