### ISSUE TITLE
是否可以接入Poe

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#164]
大佬，目前我在QQ使用了一个项目接入了Poe，目前使用下来很稳定，而且主要是3.5是免费的没限制；可以通过cookie的方式直接入，不需要开会员和API，只需要创建账号就能使用。不知道咱们这个项目接入是否困难；这是参考项目的地址：[chatgpt-mirai-qq-bot](https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-poe.com)

**Comment by Kerwin1202** [comment]
稍微看了下，但是估计短时间不考虑，这个相当于另外自己对接一个api了，poe 里面有各个模块

**Comment by dqzboy** [comment]
嗯嗯，好的大佬，辛苦。如果后面可以接入，就能免费白嫖gpt-3.5了，哈哈哈
