### ISSUE TITLE
mongodb4.49，统计提示{"ok":0,"code":168,"codeName":"InvalidPipelineOperator"}

### ISSUE THREAD

**Issue by tczj199076** [Kerwin1202/chatgpt-web#168]
mongodb4.49，统计提示{"ok":0,"code":168,"codeName":"InvalidPipelineOperator"}
这是我更新打包后的数据表，
![image](https://github.com/Kerwin1202/chatgpt-web/assets/13128955/e79a71f2-3b3a-4616-a8a8-0a791ee34d1f)
我的版本是4.49

**Comment by tczj199076** [comment]
好的，升级到多少版本合适啊

**Comment by Kerwin1202** [comment]
我的是 5.0.x 是可以的

**Comment by tczj199076** [comment]
已升级到6.0.4，问题已解决，但是数据统计不对，我今日token使用25221，问了一次是2627，实际应该是27848，统计出来的是27868，每次都是会多20，这个20哪里来的

**Comment by tczj199076** [comment]
没事了，我自己看错了
