### ISSUE TITLE
没有可用的配置。请再试一次 | No available configuration. Please try again.

### ISSUE THREAD

**Issue by Timoshao** [Kerwin1202/chatgpt-web#169]
配置时正常的，偶尔出现这个错误。
![image](https://github.com/Kerwin1202/chatgpt-web/assets/108260847/cc2d5ec2-acd2-423c-b7f0-31dfc844ba74)

**Comment by xiaoguaishou92** [comment]
可能是同时问的人太多了。我猜的

**Comment by Timoshao** [comment]
> 可能是同时问的人太多了。我猜的

不是的，刚部署好，自己测试的时候发现的

**Comment by Kerwin1202** [comment]
默认不配置环境变量了，所以这里加个
<img width="1419" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/c3e8adcc-0e68-4889-863a-094121df44fd">

**Comment by qsc19971022** [comment]
> 默认不配置环境变量了，所以这里加个 <img alt="image" width="1419" src="https://user-images.githubusercontent.com/16319833/240549978-c3e8adcc-0e68-4889-863a-094121df44fd.png">

配置了有效key，还是会出现这个问题，是什么原因呢

**Comment by Kerwin1202** [comment]
得 key 设置的截图 以及 登录的用户权限啥的发上来看看了

**Comment by maxage** [comment]
嘿，我也怪了，也是这样的。更新后。
没有可用的配置。请再试一次 | No available configuration. Please try again.

![](https://oss.blog.nasvip.net/blog/20230524204156.png)

**Comment by maxage** [comment]
更新前都正常，反代  api接口都是正常的 使用用户是admin组的。

**Comment by Kerwin1202** [comment]
三个，一个是 Key 的role 一个是 user 的role  以及你发消息选择的是什么模型，截图看看，，如果可以最好数据库里的也给我看下

**Comment by qsc19971022** [comment]
> 得 key 设置的截图 以及 登录的用户权限啥的发上来看看了

![image](https://github.com/Kerwin1202/chatgpt-web/assets/54890307/db705b46-8bf7-48cb-af69-dc2448308919)

**Comment by Kerwin1202** [comment]
不是，我的意思是分别 截图下界面上的  用户管理（你登录的用户） key 使用的key 以及聊天使用的模型
然后如果可以 分别上诉的数据库的配置

**Comment by maxage** [comment]
我没动配置，莫名其妙又好了。又正常了。。。

**Comment by Kerwin1202** [comment]
一个模型多个key，，随机key。。。 不是轮询

**Comment by dqzboy** [comment]
> 我没动配置，莫名其妙又好了。又正常了。。。
> 
> 大佬能不能整个公告页面？
> 
> 如果存在某个模型 比如 chatgpt3.5(2) 是不是两个轮询？还是哪种机制？

公告是不是类似他这个：https://chat.aisvip.top/#/chat
他这个好像就是基于大佬的项目进行了自己改的

**Comment by assassinliujie** [comment]
我是用着用着出BUG了，很奇怪

**Comment by Kerwin1202** [comment]
> > 三个，一个是 Key 的role 一个是 user 的role 以及你发消息选择的是什么模型，截图看看，，如果可以最好数据库里的也给我看下
> > 用户是ADMIN，key的role是
> > ![图片](https://user-images.githubusercontent.com/68693675/240841295-147fb3dd-94d5-4888-a393-2c8f47a987ab.png)
> > 选择的模型是3.5和4都试过了，而且是正在使用的过程中突然不行了，

你是不是用的过程，点击了 stop response 然后又发了一次。。

**Comment by assassinliujie** [comment]
> > 是有这样的操作，发自我的荣耀手机-------- 原始邮件 --------发件人： Kerwin1202 _**@**_._**>日期： 2023年5月25日周四 下午4:59收件人： Kerwin1202/chatgpt-web _**@**_.**_>抄送： assassinliujie _**@**_._**>, Comment _**@**_.**_>主 题： Re: [Kerwin1202/chatgpt-web] 没有可用的配置。请再试一次 | No available configuration. Please try again. (Issue #169) 三个，一个是 Key 的role 一个是 user 的role 以及你发消息选择的是什么模型，截图看看，，如果可以最好数据库里的也给我看下 用户是ADMIN，key的role是 选择的模型是3.5和4都试过了，而且是正在使用的过程中突然不行了， 你是不是用的过程，点击了 stop response 然后又发了一次。。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 页面的stop 只是页面不输出，服务器还是在调用的。。这个后续看情况优化吧 这个issue 有 #157

我目前发现多人同时用的时候经常会出这个问题，请问是不是这个原因

**Comment by Kerwin1202** [comment]
> > > 是有这样的操作，发自我的荣耀手机-------- 原始邮件 --------发件人： Kerwin1202 _**@**_._**>日期： 2023年5月25日周四 下午4:59收件人： Kerwin1202/chatgpt-web _**@**_.**_>抄送： assassinliujie _**@**_._**>, Comment _**@**_.**_>主 题： Re: [Kerwin1202/chatgpt-web] 没有可用的配置。请再试一次 | No available configuration. Please try again. (Issue #169) 三个，一个是 Key 的role 一个是 user 的role 以及你发消息选择的是什么模型，截图看看，，如果可以最好数据库里的也给我看下 用户是ADMIN，key的role是 选择的模型是3.5和4都试过了，而且是正在使用的过程中突然不行了， 你是不是用的过程，点击了 stop response 然后又发了一次。。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 页面的stop 只是页面不输出，服务器还是在调用的。。这个后续看情况优化吧 这个issue 有 #157
> 
> 我目前发现多人同时用的时候经常会出这个问题，请问是不是这个原因

同时得看多少人了，如果 3秒内都没回复完，又多人大于key 那肯定是会的

**Comment by Decikingship** [comment]
我们也遇到了同样的问题,要反复的点重试才行

**Comment by assassinliujie** [comment]
> > > > 是有这样的操作，发自我的荣耀手机-------- 原始邮件 --------发件人： Kerwin1202 _**@**_._**>日期： 2023年5月25日周四 下午4:59收件人： Kerwin1202/chatgpt-web _**@**_.**_>抄送： assassinliujie _**@**_._**>, Comment _**@**_.**_>主 题： Re: [Kerwin1202/chatgpt-web] 没有可用的配置。请再试一次 | No available configuration. Please try again. (Issue #169) 三个，一个是 Key 的role 一个是 user 的role 以及你发消息选择的是什么模型，截图看看，，如果可以最好数据库里的也给我看下 用户是ADMIN，key的role是 选择的模型是3.5和4都试过了，而且是正在使用的过程中突然不行了， 你是不是用的过程，点击了 stop response 然后又发了一次。。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.***>
> > > 
> > > 
> > > 页面的stop 只是页面不输出，服务器还是在调用的。。这个后续看情况优化吧 这个issue 有 #157
> > 
> > 
> > 我目前发现多人同时用的时候经常会出这个问题，请问是不是这个原因
> 
> 同时得看多少人了，如果 3秒内都没回复完，又多人大于key 那肯定是会的，不过我突然想起来会稍微优化下，没记错之前的api key 是可以1分钟内多人，，目前被我限制死了一次只能一人 好像有点区别

在哪进行修改一次的人数呢，麻烦作者了
