### ISSUE TITLE
现在版本构建时 env 文件是否还需要？

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#177]
目前构建新版时，比如我 env文件里面配置了 OPENAI_API_KEY，但是我在web端，只给token，这个时候就会出现 配置不存在的报错；目前我发现OPENAI_API_KEY和OPENAI_ACCESS_TOKEN 在env里面都为空，构建也不报错了，所以就想问下现在构建是否还需要env文件呢 或者说 env 文件里面 哪些配置是必须的；好像Mongo是必须在env里面配置，对吧

**Comment by Kerwin1202** [comment]
可能 env 文件没更新，可以看 docker-compose.yml 里，我是删掉了一些 OPENAI_API_KEY 啥的，这个都在页面上加，后续可能也会进一步删掉，这样，省得配置太多。有页面操作方便些

**Comment by dqzboy** [comment]
好的，大佬。确实放在页面操作方便些，个人觉得把一些敏感的配置 存在 env就行
