### ISSUE TITLE
是否可以删除未通过申请用户以及将邮箱添加至黑名单

### ISSUE THREAD

**Issue by assassinliujie** [Kerwin1202/chatgpt-web#178]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/68693675/dad9e24e-faba-4089-ab1a-5f1ace49d63c)
有些人会一直尝试申请，我也没法正常拉黑，我以前就去mongodb里面把状态码随便改个值让他没法继续进行，但是这样说实话也不算正常方法

**Comment by Kerwin1202** [comment]
有这个功能的，没有打包倒最新的docker，下次打包，拉黑邮箱目前没有

**Comment by assassinliujie** [comment]
感谢

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kerwin1202/chatgpt-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kerwin1202/chatgpt-web] 是否可以删除未通过申请用户以及将邮箱添加至黑名单 (Issue #178)





 
有这个功能的，没有打包倒最新的docker，下次打包，拉黑邮箱目前没有
