### ISSUE TITLE
功能提議：添加修改默認語言和主題的選項

### ISSUE THREAD

**Issue by 1030283726** [Kerwin1202/chatgpt-web#181]
我發現在第一次進入網站的，默認都是 簡體中文界面，以及默認為白天模式

目前的我的解法是修改文件

提議添加個在前端修改默認語言（比如英文） 
以及修改默認為黑夜模式，白天模式或自動

發現問題：
繁體中文 有些文字翻譯不完整， 
目前也是修改文件解決

**Comment by Kerwin1202** [comment]
支持啊。  至于有的翻译不完整，，可以提 request merge，有的是偷懒直接赋值粘贴了，包括其他语种
<img width="710" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/43b5d1b6-7689-4fcd-b507-f37da8616dd6">

**Comment by Kerwin1202** [comment]
除了繁体本地化 部分没有翻译，其他没问题，就先关闭了
