### ISSUE TITLE
【建议】关于批量询问的功能的可行性

### ISSUE THREAD

**Issue by cvpv** [Kerwin1202/chatgpt-web#182]
O(∩_∩)O哈哈~，我想批量问一些问题，理论上能不能实现呢？
比如通过Excel导入一些问题，chatGPT能不能批量获取答案，然后导出

**Comment by huangwb8** [comment]
你这种功能可以使用python之类的脚本语言实现吧，我印象中用python调用openai API并不难？不懂可以chatGPT一下。
