### ISSUE TITLE
错误。不能使用“GPT-4”模型

### ISSUE THREAD

**Issue by dzevs** [Kerwin1202/chatgpt-web#184]
你好，我在使用“ChatGPTAPI”模型时发现了一个错误。当我使用 GPT-4 更改模型时，响应仍然来自 GPT-3.5 turbo

**Comment by dzevs** [comment]
![Screenshot_53](https://github.com/Kerwin1202/chatgpt-web/assets/25576759/971de976-0e58-43f0-a63c-bf284eee21de)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/25576759/37d72648-3753-4e9c-8286-65cf5806ec43)

**Comment by Kerwin1202** [comment]
没打包。。。 41ba8735b9827f785668a1dc0a473cfa638af0fd

**Comment by dzevs** [comment]
先生，我已经更正了那部分代码。 但我仍然不能像上面的屏幕截图那样使用 gpt-4 模型。

![image](https://github.com/Kerwin1202/chatgpt-web/assets/25576759/eceae822-91be-4421-8deb-aaa47174a51f)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/25576759/728e7b70-4b01-4cca-948e-72546fb6b00d)

**Comment by dzevs** [comment]
我设法通过在“systemMessage”上添加模型名称来解决这个问题。 也许老板有其他想法。 谢谢你！

![image](https://github.com/Kerwin1202/chatgpt-web/assets/25576759/54bb8744-f4ef-4c50-86b6-db5dc52a7992)

**Comment by Kerwin1202** [comment]
<img width="1210" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/d4081fc5-dd0f-4341-ae36-f92cfef15a1f">
<img width="348" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/96819932-1c09-4f2e-9ecf-7084ed8bb497">

上面选择的是对应的

下面是不对应的 只留了一个
<img width="475" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/8b9d059f-f53d-4365-ad97-61d8e4ea0199">
下面虽然还是选择这个，但是实际上其实不对，因为已经没有这个模型了，所以就无法读取对应的模型
<img width="358" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/cc9595cf-0c87-480a-ab1c-19d8a44dd65d">
<img width="1242" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/5e609cc5-5b82-4f00-935d-db67cd467ca7">

**Comment by dzevs** [comment]
老板有效代码我确实从 OpenAI API 检查过它。我在操场上也试过，虽然我用的是GPT-4模型，但他还是会回答他是GPT-3模型。如果我使用“accessToken”，那没问题。我认为这个问题已经解决了，你可以关闭它。谢谢。
