### ISSUE TITLE
未开启新用户审核，但是还是需要审核是什么原因？

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#189]
如题，但是也不是所有新注册的用户都会进行审核，会偶尔有那么一两个新注册的用户就需要审核才行，不知道是为啥。新用户审核是一直关闭的。

**Comment by dqzboy** [comment]
是不是因为注册用户的邮箱是个假的，不能自动通过注册登入，就会需要手动审核？如果是这样的话，能否直接就是拒绝掉，不要显示在管理员的审核名单里呢？

**Comment by Kerwin1202** [comment]
你看到的是  AdminVerify  还是 PreVerify   前者才是管理员审核，后者是 对方需要到自己的邮箱验证

**Comment by dqzboy** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/e10791e5-d463-49ac-9a47-b78d3fafe17f)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/3a038f64-55a2-4d89-b6e2-76e15417605e)

我个人觉得  是不是等用户在邮箱里面点击了那个注册链接之后，在把这个显示到管理后台页面呢？

**Comment by Kerwin1202** [comment]
我觉得这样没问题，你的意思我了解，但是显示只有好处，可以知道什么人注册了。 如果不需要可以删除就无法再次用这个注册了

**Comment by dqzboy** [comment]
嗯嗯，显示出来肯定是没问题的。我的意思 不是用户点击注册了 就直接显示出来，而是等用户通过邮箱点击了注册链接了 然后再显示出来  是不是会好一些。现在的话 就是用户只要使用一个 符合后缀的邮箱就可以注册，一点注册就直接可以在管理员这边显示

**Comment by Kerwin1202** [comment]
嗯嗯，我知道你说的。就是注册就显示，先不改吧。

显示出来一方面 可以看到万一有人批量刷，但是不验证，也可以知道下，自己去排查预防，不显示数据库加了几万条都不知道

**Comment by dqzboy** [comment]
明白
