### ISSUE TITLE
docker compose 部署之后没有用户管理

### ISSUE THREAD

**Issue by Zeus-Athena** [Kerwin1202/chatgpt-web#191]

**Comment by Kerwin1202** [comment]
部署之后  这个设置了吗，设置 了之后需要用这个账号去注册 ，然后登录 默认这个账号才有权限
<img width="397" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/9f0ee837-bc53-4d99-8bf5-c3d0ce00aab6">

**Comment by Zeus-Athena** [comment]
添加root_user之后可以了。 有个新的问题 OPENAI_API_KEY 和  OPENAI_ACCESS_TOKEN 都设置了，全部提示 Invalid URL


报错如下：
sendMessage (31 tokens) {
chatgptweb  |   max_tokens: 1000,
chatgptweb  |   model: 'gpt-3.5-turbo',
chatgptweb  |   temperature: 0.8,
chatgptweb  |   top_p: 1,
chatgptweb  |   presence_penalty: 1,
chatgptweb  |   messages: [
chatgptweb  |     {
chatgptweb  |       role: 'system',
chatgptweb  |       content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
chatgptweb  |     },
chatgptweb  |     { role: 'user', content: 'hello', name: undefined }
chatgptweb  |   ],
chatgptweb  |   stream: true
chatgptweb  | }
chatgptweb  | TypeError [ERR_INVALID_URL]: Invalid URL
chatgptweb  |     at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
chatgptweb  |     at new NodeError (node:internal/errors:399:5)
chatgptweb  |     at new URL (node:internal/url:560:13)
chatgptweb  |     at Request (/app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/request.js:55:16)
chatgptweb  |     at <anonymous> (/app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:51:19)
chatgptweb  |     at new Promise (<anonymous>)
chatgptweb  |     at fetch (/app/node_modules/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js:49:9)
chatgptweb  |     at options.fetch (/app/build/index.js:10362:37)
chatgptweb  |     at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:46:21)
chatgptweb  |     at Promise.then.promptTokens (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:259:11)
chatgptweb  |     at new Promise (<anonymous>)
chatgptweb  |     at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:237:23)
chatgptweb  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chatgptweb  |     at chatReplyProcess (/app/build/index.js:10228:22)
chatgptweb  |     at <anonymous> (/app/build/index.js:10966:14) {
chatgptweb  |   input: 'xxx/v1/chat/completions',
chatgptweb  |   code: 'ERR_INVALID_URL'
chatgptweb  | }
chatgptweb  | sendMessage (31 tokens) {
chatgptweb  |   max_tokens: 1000,
chatgptweb  |   model: 'gpt-3.5-turbo',
chatgptweb  |   temperature: 0.8,
chatgptweb  |   top_p: 1,
chatgptweb  |   presence_penalty: 1,
chatgptweb  |   messages: [
chatgptweb  |     {
chatgptweb  |       role: 'system',
chatgptweb  |       content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
chatgptweb  |     },
chatgptweb  |     { role: 'user', content: 'hello', name: undefined }
chatgptweb  |   ],
chatgptweb  |   stream: true
chatgptweb  | }
chatgptweb  | TypeError [ERR_INVALID_URL]: Invalid URL

**Comment by Kerwin1202** [comment]
新版放到这里了 
<img width="301" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/91bf75dd-c702-4a76-b5f4-62a3ed0288bf">
<img width="255" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/b3246f74-2133-42be-9cc3-f251d57ff5c8">
