### ISSUE TITLE
更新到最新版本 第一次打开会有错误提示，但是可以正常使用

### ISSUE THREAD

**Issue by wejudging** [Kerwin1202/chatgpt-web#193]
[![p9L5YfU.png](https://s1.ax1x.com/2023/05/28/p9L5YfU.png)](https://imgse.com/i/p9L5YfU)

**Comment by Kerwin1202** [comment]
看下这个 你选择的是不是不在这里
<img width="437" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/06b47055-9fbe-4b98-964a-9f0c3875d714">

**Comment by wejudging** [comment]
我默认就选了一个第一个3.5，你可以打开我的试试，网址是 https://ai.weijiajin.com

**Comment by 404gods** [comment]
+1 同样问题。设置的是OPENAI_API_MODEL: ChatGPTAPI。

**Comment by Kerwin1202** [comment]
没登录好像是，，登录也会吗？

**Comment by wejudging** [comment]
登录后不会有

**Comment by wejudging** [comment]
> 没登录好像是，，登录也会吗？

只有第一次没登录会提示，登录后就没了

**Comment by 404gods** [comment]
请问前端在哪里能看到版本号？

**Comment by Kerwin1202** [comment]
> 请问前端在哪里能看到版本号？

看不到
