### ISSUE TITLE
一键脚本

### ISSUE THREAD

**Issue by krxiaoyu** [Kerwin1202/chatgpt-web#196]
有哪位大佬可以做一个一键安装脚本吗？ 本地安装发现经常出错

**Comment by dqzboy** [comment]
这个，[一键脚本](https://github.com/dqzboy/ChatGPT/tree/main/ChatGPT-Web-Admin)

**Comment by huangwb8** [comment]
@krxiaoyu 

没必要啦，看我的教程就行： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

**Comment by krxiaoyu** [comment]
感谢回复
