### ISSUE TITLE
添加多个key 删除之后，聊天页面显示还有之前的数量

### ISSUE THREAD

**Issue by Timoshao** [Kerwin1202/chatgpt-web#197]
之前添加多个key,把一些删除之后，只保留了一个，聊天页面选择模型那里还是显示有多个。
![image](https://github.com/Kerwin1202/chatgpt-web/assets/108260847/20807dfb-7243-40c1-88e0-0406d4775a71)

![image](https://github.com/Kerwin1202/chatgpt-web/assets/108260847/eebe76aa-d085-456f-9f04-d0fd6598e394)

**Comment by Timoshao** [comment]
把数据库中哪些状态为6的全部删除之后 显示正常了

**Comment by Kerwin1202** [comment]
和数据库没关系，你没刷新，刷新下页面就好了

**Comment by Timoshao** [comment]
> 和数据库没关系，你没刷新，刷新下页面就好了

我在试试吧 
我试过换了浏览器以及清空缓存，发现还是这样的 才数据库直接删除的

**Comment by Kerwin1202** [comment]
最新版本吗

**Comment by Timoshao** [comment]
> 最新版本吗
是的 早上更新的最新版。
那些key是之前添加的。
