### ISSUE TITLE
同一个会话窗口，首次提问正常，紧接着提问就 404

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#201]
在同一个会话里面。第一次提问没问题，紧接着提问就提示404；刷页面就提示 ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined；使用的是accesstoken
![Snipaste_2023-05-29_15-51-34](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/54dab0e7-ab71-4e58-9a55-2d9a5c7928e7)

![Snipaste_2023-05-29_15-52-08](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/3b3f117f-e8d3-455d-9cd8-79a9daabf4ec)

**Comment by Kerwin1202** [comment]
哦，可能的，因为 accesstoken 每次必须要所属 聊天室 以及父消息是什么，所以第一个报错也有一个记录，跟着说话的话，读取报错的消息对应的聊天室以及父消息 其实没有父消息的，所以报错了，你可以看下数据库里是否有第一个保存的记录

**Comment by Kerwin1202** [comment]
另外你截图里的第一个报错的消息 是怎么个情况下的报错，，

**Comment by dqzboy** [comment]
就是同一个会话里面，首次提问之后，gpt回答完之后，接着问就就会报这个404错误；配置的2个accesstoken，之前点重试就会可以正常接着回复，现在不行，必须重新开一个会话才行

**Comment by Kerwin1202** [comment]
这个问题之前好像和你说过呀，没问题哦，access token 目前不支持多个同时设置的

**Comment by dqzboy** [comment]
嗯嗯 好的，就是这次比上个版本 更容易出现

**Comment by Kerwin1202** [comment]
这个没关系，随机的意思是1/2 就和投硬币，连续十次都是正面向上不能说 向上概率就是100%。只不过你这次随机倒另一个不存在的 access token 概率多了些

**Comment by dqzboy** [comment]
有这个可能
