### ISSUE TITLE
AccessToken模式多Key问题

### ISSUE THREAD

**Issue by nbMars1980** [Kerwin1202/chatgpt-web#203]
如果使用AccessToken模式，并且添加了多个来自不同账号的Key时，如果连续对话中使用不同的key会导致
ChatGPT error 404: {"errorMessage":"[object Object]"}
报错，原因是对应的官方网页端没有对应的chat
大佬能否解决一下这个问题？

**Comment by popcell** [comment]
不能这么用的

**Comment by popcell** [comment]
> 如果使用AccessToken模式，并且添加了多个来自不同账号的Key时，如果连续对话中使用不同的key会导致 ChatGPT error 404: {"errorMessage":"[object Object]"} 报错，原因是对应的官方网页端没有对应的chat 大佬能否解决一下这个问题？
不能这么用的

**Comment by Kerwin1202** [comment]
会修复，已知
