### ISSUE TITLE
没有可用的配置，这个怎么解决

### ISSUE THREAD

**Issue by tczj199076** [Kerwin1202/chatgpt-web#204]
用的好好的，时不时提示：没有可用的配置，为什么啊

**Comment by Kerwin1202** [comment]
多人用？

**Comment by tczj199076** [comment]
嗯，多人用，我是plus会员，绑定的美国的信用卡

**Comment by a137235** [comment]
是的，升级后经常出现

**Comment by Kerwin1202** [comment]
是啊，如果你就一个 key 多人同时用，那不是正常吗，一个key 目前限制了 同一个 时间只能占用3个人，除非等待前一个释放，就是以前可能会出现429的情况， 可以配置下多个key呢

**Comment by jacksnowfuck** [comment]
我4个key多人用也有这个情况出现，是因为并发多了才这样吗，昨天一次，今天一次，每次都是重启了才恢复

**Comment by tczj199076** [comment]
> 是啊，如果你就一个 key 多人同时用，那不是正常吗，一个key 目前限制了 同一个 时间只能占用3个人，除非等待前一个释放，就是以前可能会出现429的情况， 可以配置下多个key呢

可是我只有一个key，意思就是说，我用我的plus的key，配置多个模型吗？

**Comment by tczj199076** [comment]
但是像我是plus的key，不限制的情况下，怎么修改才能不出现不可用的配置呢

**Comment by wshze** [comment]
你们用的是api的GPT4还是网页版的plus？

**Comment by dqzboy** [comment]
我一个人用，一个key；也会出现没有可用的配置
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/394c2cbe-668b-4a46-bfed-418f1c94a997)

**Comment by dqzboy** [comment]
> > 我一个人用，一个key；也会出现没有可用的配置 ![image](https://user-images.githubusercontent.com/42825450/242566914-394c2cbe-668b-4a46-bfed-418f1c94a997.png)
> 
> 你解决了吗

我这个后面发现是因为key到期了  到期后也是这个提示

**Comment by Kerwin1202** [comment]
> 
> 我的是经常这样 半天才能回答一次问题

一个人用还是怎么的 以及配置是什么样的，

**Comment by Kerwin1202** [comment]
> > > 我的是经常这样 半天才能回答一次问题
> > 
> > 
> > 一个人用还是怎么的 以及配置是什么样的，
> 
> 会不会是我clash问题，我clash关掉，就能回复出来

那就是翻墙的问题可能性比较大了。。这也没啥看得，部署没问题，回复慢之类的大概率是网络问题，有时候使用access token 也会比api 稍微慢些，，然后才是之前加的随机key 如果key不足会等3秒等待释放
