### ISSUE TITLE
更换api key后，确认改key有效仍然返回401

### ISSUE THREAD

**Issue by cdssd** [Kerwin1202/chatgpt-web#209]
docker-compose 部署的更好api key后，还是提示401，是否有将key写入db导致改错误

**Comment by Kerwin1202** [comment]
如果是最新版本，key 都不从 docker-compose.yml 文件读取了， 在这里设置的，你是这么操作的吗，还是


<img width="1320" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/84094260-893a-44e7-88cd-a6866d0d16ef">

**Comment by Kerwin1202** [comment]
配置文件无效了，，看我截图这里操作即可

**Comment by justincnn** [comment]
> 如果是最新版本，key 都不从 docker-compose.yml 文件读取了， 在这里设置的，你是这么操作的吗，还是
> 
> <img alt="image" width="1320" src="https://user-images.githubusercontent.com/16319833/242303771-84094260-893a-44e7-88cd-a6866d0d16ef.png">

感谢那么人性化的涉及，我今天折腾了一个上午的compose配置，原来问题出在这里，哈哈

**Comment by dqzboy** [comment]
> 如果是最新版本，key 都不从 docker-compose.yml 文件读取了， 在这里设置的，你是这么操作的吗，还是
> 
> <img alt="image" width="1320" src="https://user-images.githubusercontent.com/16319833/242303771-84094260-893a-44e7-88cd-a6866d0d16ef.png">

大佬，Key管理里面。把状态关闭，就直接从页面中消失了吗？我测试关闭就没了，还需要重新添加
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/73de57d6-fcf3-4823-9cba-eea036b07693)

**Comment by Kerwin1202** [comment]
> > 如果是最新版本，key 都不从 docker-compose.yml 文件读取了， 在这里设置的，你是这么操作的吗，还是
> > <img alt="image" width="1320" src="https://user-images.githubusercontent.com/16319833/242303771-84094260-893a-44e7-88cd-a6866d0d16ef.png">
> 
> 大佬，Key管理里面。把状态关闭，就直接从页面中消失了吗？我测试关闭就没了，还需要重新添加 ![image](https://user-images.githubusercontent.com/42825450/242871300-73de57d6-fcf3-4823-9cba-eea036b07693.png)

是的，目前关闭就是删除的意思。。
