### ISSUE TITLE
管理页面是在哪里查看的。我怎么没找到这个页面；

### ISSUE THREAD

**Issue by hieivip** [Kerwin1202/chatgpt-web#210]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/54146330/a7475908-45b3-4ea9-9d21-3983804134fb)

**Comment by dqzboy** [comment]
通过你配置的管理邮箱注册登入就能看到了

**Comment by hieivip** [comment]
> 通过你配置的管理邮箱注册登入就能看到了

感谢感谢~
