### ISSUE TITLE
帮看下没有注册入口，咋回事啊

### ISSUE THREAD

**Issue by zhuangxuan** [Kerwin1202/chatgpt-web#213]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/13015584/3c366d57-5af0-483f-9a73-1d1b5fb5d1b6)

**Comment by jacksnowfuck** [comment]
我昨天新部署的也有这个问题，然后我手动从以前的项目导了数据库就有了

**Comment by Kerwin1202** [comment]
得看下数据库有以及配置，没有看不出

**Comment by zhuangxuan** [comment]
> 得看下数据库有以及配置，没有看不出
找到原因了，没有在docker-compose.yml 中配置auth字段，随便填了一个，可以了，感谢作者的答复
