### ISSUE TITLE
在使用第三方api网关时，无法获取余额。需要有个环境变量，允许关闭 余额的获取

### ISSUE THREAD

**Issue by Explorer1092** [Kerwin1202/chatgpt-web#215]
涉及到的代码

[      console.error('您的账户已被封禁，请登录OpenAI进行查看。')](https://github.com/Kerwin1202/chatgpt-web/blob/92d95b048da2aa5d0fa850af9098c1df84d4af50/service/src/chatgpt/index.ts#L213)

**Comment by Kerwin1202** [comment]
这个接口目前不调用 无效。。  不管怎么样肯定不会开环境变量，，这就麻烦了

**Comment by Kerwin1202** [comment]
最新版关闭了额度获取
