### ISSUE TITLE
[建议]统计中能不能加个人员的使用统计筛选功能

### ISSUE THREAD

**Issue by angelo-she** [Kerwin1202/chatgpt-web#218]

**Comment by mattholy** [comment]
同问，现在好像统计只能看到自己的，管理员能看到全部用户的吗？

**Comment by Kerwin1202** [comment]
<img width="1308" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/c87878f0-6985-4115-9ae4-3ffdf1c59403">
