### ISSUE TITLE
必须用docker部署吗？

### ISSUE THREAD

**Issue by Siri-Li** [Kerwin1202/chatgpt-web#220]
数据库直接建立空数据库，没有内容呢

**Comment by huangwb8** [comment]
@Siri-Li 

用docker挺方便的。 具体可以看我的教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

有什么不懂加群（ https://t.me/benszhub ）提问或评论区留言。

**Comment by dqzboy** [comment]
本地源码方式部署，[一键部署脚本](https://github.com/dqzboy/ChatGPT/tree/main/ChatGPT-Web-Admin)

**Comment by Kerwin1202** [comment]
docker 比较方便 ，https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml 用这个改配置直接可以跑，其他形式  还得搭建数据库 部署数据库之类的

**Comment by Siri-Li** [comment]
有宝塔的教程吗，第一次接触docker

**Comment by Kerwin1202** [comment]
> 有宝塔的教程吗，第一次接触docker

没有，不是 docker 就是一键部署了，上面都有

**Comment by Siri-Li** [comment]
docker跟一键部署都没成功
docker 这个容器目录是空 chatgptweb-database | 已停止 | nginx:alpine | 2023/06/06 13:18:02 |   |  
用一键包 第四步报错
请选择您的服务器网络环境：
1. 国外
2. 国内
2bash: line 313: git: command not found
 git clone 失败，请重试 


能告诉一下数据库如何构建吗？前后端都运行好了，就是没有数据库，把数据库构建好应该就问题了

**Comment by Kerwin1202** [comment]
docker  已停止 可以 docker logs 容器名称 看下报错日志 一般是 error 都会有写的

至于自己构建好，配置环境变量运行即可，有一个 .env.example 文件修改为 .env 然后里面的按照提示修改 再运行

**Comment by Fanlu91** [comment]
> @Siri-Li
> 
> 用docker挺方便的。 具体可以看我的教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》
> 
> 有什么不懂加群（ https://t.me/benszhub ）提问或评论区留言。

博客写的相当不错，点个赞

**Comment by Kerwin1202** [comment]
还可以用这个部署   https://github.com/Kerwin1202/chatgpt-web/issues/266
