### ISSUE TITLE
请问下如何进入docker 直接修改默认的角色设定

### ISSUE THREAD

**Issue by seanshb** [Kerwin1202/chatgpt-web#221]
现在的角色设定是You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.

这个carefully 会导致,回答过于简练.  建议 这个配置项可以在  管理员的基本配置里,或者在配置文件中, 定义, 这样在团队内使用,可以使用这个磨人配置

**Comment by Kerwin1202** [comment]
会考虑搞个 全局的 目前就手动改下

<img width="1210" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/b9484064-8480-460a-ab17-d4c342994fa7">

**Comment by seanshb** [comment]
好的,我现在会提示团队每个人手动更改,    但是每个人都要提醒下,  然后我们也想从整体视角去迭代这个prompt 库,  
尤其在公司内特别有用

**Comment by seanshb** [comment]
所以这段代码在哪里 ,我是不是可以 进container 去 手动改下?

**Comment by Kerwin1202** [comment]
可以 
```
docker exec -it chatgptweb sh
cd public/assets/
# 有好些 index- 开头的 js 自己 
cat index-xxx.js | grep You are ChatGPT
```

**Comment by seanshb** [comment]
不过我发现在 admin的账户做一个修改,后面新加入的人,  都会复用那个修改内容

**Comment by seanshb** [comment]
好咧 ,请问再可以多请教一个问题么,就是默认的系统设置是。Dark模式,是哪个参数:)
真的有劳烦到

**Comment by seanshb** [comment]
> 会考虑搞个 全局的 目前就手动改下
> 
> <img alt="image" width="1210" src="https://user-images.githubusercontent.com/16319833/243313797-b9484064-8480-460a-ab17-d4c342994fa7.png">

非常感谢那么细致的支持!!!!!

**Comment by Kerwin1202** [comment]
<img width="949" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/62777885-9812-43e5-a860-5e6e65c8d77f">
