### ISSUE TITLE
使用access token，提示Access token invalid or no longer valid

### ISSUE THREAD

**Issue by jjustwin** [Kerwin1202/chatgpt-web#225]
在keys管理中，配置了access token，选择这个提问，提示Access token invalid or no longer valid
![image](https://github.com/Kerwin1202/chatgpt-web/assets/8491449/ec7aa28e-6301-4d93-a12e-4578157cd1d2)

**Comment by jjustwin** [comment]
使用docker部署，部署后docker logs -f 没有该错误的日志

**Comment by dqzboy** [comment]
字面意思 换个新token

**Comment by Kerwin1202** [comment]
token 是可能过期的，api 没有。。 点击这个刷新个
<img width="192" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/c51f56d1-65c9-44f5-9b7d-52777418e6a7">

**Comment by jjustwin** [comment]
> 

这个accesstoken 配置给guest就有这个错误提示，配置给admin角色就正常

**Comment by Kerwin1202** [comment]
那你使用的账号权限是啥呢，目前确实 看不太出
