### ISSUE TITLE
手机浏览器访问ui错乱

### ISSUE THREAD

**Issue by superen7527** [Kerwin1202/chatgpt-web#227]
一个月没更新 发现有很多功能更新了一下，结果设置界面出问题了。

很直观对比感觉拥挤了不少，这都不是问题，但是添加key的时候ui完全不对，对话框半截。不知道怎么上传图片。有搭建的可以试试手机ua访问有没有一样的问题？

**Comment by huangwb8** [comment]
@superen7527 

虽然可以通过滑动来选择，但是设置界面基本上可以认为对移动端没怎么优化。

不过，我们一般是办公的时候才用chatGPT。办公的人一般都是用PC的，所以这个问题不存在。我估计这也是移动端优化不太好的主要原因之一。

后续等功能比较稳定了再看移动端优化呗！

**Comment by zhaobudaomingzi** [comment]
@Kerwin1202 还有“设置-用户管理-设置权限”这个页面，希望能优化一下👍

**Comment by zhaobudaomingzi** [comment]
> @Kerwin1202 还有“设置-用户管理-设置权限”这个页面，希望能优化一下👍

![微信图片_20230612090512](https://github.com/Kerwin1202/chatgpt-web/assets/54617500/62537eb7-da84-4ab1-9895-fef33e7f3f55)
