### ISSUE TITLE
请教下我想把网站的默认界面改成DarkMode ,请问修改哪个参数

### ISSUE THREAD

**Issue by seanshb** [Kerwin1202/chatgpt-web#232]
谢谢, 因为我发现,未登陆状态下, Darkmode 要看上去正式很多, 不会显得网站不稳定,哈哈哈

**Comment by liantian-cn** [comment]
src/store/modules/app/helper.ts
修改
```
export function defaultSetting(): AppState {
  return { siderCollapsed: false, theme: 'light', language: 'zh-CN' }
}
```

**Comment by seanshb** [comment]
谢谢 ,但是我似乎没有找到 /app/src # find . -name "*.ts"
./storage/config.ts
./storage/mongo.ts
./storage/model.ts
./utils/textAudit.ts
./utils/mail.ts
./utils/is.ts
./utils/index.ts
./utils/security.ts
./index.ts
./types.ts
./chatgpt/index.ts
./chatgpt/types.ts
./middleware/rootAuth.ts
./middleware/auth.ts
./middleware/limiter.ts

相关文件

**Comment by seanshb** [comment]
搞定,谢谢.
