### ISSUE TITLE
回复字数很少

### ISSUE THREAD

**Issue by wszcl123456** [Kerwin1202/chatgpt-web#234]
每次回复的字数很短，800字的高考作文我说了3次继续才说完，大佬们，这要改哪个参数，我在环境变量.env文件中加了MAX_TOKENS=8192，然后重启服务还是不行

**Comment by qsc19971022** [comment]
你加百度敏感词了嘛

**Comment by wszcl123456** [comment]
> 你加百度敏感词了嘛

没有，百度敏感词我测试好像不行，我在百度后台测试能过

**Comment by Kerwin1202** [comment]
看你 close了所以没回你，看下超时设置 有时候access token 是 比较慢的 超时就断了
<img width="307" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/9160fb55-2f3c-440a-ad8f-1ab288a8612e">

**Comment by wszcl123456** [comment]
> 看你 close了所以没回你，看下超时设置 有时候access token 是 比较慢的 超时就断了
> <img width="307" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/9160fb55-2f3c-440a-ad8f-1ab288a8612e">
> 

是的，我看到别的有这个问题，我就close了，不过设置的是60000，改太大会报错，我用的是API
