### ISSUE TITLE
我用gpt-4模式，就报这个错误提示。这是什么原因啊？

### ISSUE THREAD

**Issue by 123Jason-cn** [Kerwin1202/chatgpt-web#235]
![飞书20230608-192011](https://github.com/Kerwin1202/chatgpt-web/assets/75602210/900a309d-68c9-4ed8-9b4c-3909deb94d51)

**Comment by 123Jason-cn** [comment]
好的。我换个vpn试试

**Comment by 123Jason-cn** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/75602210/2686c347-33e0-4f27-acc8-7954b6bad24c)
这个错误，是不是因为没有开通gpt-4？

**Comment by Fanlu91** [comment]
> ![image](https://user-images.githubusercontent.com/75602210/244568323-2686c347-33e0-4f27-acc8-7954b6bad24c.png) 这个错误，是不是因为没有开通gpt-4？

是的，说明账号还没权限
