### ISSUE TITLE
前端pnpm build报错

### ISSUE THREAD

**Issue by duzhor** [Kerwin1202/chatgpt-web#236]
版本v2.13.4
报错信息：
![Snipaste_2023-06-10_16-39-24](https://github.com/Kerwin1202/chatgpt-web/assets/35054371/64380d1e-0c86-4611-9ef1-e7017576c123)

**Comment by duzhor** [comment]
同样方式编译v2.13.3没有报错。

**Comment by Kerwin1202** [comment]
是不是有什么库之类的没更新啥的， 我试了下正常的

<img width="740" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/0cc4620c-7ad7-436d-9bc1-e1a89033f5ff">
<img width="659" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/6f891519-8afd-4107-af51-b2c876fb4949">
