### ISSUE TITLE
用户登录拉取历史记录不正确问题

### ISSUE THREAD

**Issue by tczj199076** [Kerwin1202/chatgpt-web#239]
A用户登录可能拉取的是B用户的聊天记录，这种情况偶现。

**Comment by Kerwin1202** [comment]
聊天室 左侧是对的吗，还是存聊天上下文不对。 

之前有一个人说这个问题可能套了cdn，你把接口数据缓存了

**Comment by tczj199076** [comment]
> 聊天室 左侧是对的吗，还是存聊天上下文不对。
> 
> 之前有一个人说这个问题可能套了cdn，你把接口数据缓存了

聊天室和聊天记录都不对，是缓存问题吗！的确用了cdn但是是七牛的图片上传

**Comment by LanQian528** [comment]
> > 聊天室 左侧是对的吗，还是存聊天上下文不对。
> > 之前有一个人说这个问题可能套了cdn，你把接口数据缓存了
> 
> 聊天室和聊天记录都不对，是缓存问题吗！的确用了cdn但是是七牛的图片上传

是cdn问题，把接口路径的缓存关了就行

**Comment by tczj199076** [comment]
> > > 聊天室 左侧是对的吗，还是存聊天上下文不对。
> > > 之前有一个人说这个问题可能套了cdn，你把接口数据缓存了
> > 
> > 
> > 聊天室和聊天记录都不对，是缓存问题吗！的确用了cdn但是是七牛的图片上传
> 
> 是cdn问题，把接口路径的缓存关了就行

接口路径缓存？啥意思呀

**Comment by Kerwin1202** [comment]
@tczj199076 没用过 七牛  可以，应该有类似的设置 就是关闭动态接口 选项，活著指定接口前缀路径关闭缓存 比如 /api 开头的都关闭

**Comment by xushuojie** [comment]
请问解决问题了吗，我也遇到相同的问题

**Comment by Kerwin1202** [comment]
> 请问解决问题了吗，我也遇到相同的问题

没用cdn？
