### ISSUE TITLE
私有服务器部署，accessToken方式，如果分享给朋友使用，多大流量会导致封号？

### ISSUE THREAD

**Issue by appotry** [Kerwin1202/chatgpt-web#240]
账户赠送的美元已经过期了，现在采用accessToken的方式访问。

私有vps, 地点USA。现在这样使用，给朋友注册账户会导致封号么？ 或者多大流量会导致封号

有类似用法的用户没？

**Comment by huangwb8** [comment]
@appotry 

Access Token应该是有限流的，即单位时间超过一定的问题速就会被限制。 

现在有人售卖第3方API的，120美元帐户的Openai API应该是几块钱就买得到。 自己找一下。 

以上。

**Comment by appotry** [comment]
@huangwb8 现在短信平台一个sms就要几块钱了，账号还这么便宜？

目前服务器IP很干净，只用过一个api key，如果使用批量注册的key，可能连累被openai封ip，这个风险不值得

**Comment by huangwb8** [comment]
@appotry 

我是自己注册的。 如果你对价格不敏感且安全性要求较高，可关注我的方案《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。 我用的是nobepay。

**Comment by cdssd** [comment]
给个购买链接@huangwb8

**Comment by huangwb8** [comment]
@cdssd 

你可以加Telegram群 **[OpenAI/ChatGPT群](https://t.me/+L0g2D-hecQM4ODVl)**  。 这个群的人专门讨论ChatGPT帐号问题，应该有人可以帮你。 不过，陌生人交易的安全是没有办法保证的，自己小心。我自己也没有在这个群里索求服务。 祝好 (ฅ´ω`ฅ)

**Comment by appotry** [comment]
@cdssd 自己注册的靠谱一些，同一个ip批量注册的账号，封号概率极大，会一次砍掉所有关联账号的


这个是以前写的注册教程，[中国区注册ChatGPT并使用全流程图解教程](https://blog.17lai.site/posts/1336c869/)

**Comment by JeazW** [comment]
access_token回答质量高一些，access_token可以多个负载均衡吗现在

**Comment by 1VeniVediVeci1** [comment]
> > 给个购买链接@huangwb8
> 
> 15块钱都可以买一个绑卡的120美金的账号，比用access_token方便

15块可太贵了，一般零售价8元，批发5元，低到离谱

**Comment by cdssd** [comment]
@1VeniVediVeci1 给个链接，别又是电报群啊

**Comment by assassinliujie** [comment]
> > 给个购买链接@huangwb8
> 
> 15块钱都可以买一个绑卡的120美金的账号，比用access_token方便

赠金API也有限制，最好还是老老实实付费
