### ISSUE TITLE
如何用dockerfile只打包后端镜像，镜像太大拖到服务器上太慢了

### ISSUE THREAD

**Issue by ChuckZengxf** [Kerwin1202/chatgpt-web#241]

**Comment by ChuckZengxf** [comment]
我试了好像不行，docker的用法不是很懂，希望大神能帮忙解决下

**Comment by Kerwin1202** [comment]
既然不太懂，我觉得可以简单点呀，就是直接用现有的docker 运行起来，然后只用后端接口就行了。
就是这个项目包含前后端，你只要后端就只用后端就好了，前端不用放在哪里也没事的意思。。。  
 按照这个 修改文件然后 运行  需要安装 docker 以及 docker-compose
```
docker-compose up -d
```
https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml

**Comment by ChuckZengxf** [comment]
现在用的就是，只用到镜像里的后端。现在打个镜像要几百兆，在上传到境外服务器每次传都要10-20分钟，这个时间太折磨了。有什么更好的办法吗？

**Comment by Kerwin1202** [comment]
为啥要上传呀，直接你境外服务器直接 docker pull 就好了呀 国外服务器pull 应该很快的，你是自己改了什么打包的然后传这样？ 那也可以自己的github 账号 action 打包自动push倒 hub.docker.com  再去 pull 而不用自己人工打包再搞上去

**Comment by liantian-cn** [comment]
好方法就是你用buildah 打包容器,podman save -o导出容器，用gzip压缩
buildah 和docker build的区别是buildah所有操作只算一层。打包后是280MB
gzip压缩完，我这里只有48mb
