### ISSUE TITLE
源码是否未更新，下载源码运行不了，但是docker可以使用

### ISSUE THREAD

**Issue by fengjuntang** [Kerwin1202/chatgpt-web#246]

**Comment by Kerwin1202** [comment]
docker 就是 源码 github action 自动打包的，估计你操作有问题？

**Comment by snareli** [comment]
我也是，开发时只能进500页面，部署在服务器就没问题

**Comment by Kerwin1202** [comment]
> 我也是，开发时只能进500页面，部署在服务器就没问题

500 看是什么报错啊，啥也没，步骤也没，看不出

**Comment by fengjuntang** [comment]
> 我也是，开发时只能进500页面，部署在服务器就没问题

我和你一样的问题，源码下载下来，直接dockerfile构建一个镜像，使用docker-compose.yml文件运行就进入500那个界面，如果我使用作者的镜像，使用一样的docker-compose.yml文件运行，就没有问题

**Comment by fengjuntang** [comment]
logs什么错误都没有，
> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js
Server is running on port 3002
服务器不会崩，只是访问的时候就进入http://localhost:3002/#/500界面
要不作者辛苦下，把最新的几个模型加进去，哈哈哈

**Comment by liantian-cn** [comment]
我build没问题..
有问题能贴下具体命令嘛

**Comment by Kerwin1202** [comment]
> logs什么错误都没有，
> 
> > chatgpt-web-service@1.0.0 prod /app
> > esno ./build/index.js
> > Server is running on port 3002
> > 服务器不会崩，只是访问的时候就进入[http://localhost:3002/#/500界面](http://localhost:3002/#/500%E7%95%8C%E9%9D%A2)
> > 要不作者辛苦下，把最新的几个模型加进去，哈哈哈

一般 500 错误 就是后端启动失败了，那你看下会不会端口占用了，默认会用 80 或者 3002 端口的，如果占用启动不了会失败。。。 或者步骤放一下，否则啥也没有看不出哦

**Comment by fengjuntang** [comment]
真的是端口问题，今天换了3003端口就成功打开了

> > logs什么错误都没有，
> > > chatgpt-web-service@1.0.0 prod /app
> > > esno ./build/index.js
> > > Server is running on port 3002
> > > 服务器不会崩，只是访问的时候就进入[http://localhost:3002/#/500界面](http://localhost:3002/#/500%E7%95%8C%E9%9D%A2)
> > > 要不作者辛苦下，把最新的几个模型加进去，哈哈哈
> 
> 一般 500 错误 就是后端启动失败了，那你看下会不会端口占用了，默认会用 80 或者 3002 端口的，如果占用启动不了会失败。。。 或者步骤放一下，否则啥也没有看不出哦

真的是端口问题，换了3003端口就好了

**Comment by fengjuntang** [comment]
但是为什么在docker logs中也没有报错信息呢

**Comment by afire-studio** [comment]
本地500大概率是MongoDB原因，本地需要安装MongoDB，配置好账号密码，代码里面数据库取URL的第一个反斜杆后面的，默认用的chatgpt，然后再配置server端环境变量的MONGODB_URL，比如 MONGODB_URL=mongodb://chatgpt:123456@127.0.0.1:27017/chatgpt，前端session接口会返回相关错误

**Comment by Kerwin1202** [comment]
> 但是为什么在docker logs中也没有报错信息呢

log的日志是 docker本身运行成功，里面程序运行报错会出现，端口占用是 docker本身运行失败了。正常来说，你`docker-compose up` 不加 -d 可以看得出
