### ISSUE TITLE
大佬，title为啥不显示变量值而是变量名

### ISSUE THREAD

**Issue by JeazW** [Kerwin1202/chatgpt-web#250]
360安全浏览器，之前都是手动去替换，这次我决定咨询一下

**Comment by hostemail** [comment]
问题+1，采用docker compose部署

**Comment by Kerwin1202** [comment]
> 问题+1，采用docker compose部署

页面的title 主要是首次 docker run的时候才会替换 并且只会替换 docker-compose.yml 文件里的 如果后续在前端页面设置里修改了，目前不会同步修改 前端页面

如果首次运行都不变，那需要看看  docker日志  主要是用这个去替换的

https://github.com/Kerwin1202/chatgpt-web/blob/main/replace-title.sh
