### ISSUE TITLE
官方更新了gpt-3.5-turbo

### ISSUE THREAD

**Issue by a137235** [Kerwin1202/chatgpt-web#254]
gpt-3.5-turbo-16k

**Comment by HaanJam** [comment]
有更新的呀
![image](https://github.com/Kerwin1202/chatgpt-web/assets/35722236/93579636-7b19-4969-8c39-e50fecda998b)

**Comment by zhaobudaomingzi** [comment]
> 有更新的呀 ![image](https://user-images.githubusercontent.com/35722236/246317808-93579636-7b19-4969-8c39-e50fecda998b.png)

为啥我这里没有啊
