### ISSUE TITLE
这么多用户权限，都分别有什么用

### ISSUE THREAD

**Issue by XingHehy** [Kerwin1202/chatgpt-web#255]
这么多用户权限，都分别有什么用
admin，user我知道，其他权限是干什么的
<img width="560" alt="" src="https://github.com/Kerwin1202/chatgpt-web/assets/62918118/d04c0eac-4355-44d6-9f3f-c93d2940f3e6">

**Comment by Kerwin1202** [comment]
除了admin 其他就是认为是 权限1 权限2 权限3的意思

**Comment by XingHehy** [comment]
ok，明白了
