### ISSUE TITLE
请教怎么在railway上部署，有没有详细教程，特别是数据库的部分

### ISSUE THREAD

**Issue by wwlmm** [Kerwin1202/chatgpt-web#266]
怎么在railway上部署，有没有详细教程，特别是数据库的部分，谢谢，望大佬们赐教。

**Comment by Kerwin1202** [comment]
花了点时间研究了下，
## mongodb

首先 在 https://railway.app/new  新建一个 mongodb， 复制变量 后续使用
<img width="1069" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/7001625f-fe89-43b4-97fe-1684802842de">
<img width="1450" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/8ab50517-7407-4f8d-95b7-1a9d3753b59b">

## chatgpt web
https://railway.app/new  自己github 授权 选择 fork 的本项目 
<img width="737" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/3ad42faf-af9c-4946-8326-9f188fe39f18">

设置环境变量，极少数的，其他运行之后设置即可
<img width="1631" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/671dfebe-6053-4cb2-8e35-f839095ce323">

设置域名
<img width="1024" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/ab6bd4dd-4bce-4a7d-8a18-adcde94ef141">

**Comment by GitHubQkun** [comment]
你好，请问按照上述图片railway部署后没有怎么登录界面呀，也没有管理员界面，会有VITE相关的变量，怎么填呢，谢谢
![问题](https://github.com/chatgpt-web-dev/chatgpt-web/assets/65835644/5d92a744-7aad-4e57-9e1a-3b2f49a43427)
