### ISSUE TITLE
关于注册邮箱配置的设置

### ISSUE THREAD

**Issue by DoNotSayYes** [Kerwin1202/chatgpt-web#269]
大佬，有几个问题想请教一下，是关于注册邮箱设置的，望解答，十分感谢。@Kerwin1202
1. 当中字段` SITE_DOMAIN: http://127.0.0.1:1002`这个字段是默认填写就好了，是根据代码的那个地址获得的。
2. 开启注册后，`SMTP_HOST`如果是用公司的邮箱，由于权限问题不能使用公司的`SMTP`服务时，有办法解决注册问题么，例如说我限制只能是`*qq.com`的邮箱注册，但是验证邮箱配置`SMTP`服务使用的是163邮箱的，这样有问题不，还是说注册邮箱必须要和验证邮箱配置是同一个邮件服务器，`ROOT_USER: xxx@qq.com` 超级管理员是否强制要求是在同一个邮件服务器上的邮箱？

```
      # 开启注册之后 发送验证邮箱配置
      SMTP_HOST: smtp.exmail.qq.com
      SMTP_PORT: 465
      SMTP_TSL: true
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
```

**Comment by huangwb8** [comment]
@DoNotSayYes 

请仔细地看教程《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》的设置。

超级管理员的邮箱有一个专门的变量`ROOT_USER`设置，和SMTP并无直接关系。

`SITE_DOMAIN`指的是实际使用chatgpt-web时它的域名。并不能用默认的地址。

**Comment by Kerwin1202** [comment]
@DoNotSayYes 
1. 默认的 `http://127.0.0.1:1002` 是案例 需要修改的，否则只能你本地使用，比如你解析了域名可以换成域名 如果有端口就域名+端口
2.  注册的限制，是对用的人限制， 你的 smtp 是可以任意的 2者没有必然关系

**Comment by DoNotSayYes** [comment]
> @DoNotSayYes
> 
> 请仔细地看教程《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》的设置。
> 
> 超级管理员的邮箱有一个专门的变量`ROOT_USER`设置，和SMTP并无直接关系。
> 
> `SITE_DOMAIN`指的是实际使用chatgpt-web时它的域名。并不能用默认的地址。

大佬，照着你的步骤来启用的服务，页面都无法访问，数据库也有问题，上面这些步骤是有什么需要更新的吗？@huangwb8

**Comment by Kerwin1202** [comment]
@DoNotSayYes 没有具体的步骤等信息不清楚
