### ISSUE TITLE
首页用户描述信息（userInfo.description）无显示

### ISSUE THREAD

**Issue by hostemail** [Kerwin1202/chatgpt-web#273]
与原作者代码对比了下，发现common/UserAvatar/index.vue中，少了用户描述信息渲染显示

![image](https://github.com/Kerwin1202/chatgpt-web/assets/45652715/8bc5d307-e272-4807-9259-d0561cc2ca6d)

![image](https://github.com/Kerwin1202/chatgpt-web/assets/45652715/0c1ccfc8-8007-47f1-b294-27da8a51bbaf)

**Comment by Kerwin1202** [comment]
目前是这样的，未显示
