### ISSUE TITLE
docker更新了，才发现没有更新relearse，哈哈

### ISSUE THREAD

**Issue by justincnn** [Kerwin1202/chatgpt-web#274]
刚才闲着无事，pull了下image，发现已经支持gpt3.5-16k了，

感谢kerwin1202的激情和时间

![](https://cdn.jsdelivr.net/gh/justincnn/pictures/img/%E6%88%AA%E5%B1%8F2023-06-24%2018.50.03.png)

**Comment by Kerwin1202** [comment]
已加
