### ISSUE TITLE
对Docker compose 部署细节感到疑惑？？？

### ISSUE THREAD

**Issue by piwawa** [Kerwin1202/chatgpt-web#276]
这个打包好的前端文件是什么？不是用docker compose已经把前后端都拉起来了吗？

这个nginx.conf需要覆盖我系统中`/etc/nginx/nginx.conf`的配置吗？
![image](https://github.com/Kerwin1202/chatgpt-web/assets/46926496/21609a9e-369d-49fc-9118-88beea82a916)

```
# mongodb 的连接字符串
MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017'
```

这里的链接是随便填吗？还是和原文一致？

最好附图详细介绍一下部署流程，谢谢！

**Comment by Kerwin1202** [comment]
文案晚些时候看情况改下 fork 上一个项目遗留，实际上和这个没任何关系  只看这个就行，如果是自己build的 docker 一系列可能会用到
<img width="617" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/210d1b4f-6c71-44fd-add7-6ed6e254198d">

**Comment by piwawa** [comment]
> 文案晚些时候看情况改下 fork 上一个项目遗留，实际上和这个没任何关系 只看这个就行，如果是自己build的 docker 一系列可能会用到 <img alt="image" width="617" src="https://user-images.githubusercontent.com/16319833/248485474-210d1b4f-6c71-44fd-add7-6ed6e254198d.png">


那请问这个配置我要修改吗？没用过数据库

![image](https://github.com/Kerwin1202/chatgpt-web/assets/46926496/dcc7bc53-d29b-4d35-848e-abda16cc8d4d)

**Comment by Kerwin1202** [comment]
chatgpt 是账号 xxxx 是密码 ，对应下面有的 mongodb 对应设置就可以

<img width="598" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/eb9fbd78-b1fd-4ede-9fd5-c2503e252c50">

**Comment by Kerwin1202** [comment]
> 一样的docker-compose文件，在本地debian测试能跑起来，但在centos云服务器就报错了 <img alt="image" width="1002" src="https://user-images.githubusercontent.com/48551225/276259062-b06c254c-b93a-423a-b17f-02ce32e5ed03.png">

可能不同的操作系统 读取的 字段 不一样， 看截图报错的意思是  看 docker-compose.yml 文件 里的 true 相关字眼 有没有 '' 单引号 没有的加下 有的就去掉 再试试
