### ISSUE TITLE
没有用docke部署，用本地部署启动，会报错Cannot read properties of null (reading 'config')

### ISSUE THREAD

**Issue by KrystalandBarry** [Kerwin1202/chatgpt-web#278]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/64ea5596-3210-4f20-a132-d9e74cbaeaef)

**Comment by Kerwin1202** [comment]
你是不是没开启注册的，也没开启登录的情况下

**Comment by KrystalandBarry** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/89d7ac12-b089-4796-b346-01617058566a)
开启了的

**Comment by KrystalandBarry** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/06265ec2-8bc3-4995-8795-b797b3eba37b)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/4e73b06e-1d98-4fa7-9364-1da7cfb9fb74)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/74537da0-9193-4914-98e0-51a3d14b4152)
现在本地我可以正常数据库链接mongodb，但是启动后，页面报找不到对应的数据库

**Comment by Kerwin1202** [comment]
这个设置下，默认配置之后不会立马有数据库，需要进行注册啊 保存配置之类的操作才会有，
<img width="258" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/daef4eba-1371-4801-bd3c-d2bb537fee24">

**Comment by KrystalandBarry** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/3c66cce5-268d-4528-a195-7dea491b37a4)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/5c8ad448-d999-48c4-859a-6091352a7df8)
配置了，但是启动后，还是直接请求了session，没有登录注册的操作界面出来

**Comment by Kerwin1202** [comment]
这个 500 是直接跳转的 还是你上次停留的  删掉后面的 试试
<img width="184" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/ae1d68d7-d36d-402f-b5f6-947aa93989be">

**Comment by KrystalandBarry** [comment]
直接跳转的，我请求的是http://10.0.33.25:1002/

**Comment by Kerwin1202** [comment]
要看下这里 以及 console 里有没有报错

<img width="1172" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/8da732bf-046d-450a-8fa9-6196d354190a">

**Comment by KrystalandBarry** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/832428a8-f492-4b3e-b989-39b2337b54e8)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/dba9fe15-67bc-476b-ba52-3e1277c267aa)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33093118/6bbb5435-eac2-46e1-b12f-6e994f85f780)
辛苦看一下

**Comment by Kerwin1202** [comment]
我不清楚你的mongodb是怎么部署的，但是这个应该是 localhost 或者其他ip啥的
<img width="867" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/4499fd26-2dd4-4d97-8455-511129485452">

**Comment by KrystalandBarry** [comment]
我的问题，已解决，谢谢，mongodb本地的问题
