### ISSUE TITLE
使用Token时的模型选择和对话删除

### ISSUE THREAD

**Issue by krxiaoyu** [Kerwin1202/chatgpt-web#284]
1. 关于使用token时，可以选择哪些模型？
'gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-16k', 'gpt-4', 'gpt-4-0314', 'gpt-4-32k', 'gpt-4-32k-0314', 'gpt-4-0613', 'gpt-4-32k-0613', 'ext-davinci-002-render-sha-mobile', 'text-embedding-ada-002', 'gpt-4-mobile', 'gpt-4-browsing'

2. 使用token时，在chatgpt-web上新建对话后，在openai网页上也可以看到相关对话，在chatgpt-web上删除对话后，openai网页上并不会被删除，如果想删除只能去openai网页上删除吗？

**Comment by krxiaoyu** [comment]
意思是，使用[Access Token]时全部模型可以都可以使用，那么使用API Key时呢？ 部分不能使用是吗？

**Comment by Kerwin1202** [comment]
有的是只有 token 可以 比如 gpt-4-browsing 这种只有官网才有的 ，至于是否所有都token可以，得试试

**Comment by krxiaoyu** [comment]
好的，谢谢，那我都试试吧
