### ISSUE TITLE
可以成功发送邮件但是点验证进不去，提示403

### ISSUE THREAD

**Issue by yueshu12735** [Kerwin1202/chatgpt-web#292]
[
![Screenshot_2023-07-02-23-26-21-654_com netease mo](https://github.com/Kerwin1202/chatgpt-web/assets/81411250/aa4430df-0d9d-4ad1-9b3d-fd20b1c2d87f)
![Screenshot_2023-07-02-23-26-25-261_com netease mo](https://github.com/Kerwin1202/chatgpt-web/assets/81411250/4aa66b60-8bdf-4e3c-90db-58ebc5395a7d)
](url)

这是我的配置文件，我不知道哪里出了问题
version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: 
      # 网站名称
      SITE_TITLE: ChatGpt Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:填了@database:27017'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: xxx
      # 开启注册之后 超级管理邮箱
      ROOT_USER: 填了@gmail.com
      # 网站是否开启注册 必须开启, 否则管理员都没法注册, 可后续关闭
      REGISTER_ENABLED: true
      # 更多配置, 在运行后, 注册管理员, 在管理员页面中设置
    links:
      - database

  database:
    image: mongo
    container_name: chatgptweb-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: 填了
      MONGO_INITDB_DATABASE: chatgpt

volumes:
  mongodb: {}

**Comment by huangwb8** [comment]
@yueshu12735 

你缺少一个叫`SITE_DOMAIN`的参数，类似这样：

```yaml
# 前面一定要有https://或http://，且末尾不含/。注册的时候发送验证邮箱使用。
 SITE_DOMAIN: https://chatgpt.hwb0307.com # 按需修改
```

更多细节可参考我的博客教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》

祝好！

**Comment by yueshu12735** [comment]
> @yueshu12735
> 
> 你需要一个叫`SITE_DOMAIN`的参数，类似这样：
> 
> ```yaml
> # 前面一定要有https://或http://，且末尾不含/。注册的时候发送验证邮箱使用。
>  SITE_DOMAIN: https://chatgpt.hwb0307.com # 按需修改
> ```
> 
> 更多细节可参考我的博客教程：《[Docker系列基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》
> 
> 祝好！

谢谢大佬，可以了
