### ISSUE TITLE
恳求增加read pdf的功能

### ISSUE THREAD

**Issue by VectorZhao** [Kerwin1202/chatgpt-web#294]
[https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E7%90%86%E8%A7%A3PDF%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9.py](https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E7%90%86%E8%A7%A3PDF%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9.py)

聊天记录添加`上传pdf`的按钮，通过调用函数来读取pdf内容喂给chatgpt

**Comment by magicdmer** [comment]
这个已经提过了：
https://github.com/Kerwin1202/chatgpt-web/issues/256
