### ISSUE TITLE
docker-compose部署, 如何自定义 网站标题/验证邮件正文 等内容.

### ISSUE THREAD

**Issue by yangxiao960602** [Kerwin1202/chatgpt-web#295]
我用docker-compose部署了应用, 在容器内修改了 /app/public/index.html 中<title>标签内的字符串, 但是刷新页面不起作用. 重启之后index.html中的修改内容也自动还原了. 

此外, 还有 验证邮件正文, 以及新建聊天室顶部的 "Aha~"(如下图. 想把这个提示词当做网站公告来使用).

前端小白, 还望大佬赐教.

![image](https://github.com/Kerwin1202/chatgpt-web/assets/12980249/10ce019e-8ae4-44ac-ad0f-b3b0a9d7cda0)

**Comment by fengjuntang** [comment]
一是可以下载源码，查找Aha的位置，修改，然后打包成镜像，在服务器拉取镜像重新docker，二可以进入你docker容器内，找到Aha所在的文件，然后vim修改文件中Aha为你想要的文本。上面两个方法都可以问chatgpt具体操作方法，提供一个免费的chatgpt网站，funning.tjfai.club，操作不难，去问下步骤就行

**Comment by yangxiao960602** [comment]
> 刚提问就发现能够解决了,瞬间关闭了issue. 依然感谢大佬的 极速&耐心解答.
- "Aha~"找到了, 在 /app/public/assets/index-33307fe7.js 中, 修改后重启容器不会复原
- 网站<title>修改后还是会复原, 可能真得从源码build才行. 
- 已基本解决了我当前的需求, 感谢大佬指路.



> 一是可以下载源码，查找Aha的位置，修改，然后打包成镜像，在服务器拉取镜像重新docker，二可以进入你docker容器内，找到Aha所在的文件，然后vim修改文件中Aha为你想要的文本。上面两个方法都可以问chatgpt具体操作方法，提供一个免费的chatgpt网站，funning.tjfai.club，操作不难，去问下步骤就行

**Comment by yangxiao960602** [comment]
> > > 刚提问就发现能够解决了,瞬间关闭了issue. 依然感谢大佬的 极速&耐心解答.
> > 
> > 
> > 
> > * "Aha~"找到了, 在 /app/public/assets/index-33307fe7.js 中, 修改后重启容器不会复原
> > * 网站<title>修改后还是会复原, 可能真得从源码build才行.
> > * 已基本解决了我当前的需求, 感谢大佬指路.
> > 
> > > 一是可以下载源码，查找Aha的位置，修改，然后打包成镜像，在服务器拉取镜像重新docker，二可以进入你docker容器内，找到Aha所在的文件，然后vim修改文件中Aha为你想要的文本。上面两个方法都可以问chatgpt具体操作方法，提供一个免费的chatgpt网站，funning.tjfai.club，操作不难，去问下步骤就行
> 
> 我修改`/app/public/assets/`里面的`.js`配置也不起作用，你怎么让修改生效的？


在容器镜像内的终端目录 (/app/public/assets/) 下, 全目录搜索字符串 “Aha~”, 然后找到对应文件，修改该字符串，重启容器就可以了。我这儿是这么操作的。
