### ISSUE TITLE
能否显示每个对话使用的模型？

### ISSUE THREAD

**Issue by pepperdog999** [Kerwin1202/chatgpt-web#300]
因为本项目中可以任意切换可用模型，是否可在每条记录上显示当时使用的模型？

**Comment by jamebal** [comment]
+1

**Comment by Kerwin1202** [comment]
每条记录的意义是否不大？ 我觉得可以给每个聊天室 提示下上次用的是什么，然后下次打开切换过来默认是上次的

**Comment by jamebal** [comment]
> 每条记录的意义是否不大？ 我觉得可以给每个聊天室 提示下上次用的是什么，然后下次打开切换过来默认是上次的

这个非常好
