### ISSUE TITLE
show user role beside their username

### ISSUE THREAD

**Issue by Urmi10799** [Kerwin1202/chatgpt-web#302]
Is it possible to show the user role beside their username? it would be helpful for users to understand at what role they are in. or can you guide me a little how to do that? thanks in advanced 😊

**Comment by Kerwin1202** [comment]
Maybe like this
<img width="246" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/55218d3e-37d5-4f09-84cb-a4491fe28966">
