### ISSUE TITLE
GPT返回的消息每次都携带消耗token信息

### ISSUE THREAD

**Issue by miracle1103** [Kerwin1202/chatgpt-web#304]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/37585258/c634530e-e616-435d-8860-0ff329f6b5e6)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/37585258/4ee839cf-dbf0-4f88-8f9f-3148cdeb63c9)
如图红框圈出来的消耗token统计信息,能否设置不展示token消耗信息?

**Comment by Kerwin1202** [comment]
这个不改吧，，隐藏的意义是？

**Comment by miracle1103** [comment]
嗯嗯,就是有点强迫症😄,设计目的如果是让个人token消耗可以一目了然,那我完全可接受哈!

**Comment by Kerwin1202** [comment]
就是方便看到消耗，然后在 左下角设置里可以看到每天的消耗

**Comment by miracle1103** [comment]
嗯嗯!soga!👍 @Kerwin1202
