### ISSUE TITLE
怎么删除对话之后连同数据库的数据和服务器本地的文件一起删除呢

### ISSUE THREAD

**Issue by tinnnnnnny** [Kerwin1202/chatgpt-web#328]

**Comment by tinnnnnnny** [comment]
看了下代码 删除都是改了状态 但是没有删除本地的数据

**Comment by Kerwin1202** [comment]
目前不支持，得第三方工具连接上去删

**Comment by tinnnnnnny** [comment]
> 目前不支持，得第三方工具连接上去删

请问用什么第三方工具呢

**Comment by Kerwin1202** [comment]
> > 目前不支持，得第三方工具连接上去删
> 
> 请问用什么第三方工具呢

比如  studio 3T datagrip 等数据库管理工具
