### ISSUE TITLE
同一个GPT4的Key，为啥这个回答是GPT3；Next-WEB回答是正确的

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#332]
![Snipaste_2023-08-22_13-52-16](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/d222ee7c-9038-433d-a973-3080a6080bec)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/676965ed-a1b0-438c-903d-5475ecc685dd)

**Comment by Kerwin1202** [comment]
> 还有个问题就是 之前用的accesstoken，然后加了个api key之后，之前使用的accesstoken的会话就都提示没有可用的配置了 ![image](https://user-images.githubusercontent.com/42825450/262277708-69d179dd-36e3-461d-90f6-e0e3133e70dd.png)

加了个api key  之前的access token还在吗， 使用的版本是最新的吗

**Comment by dqzboy** [comment]
> > 还有个问题就是 之前用的accesstoken，然后加了个api key之后，之前使用的accesstoken的会话就都提示没有可用的配置了 ![image](https://user-images.githubusercontent.com/42825450/262277708-69d179dd-36e3-461d-90f6-e0e3133e70dd.png)
> 
> 加了个api key 之前的access token还在吗， 使用的版本是最新的吗

还在的，版本是最新的

**Comment by Kerwin1202** [comment]
如果重启过 还是上面这个提示，只能想到 2个可能， 一个是 access token 和 room 根本不对应 

那得对比下数据库里的 room 里的字段 和你 还在的 access token 用 jwt 解密下对比下看看是否是同一个

另一个就是权限不对  再看看 对应的 key 以及 user 权限，和使用者是否有这个key 的权限

**Comment by dqzboy** [comment]
好的，大佬最新有啥新功能没 哈哈

**Comment by Kerwin1202** [comment]
暂时没哈，最近都没看这块，issue 都间隔看来着 [捂脸]
