### ISSUE TITLE
部署公司内部使用，如何配置只注册管理员账号，其他人随便使用？

### ISSUE THREAD

**Issue by walkchen9** [Kerwin1202/chatgpt-web#334]
部署公司内部使用，如何配置只注册管理员账号，其他人随便使用？

**Comment by walkchen9** [comment]
docker-compos.yml上如何配置相关参数？

**Comment by Kerwin1202** [comment]
不行，其实无所谓吧，你不管内部不内部 注册下账号 接受个验证码 好像也没啥呀， 你一般人不去注册登录 聊天记录没法保存啊，换个浏览器就没了

**Comment by huangwb8** [comment]
@walkchen9  

建议人手注册一个帐户，很容易的

具体安装方案可以看我的教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》，有不懂再沟通。

祝好！

**Comment by huangwb8** [comment]
> > @walkchen9
> > 建议人手注册一个帐户，很容易的
> > 具体安装方案可以看我的教程： 《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》，有不懂再沟通。
> > 祝好！
> 
> ？人家问的是这个吗

不好意思，我之前的表述不太清楚。

我的原意是，既然他已经准备建这个项目，他的同事可以在他建好的项目里自己注册一个帐号使用；或者他可以直接以管理员的身份添加帐号，这并不是什么难事。

正如 @Kerwin1202 说的那样，每个人有自己的帐号可以让聊天记录互相隔离并远程保存——这是本项目的优势之一。不然，直接安装源项目[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)即可，它相对简单，并不要求使用者注册帐户。
