### ISSUE TITLE
部署完毕后，管理员账号注册提示：账户状态异常 | Account status abnormal.

### ISSUE THREAD

**Issue by wangyan0821** [Kerwin1202/chatgpt-web#336]
使用docker-compose.yaml中配置的ROOT_USER用户作为管理员用户首次注册（登录/注册页面中选择的重置密码）。 
但是一直提示账户状态异常 | Account status abnormal.
不知道是不是哪里配置不对

**Comment by wangyan0821** [comment]
使用过的版本包括： 
1. kerwin1202/chatgpt-web:v2.13.4 、mongo:4.0
2. 1kerwin1202/chatgpt-web:latest 、mongo:4.0
3. kerwin1202/chatgpt-web:latest 、mongo:5.0.3

**Comment by Kerwin1202** [comment]
root 直接注册  然后 直接登录即可，重置密码，都没有这个账号肯定无法重置的

**Comment by wangyan0821** [comment]
请问直接注册是什么意思？  登录/注册页面只有登录和重置密码两个界面， 注册是要如何注册，直接登录的话root的密码又是什么？

**Comment by wangyan0821** [comment]
知道问题原因了，已解决。

      REGISTER_ENABLED: 'true'
此处的true必须加个单引号
