### ISSUE TITLE
自定义对话模型

### ISSUE THREAD

**Issue by buctllx** [Kerwin1202/chatgpt-web#340]
目前设置”对话模型“只能下拉选择，可否支持用户手动输入模型名称，这样适用性就大大增强

**Comment by fl0w1nd** [comment]
确实，CHATGPT-NEXT-WEB支持自定义对话模型，但是那是本地使用的，这个要自定义对话模型的话需要管理页面增加自定义模型选项

**Comment by Kerwin1202** [comment]
<img width="1350" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/b6f47c90-9418-4df1-bc82-01cb06fbf3d1">
