### ISSUE TITLE
内存占用200多MB, 能否优化一下?

### ISSUE THREAD

**Issue by padixa** [Kerwin1202/chatgpt-web#345]
原作者[Chanzhaoyu](https://github.com/Chanzhaoyu)/[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)现在貌似在弄收费版, 基本很少更新了, 你成了咱希望了啊.

Docker中运行这个容器直接占用200多兆(还不包含Mongodb), 能否优化一下, 只是个WEB页面二次转发显示请求而已, 用不着占这么多吧. 再说了不是已经有Mongodb吗? 多余的东西能否直接存数据库.

**Comment by Timoshao** [comment]
全村的希望。
大佬加油

**Comment by padixa** [comment]
人呢?  不会这个项目也歇菜了吧.

**Comment by padixa** [comment]
@Kerwin1202 , 重启一下, 发送几个gpt聊天记录. 再查下.

**Comment by Kerwin1202** [comment]
确实 170 左右 但是我对优化这块不太懂

**Comment by padixa** [comment]
@Kerwin1202 不会是你没把缓存放在数据库直接放在内存中导致的吧? 以前的逻辑没数据库, 但现在咱可以放数据库嘛. 优化下呗. 定位到了当前Tab再拿出来, 其他时候放数据库. 再看下其他地方到底哪里耗的多.

**Comment by zhujunsan** [comment]
> @Kerwin1202 不会是你没把缓存放在数据库直接放在内存中导致的吧? 以前的逻辑没数据库, 但现在咱可以放数据库嘛. 优化下呗. 定位到了当前Tab再拿出来, 其他时候放数据库. 再看下其他地方到底哪里耗的多.

你说的这个情况应该是不存在的， #113 中就已经关闭默认的 LRU 缓存了。我怀疑是因为用 esno 启动脚本，直接运行ts，要先编译后运行，所以整个编译器都加载了，所以启动速度也慢内存开销也大。应该可以在build的时候编译完ts到js，我不会 :no_mouth: ，我去学一学看看

**Comment by zhujunsan** [comment]
好吧，build的时候确实是编译过一下了，仍然还是不知道怎么看内存具体是谁开销的
