### ISSUE TITLE
更新token在同一个对话里提问会出现无可用配置

### ISSUE THREAD

**Issue by dqzboy** [Kerwin1202/chatgpt-web#348]
使用的是Accesstoken，更新了Token之后，在同一个聊天里面提问题就会出现 没有可用的配置。请再试一次 | No available configuration. Please try again.  新开一个聊天就可以正常提问
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/d7c30279-de87-4caa-95e4-c22d911b1c12)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/42825450/2a1d5cb4-b07f-42b7-9fcf-1da29e980f64)

**Comment by Kerwin1202** [comment]
更新token 确定是同一个账户的么，数据库里 有一个room字段看下accountid 是什么 然后拿到你的token  网上搜在线解析 jwt 看下是否一样 一般是不一样导致的。 也不排除openai 更新token 之后相关字段会变，如果是的话麻烦提供下相关信息我好更新代码

**Comment by dqzboy** [comment]
> 更新token 确定是同一个账户的么，数据库里 有一个room字段看下accountid 是什么 然后拿到你的token 网上搜在线解析 jwt 看下是否一样 一般是不一样导致的。 也不排除openai 更新token 之后相关字段会变，如果是的话麻烦提供下相关信息我好更新代码
更新Token是同一个账号；我是配置了2个openai账号，怀疑是更新之后，继续在原来的会话里进行对话没有匹配到原来的

**Comment by Kerwin1202** [comment]
> > 更新token 确定是同一个账户的么，数据库里 有一个room字段看下accountid 是什么 然后拿到你的token 网上搜在线解析 jwt 看下是否一样 一般是不一样导致的。 也不排除openai 更新token 之后相关字段会变，如果是的话麻烦提供下相关信息我好更新代码
> > 更新Token是同一个账号；我是配置了2个openai账号，怀疑是更新之后，继续在原来的会话里进行对话没有匹配到原来的

还是得数据库的数据看看，对比对比，要么是room里的字段没写进去导致的

**Comment by dqzboy** [comment]
好的 大佬，我研究研究
