### ISSUE TITLE
上下文的发送是不是有严重的BUG? (删除的内容也发送)

### ISSUE THREAD

**Issue by padixa** [Kerwin1202/chatgpt-web#349]
假如我们给GTP分别发送3次内容: 1,  2,  3
然后我们让GPT重复说出我们发送的内容, 它会说: 你发送了1 2 3
但是如果我们删除顶部的两个对话 (1 和 GPT的回复, 这时候我们对话从2开始),  然后问GPT 重复我们发送的内容.  它竟然说:1, 2, 3....

这就不对了吧.  我们平常如果说的内容有误或者想缩短, 一般会删除中间的几段对话(或者更之前的一些无用对话),  但咱这个chatgpt-web, 原封不动把所有原来的上下文继续发送给了GPT, 导致我们上下文所花费的token一直增长, 随之费用也增多.

咱是不是应该修复一下这个BUG??    (貌似删除底部的倒是没发送这些内容)

**Comment by zhujunsan** [comment]
你说的对，确实是bug

**Comment by huangwb8** [comment]
@padixa 

你在界面里删除对话，但实际上该对话还是存在数据库里，只是不显式展示。 这里确实存在不足，即如果用户想一会使用连续对话一会使用间断对话，这会带来不便。 

我自己的习惯是：

+ 如果预计是一个长对话，则新开一个对话，点绿时钟 （如图的美波小姐）。

+ 如果预计只是一问一答，则在一个旧对话里进行，它始终是点红时钟 （如图的基础模型）。

![msedge_vf0Xd4JUtZ](https://github.com/Kerwin1202/chatgpt-web/assets/35643122/1ff8743c-8feb-4d8d-bc20-608ca2af418a)

看看其它大佬有什么建议！

**Comment by zhujunsan** [comment]
这是bug，取上下文的时候没看是否标记删除，传参要改下就好了

**Comment by padixa** [comment]
这个BUG真的是**老惨了**, 昨天一边聊天, 一边删除没用的上下文, 以为自己充分利用了GPT特性时, 余额直接给干没了....懵逼啊我.

另外谁要是修复这个BUG, 能否增加个多选功能, 有的时候聊了10句了, 想通过多选, 删除没用的无效聊天6句, 然后在剩余的4个上下文的基础上继续提问, 这才是好的使用方法吧.

**Comment by zhujunsan** [comment]
> 这个BUG真的是**老惨了**, 昨天一边聊天, 一边删除没用的上下文, 以为自己充分利用了GPT特性时, 余额直接给干没了....懵逼啊我.
> 
> 另外谁要是修复这个BUG, 能否增加个多选功能, 有的时候聊了10句了, 想通过多选, 删除没用的无效聊天6句, 然后在剩余的4个上下文的基础上继续提问, 这才是好的使用方法吧.

不好意思没注意哈。
你也可以关注下每条消息时间边上的 token 使用数量

**Comment by padixa** [comment]
> > 这个BUG真的是**老惨了**, 昨天一边聊天, 一边删除没用的上下文, 以为自己充分利用了GPT特性时, 余额直接给干没了....懵逼啊我.
> > 另外谁要是修复这个BUG, 能否增加个多选功能, 有的时候聊了10句了, 想通过多选, 删除没用的无效聊天6句, 然后在剩余的4个上下文的基础上继续提问, 这才是好的使用方法吧.
> 
> 不好意思没注意哈。 你也可以关注下每条消息时间边上的 token 使用数量

好的. 可以的话再增加个[多选]-[删除] 功能可以吗?  让我们方便裁剪聊天记录.
