### ISSUE TITLE
最近几天一直返回错误

### ISSUE THREAD

**Issue by sonnyyin** [Kerwin1202/chatgpt-web#352]
周五开始一直返回错误，无法与ChatGPT对话了，返回提示：好像出错了，请稍后再试。
![image](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/814145a2-2be2-47c0-a7e9-b5f2c5166f8e)

**Comment by Kerwin1202** [comment]
f12 看看请求是报错什么

**Comment by CEJXXX** [comment]
![Snipaste_2023-10-23_09-43-29](https://github.com/Kerwin1202/chatgpt-web/assets/127327469/1cd8cf9a-c90d-4d09-b09f-2270e3cafe78)
![Snipaste_2023-10-23_09-42-48](https://github.com/Kerwin1202/chatgpt-web/assets/127327469/b344d183-5e78-443f-8dc6-e568cbb290a7)


我的也是这样，突然就不行了

**Comment by xiaosaaaa** [comment]
是accesstoken的部署方式吗？我的也是这样，而且在gpt官方网页是能看到有对话产生的，就是没有回复

**Comment by Kerwin1202** [comment]
> ![Snipaste_2023-10-23_09-43-29](https://user-images.githubusercontent.com/127327469/277208864-1cd8cf9a-c90d-4d09-b09f-2270e3cafe78.png) ![Snipaste_2023-10-23_09-42-48](https://user-images.githubusercontent.com/127327469/277208871-b344d183-5e78-443f-8dc6-e568cbb290a7.png)
> 
> 我的也是这样，突然就不行了

看你第一个截图是 如果我没记错的话  这个模型 几个月前说好像会下架，所以你换个模型试试 

<img width="266" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/e3f8ec56-f49d-4ca0-9505-672b41525962">
<img width="144" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/e5900174-4c4a-4410-8a11-ceaa61cf3878">

**Comment by CEJXXX** [comment]
![Snipaste_2023-10-23_12-18-45](https://github.com/Kerwin1202/chatgpt-web/assets/127327469/23653ca4-af8f-4f4e-b2ce-9f2956f90626)
![Snipaste_2023-10-23_12-18-53](https://github.com/Kerwin1202/chatgpt-web/assets/127327469/16453a50-fec3-47cc-935a-cb5fc502e459)

所有模型都试过了，都用不了了。上周五应该是都还可以的。

**Comment by xiaosaaaa** [comment]
> > ![Snipaste_2023-10-23_09-43-29](https://user-images.githubusercontent.com/127327469/277208864-1cd8cf9a-c90d-4d09-b09f-2270e3cafe78.png) ![Snipaste_2023-10-23_09-42-48](https://user-images.githubusercontent.com/127327469/277208871-b344d183-5e78-443f-8dc6-e568cbb290a7.png)
> > 我的也是这样，突然就不行了
> 
> 看你第一个截图是 如果我没记错的话 这个模型 几个月前说好像会下架，所以你换个模型试试
> 
> <img alt="image" width="266" src="https://user-images.githubusercontent.com/16319833/277226310-e3f8ec56-f49d-4ca0-9505-672b41525962.png"> <img alt="image" width="144" src="https://user-images.githubusercontent.com/16319833/277226356-e5900174-4c4a-4410-8a11-ceaa61cf3878.png">

我是用accesstoken的方式部署的，换模型应该不起作用，用Openai Api Key换模型应该有用。

**Comment by dqzboy** [comment]
我今天也出现了这问题，昨天还可以使用

**Comment by CEJXXX** [comment]
> > > ![Snipaste_2023-10-23_09-43-29](https://user-images.githubusercontent.com/127327469/277208864-1cd8cf9a-c90d-4d09-b09f-2270e3cafe78.png) ![Snipaste_2023-10-23_09-42-48](https://user-images.githubusercontent.com/127327469/277208871-b344d183-5e78-443f-8dc6-e568cbb290a7.png)
> > > 我的也是这样，突然就不行了
> > 
> > 
> > 看你第一个截图是 如果我没记错的话 这个模型 几个月前说好像会下架，所以你换个模型试试
> > <img alt="image" width="266" src="https://user-images.githubusercontent.com/16319833/277226310-e3f8ec56-f49d-4ca0-9505-672b41525962.png"> <img alt="image" width="144" src="https://user-images.githubusercontent.com/16319833/277226356-e5900174-4c4a-4410-8a11-ceaa61cf3878.png">
> 
> 我是用accesstoken的方式部署的，换模型应该不起作用，用Openai Api Key换模型应该有用。

确实，我换成API KEY试了下，没问题。accesstoken没法用。
怎么解决呢？ @Kerwin1202 大佬

**Comment by 3tel** [comment]
Today it's completely unusable.

**Comment by CEJXXX** [comment]
API KEY一直是正常的，今天我换了个号，试了下accesstoken，刚开始没问题，过了一会就不行了。估计是官方对accesstoken使用有限制了。

**Comment by Kerwin1202** [comment]
你们是多久之后才会失效的，因为我一直不用access token 刚才测试了下，发现是正常的

**Comment by xiaosaaaa** [comment]
> 你们是多久之后才会失效的，因为我一直不用access token 刚才测试了下，发现是正常的

大概率是代理那边的问题，默认代理fakeopen星期六开始挂的，星期天作者修好了就可以用了，我自己搭建的go-chatgpt-api现在还是用不了。

**Comment by CEJXXX** [comment]
> > 你们是多久之后才会失效的，因为我一直不用access token 刚才测试了下，发现是正常的
> 
> 大概率是代理那边的问题，默认代理fakeopen星期六开始挂的，星期天作者修好了就可以用了，我自己搭建的go-chatgpt-api现在还是用不了。

看来确实是这样，代理改成fakeopen就可以用了，我之前也用的是自建go-chatgpt-api。除了这个还有别的推荐的自建代理吗？

**Comment by sonnyyin** [comment]
我的还是用不了，不过大概率是代理的问题，周六看到跳出来代理异常的页面。
![图片](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/5bed3b48-ebf4-4c96-90a6-feba8a2d7f93)

**Comment by CEJXXX** [comment]
> 我的还是用不了，不过大概率是代理的问题，周六看到跳出来代理异常的页面。 ![图片](https://user-images.githubusercontent.com/33096611/278988606-5bed3b48-ebf4-4c96-90a6-feba8a2d7f93.png)

https://ai.fakeopen.com/api/conversation 用这个应该可以
