### ISSUE TITLE
本地运行一直报错

### ISSUE THREAD

**Issue by zhuangxuan** [Kerwin1202/chatgpt-web#353]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/13015584/f9ef9aa2-7976-4305-8aed-bf8c768fd376)

**Comment by zhuangxuan** [comment]
本地环境node  v16.20.0  
运行命令：
cd service ;  pnpm start
cd ..;    pnpm dev

**Comment by huangwb8** [comment]
@zhuangxuan 

推荐使用docker来搭建，不需要处理各种环境问题。详见：《[Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)》。

祝好！

**Comment by zhuangxuan** [comment]
@huangwb8 @Kerwin1202  我之前看了你的文章了，搭建成功了，但是我想学习一下里面的代码，想本地运行调试，很早之前是可以运行的，现在突然报错说是require 没有定义，网上搜了一圈没找到解决方案，可以帮分析下吗？  我的node是16版本，其他版本也试过了,也还是报错。

**Comment by zhuangxuan** [comment]
是我自己的问题，找到了，代码让我很早之前给改动了
