### ISSUE TITLE
最近重装后开始有问题

### ISSUE THREAD

**Issue by a8500830** [Kerwin1202/chatgpt-web#354]
我是在openwrt的docker上运行的。之前一直好好的没问题，前几天重装后出现了问题，问题如下：
不能开openclash使用。之前没问题，现在打开open clash不管使用什么规则都不行（节点肯定没问题的）包括所有代理都走直连，所有代理都走代理。其他docker都能使用openclass访问，唯独这个不行。
更换别人家的第三方密钥和代理网址也不行。
关闭openclash可以使用。
打开ssr plus+可以使用，但其他docker又不走代理。
望解答

**Comment by a8500830** [comment]
提示fetch failed

**Comment by Kerwin1202** [comment]
可能是代理问题？我是设置这个代理就行 用的clash 开启局域网 然后设置 socks


<img width="618" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/331c8e97-fbcb-46d0-9ca5-62bd8b0189f4">

**Comment by a8500830** [comment]
不应该是代理问题啊，因为之前版本就好好的，这个版本开clash直接失效
