### ISSUE TITLE
最新版本用户管理删除按钮不显示了

### ISSUE THREAD

**Issue by 02000823** [Kerwin1202/chatgpt-web#357]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/84962546/73f6c54e-3893-4db4-a3e0-b505236aca5d)

**Comment by huangwb8** [comment]
该bug确实存在 @Kerwin1202

**Comment by Kerwin1202** [comment]
确实，，我电脑屏幕有点大所以可以看到，暂时的解决办法是 比如 chrome edge 右上角三个点 缩放下网页，刷新就可以看到了
