### ISSUE TITLE
用手机打开网页端，用户管理界面，删除编辑账户下面有时候会出现红圈内的显示问题，无法消除

### ISSUE THREAD

**Issue by 02000823** [Kerwin1202/chatgpt-web#358]
![IMG_20231105_004024.jpg](https://github.com/Kerwin1202/chatgpt-web/assets/84962546/721d2770-e48a-479f-8219-062336fbdd04)

**Comment by Kerwin1202** [comment]
这是正常的，因为这个人开了 2FA 管理员可以关闭，就是没翻译而已
