### ISSUE TITLE
文本审核貌似没有提示含有敏感词

### ISSUE THREAD

**Issue by luckywangxi** [Kerwin1202/chatgpt-web#36]
在百度后台可以看到API已被调用
![image](https://user-images.githubusercontent.com/112324550/232425497-4129fc95-9904-401b-987a-6d7409f66040.png)

但网站没有提示含有敏感词，文本测试显示不含敏感词
![image](https://user-images.githubusercontent.com/112324550/232425188-3a98ab5c-27fe-41a2-ad67-3d18fd3eedf1.png)
![image](https://user-images.githubusercontent.com/112324550/232425740-8c1a0355-4699-4cf8-a304-4fe2ee03c962.png)

**Comment by Fugitive844** [comment]
我的也没生效

**Comment by Fugitive844** [comment]
聊天的时候没调用百度API检测
