### ISSUE TITLE
是否能支持最新的GPT-4 Turbo模型

### ISSUE THREAD

**Issue by cjnss008** [Kerwin1202/chatgpt-web#361]
以及支持对应的gpt-4-vision-preview绘图模型

**Comment by padixa** [comment]
怎么一点都不着急, 新的gpt4模型不但日期更新到了2023, 还省钱. 干嘛呢这是...

**Comment by Kerwin1202** [comment]
> 怎么一点都不着急, 新的gpt4模型不但日期更新到了2023, 还省钱. 干嘛呢这是...

因为我没天天关注是否有最新模型，也没去研究这个模型有什么好处， 然后有人提了个issue 可能当时看到了，有事没空改，后面忘记了，上面看有6个点 但是这种是没有提醒的 你这多催 邮件提醒就看到了会加，，另外可以提供最新的看到的相关连接，我也好了解下

**Comment by Kerwin1202** [comment]
后面优化为允许自己添加模型

**Comment by padixa** [comment]
@Kerwin1202 , 代码测了没? 怎么我pull了latest, 还是不显示?   另外确实需要在设置里有地方能增加/管理自定义的模型名更方便一些.(甚至可以删除不用的模型)

**Comment by Kerwin1202** [comment]
自己key 管理添加就行，新加的默认没给，包括删除不用 你不给这个key这个模型就没有

**Comment by padixa** [comment]
你不早说, 哈哈. 还找半天.  谢了.

**Comment by cjnss008** [comment]
@Kerwin1202 docker拉取最新配置，没找到新模型啊
![Uploading 1.png…]()

**Comment by Kerwin1202** [comment]
@cjnss008 
```
docker pull kerwin1202/chatgpt-web
docker-compose up -d
```

<img width="651" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/93a70b51-1b0e-461b-ae3d-4ac70ff0863f">

**Comment by cjnss008** [comment]
@Kerwin1202 已拉取到，不过vision支持的图片需要图片上传功能，以及图片DALL·E 3模型生成功能。希望未来能添加，谢谢。
相关新闻链接：https://openai.com/blog/new-models-and-developer-products-announced-at-devday

**Comment by padixa** [comment]
还有`gpt-3.5-turbo-1106`呢?   你还是把列表手动增加功能早日加上吧.

**Comment by ceozero** [comment]
> 还有`gpt-3.5-turbo-1106`呢? 你还是把列表手动增加功能早日加上吧.

+1

**Comment by HanZhongic** [comment]
> 还有`gpt-3.5-turbo-1106`呢? 你还是把列表手动增加功能早日加上吧.

+1

**Comment by Kerwin1202** [comment]
<img width="865" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/6b96c0ec-259f-4970-8ade-88ad6758e7fa">

**Comment by yangxiao960602** [comment]
@padixa 
从来不在互联网上引战, 但实在是太多次, 在不同的issue下看到你的发言语气与态度.
有本事, 你就自己改代码提交合并. 
没有本事, 那就去学.
既没本事改又不想学, 就态度/语气放客气点提建议.
免费的公益项目你希望有专业的售后服务团队伺候你?

**Comment by padixa** [comment]
@yangxiao960602 我并没对作者表现什么恶意, 只是回复很随意而已. 再说了别人都不说什么, 你急什么? 我也没让你给我做什么吧? 我也没评价你的任何回复吧?  说不想引战, 又说话这么难听....又立又当吗?

**Comment by yangxiao960602** [comment]
@padixa 
确实从不引战, 但也确实看不顺眼, 所以这次既不当也不立, 选择直接开喷. 
望你终有一天能为你所谓的"随意的回复"(口无遮拦?)负起责任, 付出代价.

**Comment by padixa** [comment]
@yangxiao960602  哈哈, 别咒我了. 倒是你把格局打开. 到此为止吧, 就别占用这个issue来谈自我感受了.
