### ISSUE TITLE
功能改进建议： 大佬是否可以增加给每个key单独设置API地址的功能

### ISSUE THREAD

**Issue by liuchao0807** [Kerwin1202/chatgpt-web#369]
当前有部分key来源于不同的第三方，api的url都不一致，切换起来比较麻烦
建议：每个key的配置里增加一个api url的配置，如果没填则使用全局设置里的地址

**Comment by a8500830** [comment]
同意，很好的功能

**Comment by Kerwin1202** [comment]
<img width="1249" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/d47ed874-1437-4635-9d63-d1fa8fe617ed">

**Comment by a8500830** [comment]
> <img alt="image" width="1249" src="https://private-user-images.githubusercontent.com/16319833/293470652-d47ed874-1437-4635-9d63-d1fa8fe617ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzAyMDgsIm5iZiI6MTcwNDA2OTkwOCwicGF0aCI6Ii8xNjMxOTgzMy8yOTM0NzA2NTItZDQ3ZWQ4NzQtMTQzNy00NjM1LTlkNjMtZDFmYThmZTYxN2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDAwNDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDYzOGFkN2Y4ZWFjOTFjYWQyNjdhZjU1ZTkyYzRmZGE1NzNhYTJiOTRhODVlMDg4OWNlMDgyMWM5MmY1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hR98suCa2qjMQ7mg0Uhlrk7EwF9bb8OPiM3CavoSCVM">
问题又来了，设置的这个api地址，和基础配置里的接口地址重合了，目前还是以基础配置里的地址为准。如果基础配置的token失效了，切换地址还是需要把token的api替换过去

**Comment by Kerwin1202** [comment]
默认如果不写 是以基础配置里的，如果写了是优先 这个单独的

**Comment by a8500830** [comment]
确实可可以了，是我代理的问题

Kerwin1202 ***@***.***>于2024年1月1日 周一下午2:26写道：
