### ISSUE TITLE
反向代理没有保存

### ISSUE THREAD

**Issue by wanghai-king** [Kerwin1202/chatgpt-web#37]
从环境变量可以保存数据库，在页面配置中没有保存到数据库
![QQ截图20230417163305](https://user-images.githubusercontent.com/77134863/232430500-cd96f19f-3561-46ab-b75a-a4cc4b6bfa79.png)

**Comment by Kerwin1202** [comment]
昨天改过 没push  下次打包    8afc235a0efd24e43dfa4d64b7e402f03673691d

**Comment by wanghai-king** [comment]
我想请教一下大佬，您改前端用的什么工具，前端用什么软件可以可视化修改，没学过vue，代码也看不懂

**Comment by Kerwin1202** [comment]
> 我想请教一下大佬，您改前端用的什么工具，前端用什么软件可以可视化修改，没学过vue，代码也看不懂

vs code，vue 跑起来就浏览器访问 改了实时更新的
