### ISSUE TITLE
MONGODB_URL

### ISSUE THREAD

**Issue by ytking** [Kerwin1202/chatgpt-web#372]
MONGODB_URL怎么来的，需要在MongoDB做哪些配置

**Comment by 2ndelement** [comment]
mongo://用户名:密码@主机ip/数据库名

**Comment by 2ndelement** [comment]
mongodb镜像里，MONGO_INITDB_DATABASE好像不起作用，使用的是默认admin数据库，所以不需要配置

**Comment by Kerwin1202** [comment]
默认不是有一个 docker-compose.yml 配置吗，，如果你是直接这个配置的 那么改对饮的账号密码即可了，但是如果你是另外单独设置的 mongodb数据库，那么删掉 下面部分 改对应的连接服务器以及帐号密码

<img width="819" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/f3a09587-2e07-4cf3-b56a-29ecd9026530">
