### ISSUE TITLE
邮箱验证问题

### ISSUE THREAD

**Issue by leijmin** [Kerwin1202/chatgpt-web#373]
我创建了三个账号，邮箱始终收不到验证码，一个都没收到
一个qq邮箱，2个google邮箱
目前暂时是改数据库status=0解决的
我使用的是v2.13.7的tag运行的项目

**Comment by leijmin** [comment]
可以加个v吗？向你学习学习；或者有交流群吗？拉我进下。谢谢！

**Comment by Kerwin1202** [comment]
我没群， v 的话 zhiwei2145      

收不到验证码  是不是你没配置邮箱啊   部署好之后，先采用 root账号注册 这不需要验证 直接登录
然后左下角有设置里面配置邮箱  里面也有用户管理可以通过验证
