### ISSUE TITLE
统计界面能否加一个按用户筛选或按用户显示用量的功能？

### ISSUE THREAD

**Issue by weisuiyu** [Kerwin1202/chatgpt-web#378]
统计界面能否加一个按用户筛选或按用户显示用量的功能？

**Comment by darkice1** [comment]
我也想要这个功能

**Comment by Kerwin1202** [comment]
<img width="809" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/d3936c8c-b1b4-4716-a867-b7946cc3d0b8">
