### ISSUE TITLE
mongo 怎么登录进去

### ISSUE THREAD

**Issue by 1515806183** [Kerwin1202/chatgpt-web#38]
docker exec -it mongo mongo admin 没办法进去。

**Comment by huangwb8** [comment]
@1515806183 

可以参考我的教程： https://blognas.hwb0307.com/linux/docker/4201

我使用了Mongo-Express作为GUI，比较直观：

![msedge_UufsU9WmR6-2](https://user-images.githubusercontent.com/35643122/232467533-02e07a88-e6eb-4861-a912-2b34357ebb6f.gif)

**Comment by 1515806183** [comment]
> @1515806183
> 
> 可以参考我的教程： https://blognas.hwb0307.com/linux/docker/4201
> 
> 我使用了Mongo-Express作为GUI，比较直观：
> 
> ![msedge_UufsU9WmR6-2](https://user-images.githubusercontent.com/35643122/232467533-02e07a88-e6eb-4861-a912-2b34357ebb6f.gif) [ ![msedge_UufsU9WmR6-2](https://user-images.githubusercontent.com/35643122/232467533-02e07a88-e6eb-4861-a912-2b34357ebb6f.gif) ](https://user-images.githubusercontent.com/35643122/232467533-02e07a88-e6eb-4861-a912-2b34357ebb6f.gif) [ ](https://user-images.githubusercontent.com/35643122/232467533-02e07a88-e6eb-4861-a912-2b34357ebb6f.gif)

大佬的博客写的真好，博客源码能分享？

**Comment by huangwb8** [comment]
@1515806183 

我的博客主题是开源的。 具体请至学习地图查看： https://blognas.hwb0307.com/map 。 有问题可以留言或加tg群： https://t.me/benszhub 

感谢你的关注喔！但我的博客与本issue不直接相关。 如果issue得到解决，请考虑关闭该issue。 谢谢合作！
