### ISSUE TITLE
使用 API 的时候必须填写 PROXY 吗? 

### ISSUE THREAD

**Issue by HolmesZhao** [Kerwin1202/chatgpt-web#381]
使用 API 的时候必须填写 PROXY 吗? 我这边尝试删除Proxy 报错如下:
![image](https://github.com/Kerwin1202/chatgpt-web/assets/19728934/479cca2a-d326-414a-af5e-9b2a6e568293)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/19728934/f0fa5404-eaa3-4eeb-b666-ad757ff090d6)

看了一下这个 API 的地址并没有被墙, 不需要代理就可以才对

**Comment by Kerwin1202** [comment]
你说的没有被墙是你访问这个api 没有吧，但是这个api 访问openai呢也是正常的么，，下面的选项都是可选的

**Comment by assassinliujie** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/68693675/c9f47b15-5b93-48b5-8f82-c42054a3e6ad)
检查下提供反代的那边，正常反代应该返回这样的信息
![image](https://github.com/Kerwin1202/chatgpt-web/assets/68693675/89b2d6cf-0b2d-4ed8-b424-d614eefd3cbd)

**Comment by HolmesZhao** [comment]
> ![image](https://private-user-images.githubusercontent.com/68693675/289261623-c9f47b15-5b93-48b5-8f82-c42054a3e6ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE2MjMtYzlmNDdiMTUtNWI5My00OGI1LThmODItYzQyMDU0YTNlNmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjM3MDcyNmQ0YTA2NDQ4YWNmMDQwNDI5ZDIyYTdlM2Q1Mzc3M2U3MGYyNzJjZmQ3ZWFkNWVlYzBhNTllOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5SRiX_Es4FgMSFVIUTW2ozYI4OGBWrFngmOrt2YLPI) 检查下提供反代的那边，正常反代应该返回这样的信息 ![image](https://private-user-images.githubusercontent.com/68693675/289261751-89b2d6cf-0b2d-4ed8-b424-d614eefd3cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE3NTEtODliMmQ2Y2YtMGIyZC00ZWQ4LWI0MjQtZDYxNGVlZmQzY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMmJkMmU5Y2NiZWJhZDdjNTU5NjRlMzhkZWQ3ZjdkM2NkNjg5NGY0MzgxMGZmODI0OGJlYTU1M2E5OTZmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MN7IGkr08HYVM_bF8N22iEc504qZB7d50e4K8kih1m4)

api 也会用反代么? 我是默认的反代, 我记得代码里面用api 不会用反代啊

**Comment by HolmesZhao** [comment]
> 你说的没有被墙是你访问这个api 没有吧，但是这个api 访问openai呢也是正常的么，，下面的选项都是可选的

正常, 有在 postman 无梯子尝试过

**Comment by assassinliujie** [comment]
> > ![image](https://private-user-images.githubusercontent.com/68693675/289261623-c9f47b15-5b93-48b5-8f82-c42054a3e6ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE2MjMtYzlmNDdiMTUtNWI5My00OGI1LThmODItYzQyMDU0YTNlNmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjM3MDcyNmQ0YTA2NDQ4YWNmMDQwNDI5ZDIyYTdlM2Q1Mzc3M2U3MGYyNzJjZmQ3ZWFkNWVlYzBhNTllOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5SRiX_Es4FgMSFVIUTW2ozYI4OGBWrFngmOrt2YLPI) 检查下提供反代的那边，正常反代应该返回这样的信息 ![image](https://private-user-images.githubusercontent.com/68693675/289261751-89b2d6cf-0b2d-4ed8-b424-d614eefd3cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE3NTEtODliMmQ2Y2YtMGIyZC00ZWQ4LWI0MjQtZDYxNGVlZmQzY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMmJkMmU5Y2NiZWJhZDdjNTU5NjRlMzhkZWQ3ZjdkM2NkNjg5NGY0MzgxMGZmODI0OGJlYTU1M2E5OTZmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MN7IGkr08HYVM_bF8N22iEc504qZB7d50e4K8kih1m4)
> 
> api 也会用反代么? 我是默认的反代, 我记得代码里面用api 不会用反代啊

？你用的这个接口地址就是别人反代的就你用的这个https://api.openai-sb.com

**Comment by assassinliujie** [comment]
> > 你说的没有被墙是你访问这个api 没有吧，但是这个api 访问openai呢也是正常的么，，下面的选项都是可选的
> 
> 正常, 有在 postman 无梯子尝试过

是让你测试api.openai-sb.com这个反代服务搭建者是否正常配置了反代，不是让你测这个网址本身能不能访问

**Comment by assassinliujie** [comment]
> > 你说的没有被墙是你访问这个api 没有吧，但是这个api 访问openai呢也是正常的么，，下面的选项都是可选的
> 
> 正常, 有在 postman 无梯子尝试过

![Uploading 图片.png…]()
看看第二部到底通不通，这服务是你搭的还是你网上随便搜的

**Comment by assassinliujie** [comment]
> > ![image](https://private-user-images.githubusercontent.com/68693675/289261623-c9f47b15-5b93-48b5-8f82-c42054a3e6ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE2MjMtYzlmNDdiMTUtNWI5My00OGI1LThmODItYzQyMDU0YTNlNmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjM3MDcyNmQ0YTA2NDQ4YWNmMDQwNDI5ZDIyYTdlM2Q1Mzc3M2U3MGYyNzJjZmQ3ZWFkNWVlYzBhNTllOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d5SRiX_Es4FgMSFVIUTW2ozYI4OGBWrFngmOrt2YLPI) 检查下提供反代的那边，正常反代应该返回这样的信息 ![image](https://private-user-images.githubusercontent.com/68693675/289261751-89b2d6cf-0b2d-4ed8-b424-d614eefd3cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM4OTksIm5iZiI6MTcwMjgyMzU5OSwicGF0aCI6Ii82ODY5MzY3NS8yODkyNjE3NTEtODliMmQ2Y2YtMGIyZC00ZWQ4LWI0MjQtZDYxNGVlZmQzY2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMmJkMmU5Y2NiZWJhZDdjNTU5NjRlMzhkZWQ3ZjdkM2NkNjg5NGY0MzgxMGZmODI0OGJlYTU1M2E5OTZmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MN7IGkr08HYVM_bF8N22iEc504qZB7d50e4K8kih1m4)
> 
> api 也会用反代么? 我是默认的反代, 我记得代码里面用api 不会用反代啊

看了下这是个第三方的API提供商，你得用他们自家的API KEY试一下，用官方的肯定不行，他们自己转换过了，和单纯的反向代理还不一样
