### ISSUE TITLE
请问内存和磁盘占用是否正常？

### ISSUE THREAD

**Issue by 404gods** [Kerwin1202/chatgpt-web#383]
Docker-compose方式部署，可以正常使用，但是觉得chatgptweb容器和mongo数据库容器的内存和磁盘占用过大，因为只试了几次问话而已，请问这是否正常?如图
![11](https://github.com/Kerwin1202/chatgpt-web/assets/50573302/77a1876b-8ff1-41aa-8ed0-a969c5b3ccd8)
![12](https://github.com/Kerwin1202/chatgpt-web/assets/50573302/1a3e3465-ac68-4385-84b5-d649ef45c121)

**Comment by Kerwin1202** [comment]
内存优化不是专业的，不太好说。 我自认为 200M 以内还行吧，对程序来说可能有点大  数据库不大
