### ISSUE TITLE
本地启动报500

### ISSUE THREAD

**Issue by 2014guai** [Kerwin1202/chatgpt-web#384]
本地启动前后端，session接口报错Cannot read properties of undefined (reading 'loginEnabled')

![image](https://github.com/Kerwin1202/chatgpt-web/assets/22672617/5725408c-65b8-4229-90f2-d0cfc6b77629)

**Comment by Kerwin1202** [comment]
没有配置看不出 ，看了下代吗 估计是这个报错，所以猜测你有数据库，但是数据库里的数据不对，导致siteconfig这个配置是空。。 解决办法删掉数据库让他自动生成


<img width="934" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/e8d57a0e-b08d-48b0-832f-ee9cf6007bfd">

**Comment by a8500830** [comment]
为啥每次重装docker后第一次登陆都会报500错误，需要清除缓存才可以。每次的yml文件都一样，但每次重装都需要清除。。

**Comment by Kerwin1202** [comment]
> 为啥每次重装docker后第一次登陆都会报500错误，需要清除缓存才可以。每次的yml文件都一样，但每次重装都需要清除。。

提供f12看下哪个接口有问题 以及 报错的提示

**Comment by mattholy** [comment]
估计你的数据库账号密码错误了，你可以用`docker logs 你的数据库`来看看。我也是这个问题。

**Comment by Kerwin1202** [comment]
@2014guai  当然有了，，配置了mongodb url 就有，不配置也跑不起来 所以肯定有

**Comment by 2014guai** [comment]
可以了，本地数据库连接问题，谢谢
