### ISSUE TITLE
Keys 管理界面如果只有一条记录，无法删除成功

### ISSUE THREAD

**Issue by git-gao** [Kerwin1202/chatgpt-web#385]
正常的删除功能是可以的，
删除最后一个 key 时，界面上的记录无法删除，数据库后台会多出这条删除的记录
操作如下，正常还剩最后一条记录
![image](https://github.com/Kerwin1202/chatgpt-web/assets/37399419/777a8983-c360-4604-8f3c-9472b8208570)
界面删除点击删除后，多出一个状态 0 的记录
![image](https://github.com/Kerwin1202/chatgpt-web/assets/37399419/d9295b3a-7d10-41bf-a5dd-e0237ea69485)

**Comment by Kerwin1202** [comment]
恩，，默认始终会留一个，，你可以新加一个然后删除旧的

**Comment by git-gao** [comment]
其实我是想用 accesstoken 的，我记得好像 api key 和 accesstoken 同时存在会优先使用 key，配置 access token 没生效，会话会报 apikey 无效，所以我就想是不是因为这个 key 无法删除的原因

**Comment by Kerwin1202** [comment]
不是啊，一个道理啊，你先新加一个 access token 然后删掉旧的，确保记录有一个  我说的不是留一个key

**Comment by git-gao** [comment]
我的我的，界面变更了，我都忘记在这里配置 access token 了
