### ISSUE TITLE
【求助】统计界面刷新不出来数据，响应提示 InvalidPipelineOperator

### ISSUE THREAD

**Issue by git-gao** [Kerwin1202/chatgpt-web#386]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/37399419/9a56b2d5-3cd7-429b-b340-4ceb702e49f0)
浏览器查看接口返回，提示这个，可能原因是什么，还是我的账号有什么问题
{"ok":0,"code":168,"codeName":"InvalidPipelineOperator"}

**Comment by Kerwin1202** [comment]
应该是mongodb 版本的问题，看看用的什么版本 我是5.0.4
