### ISSUE TITLE
给各位带来一个好消息，经测试已经成功实现在本项目（与两个项目配合）实现画图功能，gpts功能应该也行（未测试）

### ISSUE THREAD

**Issue by Minstrel-Lee** [Kerwin1202/chatgpt-web#391]
1. 功能是在pandora-next/deploy和Ink-Osier/PandoraToV1Api两个项目的加持下实现的。

2. pandora-next是老pandora的升级版，具有图形界面和proxy的功能，PandoraToV1Api这个项目是在pandora-next的基础上用v1/chat/completions接口实现了许多可玩性的功能。

3. gpts及一些其他功能的使用应该需要作者协助增加可自定义的模型名称才能实现，具体能增加哪些功能可以参考此项目Ink-Osier/PandoraToV1Api

4. 两位的项目我放在下面，如果觉得不妥可自行或联系我删除。
https://github.com/pandora-next/deploy
https://github.com/Ink-Osier/PandoraToV1Api
感谢四位，Kerwin1202，Ink-Osier，zhile秦始皇，Chanzhaoyu（排名不分先后）,感谢四位大佬为我们带来如此棒的项目。

**Comment by nanbei-zhuge** [comment]
![Uploading 捕获.PNG…]()

**Comment by nanbei-zhuge** [comment]
![捕获](https://github.com/Kerwin1202/chatgpt-web/assets/150283773/c8b8a28b-37e4-4c9b-af4a-f25e68c244d4)

**Comment by sonnyyin** [comment]
这个应该怎么配置才能使用Ink-Osier/PandoraToV1Api？

**Comment by sonnyyin** [comment]
搞成了，不过为什么我的会话一直没办法自动结束响应呢？用的作者最新更新的版本。

![image](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/8f06000a-789b-454e-97f8-14909ed736c8)

![image](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/44010fd1-d4fb-4d0f-81ac-6ddced8fdaae)

**Comment by nanbei-zhuge** [comment]
> 搞成了，不过为什么我的会话一直没办法自动结束响应呢？用的作者最新更新的版本。
> 
> ![image](https://private-user-images.githubusercontent.com/33096611/291625019-8f06000a-789b-454e-97f8-14909ed736c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjUwMTktOGYwNjAwMGEtNzg5Yi00NTRlLTk3ZjgtMTQ5MDllZDczNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmQ0M2U3NGM0ODc3MGE2YWQ3MmM1MTk4MTkyMjM3NTBlY2M5ODI2OWU0MjA4ZDc0NGIyNTI4MzZhNjYzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoM4ESqMXq_BoYpC6JxC-X07tyM7P36uLq2NhwZJ6qo)
> 
> ![image](https://private-user-images.githubusercontent.com/33096611/291625755-7c2d5257-5391-4499-a9f1-578ac2ca0f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjU3NTUtN2MyZDUyNTctNTM5MS00NDk5LWE5ZjEtNTc4YWMyY2EwZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWMwN2M3ZjFmMDM4MjM4NWM1ZWU2YjI4MzZmY2VjNzkyNDhhMDFhNWJiYzUxYzIwNzg2MWE1NmY1MmRiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7fDYdhpDdc3G8IMWzW4ENpGDYUlYas9HL20rt393aE)

先用0.1.6

**Comment by sonnyyin** [comment]
> > 搞成了，不过为什么我的会话一直没办法自动结束响应呢？用的作者最新更新的版本。
> > ![image](https://private-user-images.githubusercontent.com/33096611/291625019-8f06000a-789b-454e-97f8-14909ed736c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjUwMTktOGYwNjAwMGEtNzg5Yi00NTRlLTk3ZjgtMTQ5MDllZDczNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmQ0M2U3NGM0ODc3MGE2YWQ3MmM1MTk4MTkyMjM3NTBlY2M5ODI2OWU0MjA4ZDc0NGIyNTI4MzZhNjYzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoM4ESqMXq_BoYpC6JxC-X07tyM7P36uLq2NhwZJ6qo)
> > ![image](https://private-user-images.githubusercontent.com/33096611/291625755-7c2d5257-5391-4499-a9f1-578ac2ca0f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjU3NTUtN2MyZDUyNTctNTM5MS00NDk5LWE5ZjEtNTc4YWMyY2EwZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWMwN2M3ZjFmMDM4MjM4NWM1ZWU2YjI4MzZmY2VjNzkyNDhhMDFhNWJiYzUxYzIwNzg2MWE1NmY1MmRiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7fDYdhpDdc3G8IMWzW4ENpGDYUlYas9HL20rt393aE)
> 
> 先用0.1.6

果然0.1.6可以正常使用，感谢。

**Comment by Urmi10799** [comment]
> How should this be configured to use Ink-Osier/PandoraToV1Api? How to configure chatgpt-web? Can you give me some guidance?


How did you configure it? can you give me some guidance?

**Comment by nanbei-zhuge** [comment]
> > How should this be configured to use Ink-Osier/PandoraToV1Api? How to configure chatgpt-web? Can you give me some guidance?
> 
> How did you configure it? can you give me some guidance?

Since I am not that professional, here are the documents about pandora-next you can refer to.
https://docs.pandoranext.com/api-ref/proxy/

about Ink-Osier/PandoraToV1Api, you can wait for the author to write the documentation on how to use it.
https://github.com/Ink-Osier/PandoraToV1Api/issues/11

**Comment by dabao-Lee** [comment]
> > > 搞成了，不过为什么我的会话一直没办法自动结束响应呢？用的作者最新更新的版本。
> > > ![image](https://private-user-images.githubusercontent.com/33096611/291625019-8f06000a-789b-454e-97f8-14909ed736c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjUwMTktOGYwNjAwMGEtNzg5Yi00NTRlLTk3ZjgtMTQ5MDllZDczNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmQ0M2U3NGM0ODc3MGE2YWQ3MmM1MTk4MTkyMjM3NTBlY2M5ODI2OWU0MjA4ZDc0NGIyNTI4MzZhNjYzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoM4ESqMXq_BoYpC6JxC-X07tyM7P36uLq2NhwZJ6qo)
> > > ![image](https://private-user-images.githubusercontent.com/33096611/291625755-7c2d5257-5391-4499-a9f1-578ac2ca0f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA0NDcsIm5iZiI6MTcwMzAwMDE0NywicGF0aCI6Ii8zMzA5NjYxMS8yOTE2MjU3NTUtN2MyZDUyNTctNTM5MS00NDk5LWE5ZjEtNTc4YWMyY2EwZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWMwN2M3ZjFmMDM4MjM4NWM1ZWU2YjI4MzZmY2VjNzkyNDhhMDFhNWJiYzUxYzIwNzg2MWE1NmY1MmRiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7fDYdhpDdc3G8IMWzW4ENpGDYUlYas9HL20rt393aE)
> > 
> > 
> > 先用0.1.6
> 
> 果然0.1.6可以正常使用，感谢。
和作者沟通一下，最新版已经修复了。

**Comment by sonnyyin** [comment]
> > > How should this be configured to use Ink-Osier/PandoraToV1Api? How to configure chatgpt-web? Can you give me some guidance?
> > 
> > 
> > How did you configure it? can you give me some guidance?
> 
> Since I am not that professional, here are the documents about pandora-next you can refer to. https://docs.pandoranext.com/api-ref/proxy/
> 
> about Ink-Osier/PandoraToV1Api, you can wait for the author to write the documentation on how to use it. [Ink-Osier/PandoraToV1Api#11](https://github.com/Ink-Osier/PandoraToV1Api/issues/11)

![QQ截图20231220132802](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/a6e46368-45a3-4081-a98a-c612bfa8bbbb)

![QQ截图20231220133023](https://github.com/Kerwin1202/chatgpt-web/assets/33096611/85075386-4b24-4353-b5b2-e1aa81f98bd3)

**Comment by dqzboy** [comment]
配置之后提示[OpenAI] 提供错误的API密钥 | Incorrect API key provided

**Comment by assassinliujie** [comment]
gpts gptmobile和gpt4自带的联网功能都可以利用这种方式实现，唯一缺点是本项目还不支持上传文件和图片

**Comment by assassinliujie** [comment]
> > How should this be configured to use Ink-Osier/PandoraToV1Api? How to configure chatgpt-web? Can you give me some guidance?
> 
> How did you configure it? can you give me some guidance?
使用https://github.com/pandora-next/deploy部署，并安装指示开启proxy模式
然后到chat.openai.com官网获取账号的accesstoken
然后在
![image](https://github.com/Kerwin1202/chatgpt-web/assets/68693675/c8605446-a345-4605-8e60-e46a25f5fef5)
如图所示，用/fk转换为share token
然后在https://github.com/Ink-Osier/PandoraToV1Api
将pandoranext的backend-api转换为openapi格式，
然后即可使用。使用时，BASEURL为pandoratov1api的地址，apikey是share token也可配合https://github.com/songquanpeng/one-api使用
