### ISSUE TITLE
能否添加一个选项，包含上下文最大条数。

### ISSUE THREAD

**Issue by leosam1024** [Kerwin1202/chatgpt-web#394]
如果在一个话题里继续提问，会将全部上下文都带入，但实际可能只需要近几次上下文即可
所以希望有个最大提交上下文数量的设置。
能比较好的减少token消耗。

感谢大佬的贡献

**Comment by Kerwin1202** [comment]
<img width="1257" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/224b6a99-f4c8-4562-b26c-bcf55a36ad3d">
<img width="745" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/62db4e28-abdc-45cd-ad1e-10b5d97356e1">

**Comment by padixa** [comment]
说实在的, 增加这个真的不如增加个快速删除某个上下文的方式, 比如鼠标在某个上下文上移上去时右边显示(漂浮)某个删除按钮(垃圾桶或×), 然后单击它即可删除那个上下文, 这样不需要的上下文我们及时删除, 有便于删减没必要的上下文.
