### ISSUE TITLE
聊天记录加载异常

### ISSUE THREAD

**Issue by VectorZhao** [Kerwin1202/chatgpt-web#40]
**频率**：几乎每次必现
**平台**：手机以及chrome都会出现

**error（F12控制台信息）**：

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="https://chatgpt.olft.me/assets/index-6af8a255.js:319" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">index-6af8a255.js:319</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'uuid')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Ye (<span class="devtools-link" role="link" tabindex="-1" title="https://chatgpt.olft.me/assets/index-6af8a255.js:319:2487" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">index-6af8a255.js:319:2487</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at n (<span class="devtools-link" role="link" tabindex="-1" title="https://chatgpt.olft.me/assets/index-d7a924be.js:3105:21180" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">index-d7a924be.js:3105:21180</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | Ye | @ | index-6af8a255.js:319
-- | -- | -- | --
  | n | @ | index-d7a924be.js:3105
  | setTimeout（异步） |   |  
  | （匿名） | @ | index-d7a924be.js:3105
  | ge | @ | index-6af8a255.js:319
  | on | @ | index-d7a924be.js:1
  | Bo | @ | index-d7a924be.js:1
  | o | @ | index-d7a924be.js:1

</span></div>
</body>
</html>

![image](https://user-images.githubusercontent.com/16644993/232656846-914c0af8-7aed-4c70-9f38-f12a5c877d04.png)

**Comment by VectorZhao** [comment]
对了，docker版本的话我是fork你的项目，github action自己编译的镜像上传至docker hub。应该跟这个没关系吧。

**Comment by Kerwin1202** [comment]
自己打包的话 提供 下这个文件吧

![image](https://user-images.githubusercontent.com/16319833/232657224-3b86a3f6-2bf5-4c17-b95c-39fe2ebf0c61.png)

**Comment by VectorZhao** [comment]
这个index-6af8a255.js文件吗？在docker容器内部里面找吗？

**Comment by Kerwin1202** [comment]
就截图这个点击一下 然后保存下来就可以了, 另外你报错是原本有聊天记录的是吧  只是刷新的时候加载失败了.. 如果可以的话 提供这块的录屏（可以复现的录屏

![image](https://user-images.githubusercontent.com/16319833/232658071-719ddb47-358d-492e-888d-3506f96443c6.png)
![image1](https://user-images.githubusercontent.com/16319833/232657953-d06db5ca-b74d-453d-a015-908974cc15a8.png)

**Comment by VectorZhao** [comment]
![error](https://user-images.githubusercontent.com/16644993/232659601-fbf324ce-c4a2-4239-ba9e-ad02c10d0172.gif)
[index-6af8a255.zip](https://github.com/Kerwin1202/chatgpt-web/files/11257477/index-6af8a255.zip)

**Comment by VectorZhao** [comment]
持续刷新，会交替复现

**Comment by Kerwin1202** [comment]
我刷20次都不出现... 要是有你这概率估计早修了,  我晚点看下

**Comment by VectorZhao** [comment]
所以说我觉得也很奇怪。。。。。。。。。。我清空缓存试过很多次，

**Comment by EvanDbg** [comment]
[聊天历史为空]调用了如下请求
/api/chatrooms

[聊天历史正常]调用了如下请求
/api/chatrooms
/api/chat-hisroty?roomId=1682040885518&lastId=undefined

**Comment by EvanDbg** [comment]
看了下动画

1. 正常情况下 room list 先刷新完成，然后chat content区域刷新，历史记录正常显示
2. 问题情况下 chat content区域先刷新完成，room list再刷新，显示出来的历史记录会变成空白

**Comment by huangwb8** [comment]
@Kerwin1202  

在最近的[v2.12.6](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.12.6)中，聊天记录加载异常再次出现。 表现为访问网站时当前聊天为空，要手动刷新一下才显示历史聊天记录。
