### ISSUE TITLE
docker自己打包报错

### ISSUE THREAD

**Issue by 02000823** [Kerwin1202/chatgpt-web#403]
#0 131.6  ETIMEDOUT  request to https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz failed, reason: 
#0 131.6 
#0 131.6 FetchError: request to https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz failed, reason: 
#0 131.6     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:73746:18)
#0 131.6     at ClientRequest.emit (node:events:514:28)
#0 131.6     at TLSSocket.socketErrorListener (node:_http_client:495:9)
#0 131.6     at TLSSocket.emit (node:events:526:35)
#0 131.6     at emitErrorNT (node:internal/streams/destroy:151:8)
#0 131.6     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
#0 131.6     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
------
Dockerfile:46
--------------------
  44 |     COPY /service/pnpm-lock.yaml /app
  45 |     
  46 | >>> RUN pnpm install --production && rm -rf /root/.npm /root/.pnpm-store /usr/local/share/.cache /tmp/*
  47 |     
  48 |     COPY /service /app
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm install --production && rm -rf /root/.npm /root/.pnpm-store /usr/local/share/.cache /tmp/*" did not complete successfully: exit code: 1

**Comment by Kerwin1202** [comment]
用代理吧，或者换个镜像源 再或者 更新下 pnpm ，我前几天 pnpm 也不行，更新了下就好了

**Comment by 02000823** [comment]
好的
