### ISSUE TITLE
登陆注册按钮在移动端隐藏太深

### ISSUE THREAD

**Issue by Fugitive844** [Kerwin1202/chatgpt-web#41]
1、登陆注册按钮在移动端隐藏太深，需要自己展开左侧折叠栏才看到，会导致不熟悉的用户找不到登陆和注册按钮。 
2、另外，重置密码的邮件链接点进去后是否能考虑直接打开输入框让用户输入新密码。

**Comment by Kerwin1202** [comment]
1. 你有什么建议呢  或者还是手机端直接打开弹窗?  电脑端不会改 可以看另一个issue有解释
2.  现在就是这样的把

**Comment by Fugitive844** [comment]
移动端检测未登录可以考虑直接打开弹窗，这样应该好一些。  只是建议了，我对前端不熟，想自己动手改下再部署搞不定，哈哈哈哈哈

**Comment by huangwb8** [comment]
@Fugitive844  其实还好啦，用户探索一下就行。 这种习惯是众口难调的。 保证关键功能要紧，这种可以放到稍次的位置考虑。 感谢 @Kerwin1202  大佬 (ฅ´ω`ฅ)

**Comment by luckywangxi** [comment]
![image](https://user-images.githubusercontent.com/112324550/232953139-337a9853-5db2-4ceb-a697-8684512ebdc5.png)
![image](https://user-images.githubusercontent.com/112324550/232953183-53f8bec9-88ac-4e41-9109-2e35856483bd.png)
我个人是把登录按钮调到了UI中间，原来的描述那些还原
