### ISSUE TITLE
[BUG] PWA模式下， IOS系统在暗黑模式下UI有错误

### ISSUE THREAD

**Issue by liuchao0807** [Kerwin1202/chatgpt-web#410]
#  如图所示，在暗黑模式下，状态栏部分还是白色，不太和谐
## 暗黑模式
![IMG_5376](https://github.com/Kerwin1202/chatgpt-web/assets/22492920/90f6ae76-3c0c-4a75-aa51-212999f42431)

# 其他项目，例如ChatGPT-Next-Web，可以很好的自适应
## 亮色模式
![IMG_5381](https://github.com/Kerwin1202/chatgpt-web/assets/22492920/92e5911f-a786-49ee-9a3a-e38861ef10a9)
##  暗黑模式
![IMG_5380](https://github.com/Kerwin1202/chatgpt-web/assets/22492920/2337cb8c-18a6-4de7-a9ce-d91bcbcdc168)

**Comment by BobDu** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/20370175/3464b1b2-8ad7-4bab-9c5f-71242793f512)
![image](https://github.com/Kerwin1202/chatgpt-web/assets/20370175/c1b81885-704d-4b49-b238-a9894bc42e66)
我在ios的safari上没能复现出来这个问题

**Comment by BobDu** [comment]
查询了一下相关的资料。
状态栏的颜色应该是通过
```
<meta name="theme-color" content="#319197">
```
这样子来设置的。

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
看起来 `theme-color` 的浏览器兼容性本来就不是很好。所以在有些环境下不生效其实也很能理解

但很奇怪的就是报告中描述的 ChatGPT-Next-Web 它在相同的设备环境下能做到修改状态栏颜色
@liuchao0807 你是在同一个设备环境下测试对比的吗?  它怎么做到的呢 真很奇怪了。

https://css-tricks.com/meta-theme-color-and-trickery/
我参考这个资料中提到的一个示例网站
https://mxb.dev/
测了一下各种情况下的兼容性
@liuchao0807 你也可以设置打开这个网址看下表现把你设备上的现象分享一下哈。🌹

发现在我的ios上  safari 能改状态栏颜色 chrome不行
和现在的 chatgpt-web 修改主题后的表现是一致的

**Comment by liuchao0807** [comment]
@BobDu 
我的设备是 iPhone 15 Pro Max，系统是 iOS 17.2.1
另外一点，我在 Safari 也没问题，是把网页“添加到主屏幕”，然后从桌面打开才能触发这个问题
