### ISSUE TITLE
BUG：授权admin后收回导致进程直接退出

### ISSUE THREAD

**Issue by Fugitive844** [Kerwin1202/chatgpt-web#411]
发现一个BUG，因为是在docker跑的，在公司不方便调试，先提Issues吧。
当预先给账号A授予Admin权限之后，A账号正常登陆使用过程中，Admin权限突然被收回，这时候如果A调用了管理员相关接口的话就导致整个进程异常退出。
![image](https://github.com/Kerwin1202/chatgpt-web/assets/44861876/f742f7b1-0b7c-45e9-9e17-08ba9523723c)

**Comment by BobDu** [comment]
具体调用了哪个接口啊?  我试了一下。调用 `用户管理` `keys管理` 的接口。都没有发现进程会异常退出。只是前端没渲染这个错误信息。但是看chrome dev tools network里面看接口是正常返回了
```
{"status":"Fail","message":"无权限 | No permission.","data":null}
```

@Fugitive844

**Comment by Fugitive844** [comment]
用户管理和key管理列表都会
