### ISSUE TITLE
新用户注册审核开启后，没有看到审核界面

### ISSUE THREAD

**Issue by SiMPlerMeta** [Kerwin1202/chatgpt-web#43]
新用户注册之后无法登录

**Comment by huangwb8** [comment]
目前信息太少，不好判断。 

+ 可否提供你安装本项目的方式和代码？ 

+ 可否提供一些基本设置的图片， 特别是`网站配置`？

+ 如果你使用docker安装，可否提供一下该命令的输出结果以判断image版本？

```bash
# 或者 docker inspect kerwin1202/chatgpt-web:latest
docker inspect kerwin1202/chatgpt-web
```

**Comment by Lizh6** [comment]
这个的审核，是给管理员邮箱发个邮件，手动开通，暂时没有用户管理界面

**Comment by SiMPlerMeta** [comment]
> 

找到了，确实是在管理员邮箱里面的，需要管理员点一下验证链接，非常感谢
