### ISSUE TITLE
能否增加429失败重试的机制

### ISSUE THREAD

**Issue by huangjiexin** [Kerwin1202/chatgpt-web#46]
貌似现在api只允许1分钟调用3次，可以增加失败重试机制？或者多Key轮训的机制？感谢

**Comment by huangwb8** [comment]
@huangjiexin 

1分钟3次？不至于吧！

请问您是否已经绑定openai的payment methods?

**Comment by huangjiexin** [comment]
> @huangjiexin
> 
> 1分钟3次？不过于吧！
> 
> 请询问您是否已绑定openai的付款方式？

没有绑定，所以会有限制

**Comment by huangwb8** [comment]
@huangjiexin  我个人建议使用access token的方式，自建反向代理。 具体见： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by huangjiexin** [comment]
> 。

感谢～

**Comment by Kerwin1202** [comment]
会考虑  还会考虑 多 api key轮询

**Comment by huangjiexin** [comment]
> 会考虑 还会考虑 多 api key轮询

感谢！

**Comment by Kerwin1202** [comment]
api key轮询 加了，，多个 key 的情况 429 就少了 关了
