### ISSUE TITLE
用mongoDB跑不起来

### ISSUE THREAD

**Issue by sleikang** [Kerwin1202/chatgpt-web#47]
一开始显示mongoDB显示不支持AVX指令集 （WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!），
后面降级到mongoDB4.4后可以运行了但是还是连不上数据库
![image](https://user-images.githubusercontent.com/23020770/232954405-75301038-66c1-4946-8c6b-30545f358b40.png)
![image](https://user-images.githubusercontent.com/23020770/232954453-30a6c327-b11b-4cc5-9dc4-c05289b6ec35.png)
感觉数据库直接用sqlite就行了，并不需要多高的性能

**Comment by zhujunsan** [comment]
你如果想求助 MongoDB 运行的问题，可以直接问（而且我觉得这个问题更适合在 MongoDB 社区提问，毕竟这个问题与当前项目并没有很大关联）。

如果你想问 mongo js 依赖库是否可以连接低版本的 MongoDB 数据库，可以查看依赖库的[说明](https://www.npmjs.com/package/mongodb/v/5.1.0)，并且用其他工具连接数据库以确定不是数据库或者连接信息（地址端口帐号密码等）的问题。

如果你觉得技术选型有问题，应该使用 SQLite。那代码都是开源的，你大可以自己改。

**Comment by huangwb8** [comment]
@sleikang  

我使用的是mongo:3.6。在可视化方面，我选择的是Mongo Express。 详见我的博客文章： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

之所以选择这个比较旧的版本，是因为我以前就有其它docker应用使用mongoDB，这样做可以节省镜像占用的空间。 新版本的mongoDB我倒是没有尝试过。

希望对您有帮助喔！
