### ISSUE TITLE
昨晚更新后，移动端iOS Safari浏览器登录完成后，登录框不能自动消失，需要手动刷新

### ISSUE THREAD

**Issue by wejudging** [Kerwin1202/chatgpt-web#48]
昨晚更新后，今天发现移动端iOS Safari浏览器登录完成后，登录框不能自动消失，需要手动刷新

**Comment by wejudging** [comment]
系统iOS16.4.1 设备iPhone 13 Pro

**Comment by huangwb8** [comment]
@wejudging  

该bug并非来自昨晚的更新，应该是更早时候。 只不过我比较少在移动端使用，所以没有反馈这个bug。

确实值得关注 @Kerwin1202
