### ISSUE TITLE
我本地启动，发送消息一直提示超时

### ISSUE THREAD

**Issue by 123Jason-cn** [Kerwin1202/chatgpt-web#51]
我在本地搭建的测试环境，一直提示超时。我VPN开着的，是怎么回事
<img width="631" alt="image" src="https://user-images.githubusercontent.com/75602210/233040997-8f1df7c0-e913-4f63-881a-c89ae5b96947.png">

**Comment by Fugitive844** [comment]
很多梯子只代理浏览器流量，你可以在国外服务器用nginx弄个简单的反向代理就行了

**Comment by 123Jason-cn** [comment]
> 很多梯子只代理浏览器流量，你可以在国外服务器用nginx弄个简单的反向代理就行了

谢谢大佬。已经可以了，设置下http代理，指向我的VPN接口就行了
