### ISSUE TITLE
删除对话后数据还在数据库里

### ISSUE THREAD

**Issue by a137235** [Kerwin1202/chatgpt-web#54]
用户删除了对话，数据还会继续存在，长期下来数据遭不住

**Comment by Fugitive844** [comment]
应该是故意的吧，我觉得这种彻底删除不能让用户主动做，便于你后台审核一些东西，比如统计分析。敏感话题追责

**Comment by zhujunsan** [comment]
有标记，遭不住可以写个cron脚本批量删鸭

**Comment by LanQian528** [comment]
```
db.chat.deleteMany({status: 1});
db.chat_room.deleteMany({status: 1});
```
可以在数据库使用这两行代码删除所有冗余数据

**Comment by LanQian528** [comment]
> 故意的

感觉可以在管理员设置里面增加一个一键删除冗余数据的按钮。
可以使用以下两行语句
```
db.chat.deleteMany({status: 1});
db.chat_room.deleteMany({status: 1});
```

**Comment by Kerwin1202** [comment]
1000 条才 1M 1000w 也 10G  删的问题就不考虑

<img width="1087" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/6f9e7b43-0e54-4746-8958-95df5365c313">
