### ISSUE TITLE
啊我看到登录注册了，挺好，你能加我微嘛？

### ISSUE THREAD

**Issue by wengxiaoning** [Kerwin1202/chatgpt-web#55]

**Comment by wengxiaoning** [comment]
我看一下页面

**Comment by huangwb8** [comment]
@wengxiaoning 

你是使用本项目的过程中有什么疑问吗？ 没看懂你的意思

**Comment by wengxiaoning** [comment]
你有跑起来的地址嘛，我看看哈哈哈。

**Comment by huangwb8** [comment]
@wengxiaoning 

你直接去这里看呀，上面有gif示例： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by ywgx** [comment]
https://intio.org 做了小调整, 注册/忘记密码合一, 而且注册流程做了调整, 邮件激活之后才开始创建真实用户

**Comment by wengxiaoning** [comment]
@ywgx   后能能添加用户嘛

**Comment by wengxiaoning** [comment]
@ywgx   后台能添加用户嘛？

**Comment by ywgx** [comment]
@wengxiaoning  后台添加用户是什么场景? 注册就行了

后台管理就是直接操作 mongo 就行

**Comment by Kerwin1202** [comment]
> @ywgx 后台能添加用户嘛？

暂时不支持

**Comment by haihaimx** [comment]
> https://intio.org 做了小调整, 注册/忘记密码合一, 而且注册流程做了调整, 邮件激活之后才开始创建真实用户

大佬可以分享一下吗
