### ISSUE TITLE
用nginx反向代理问题

### ISSUE THREAD

**Issue by opsxff** [Kerwin1202/chatgpt-web#58]
我用的https://xxx:443/chatgpt-web反向代理到localhost:3002，但是访问后会让浏览器申请请求https://xxx:443/assets/而不是https://xxx:443/chatgpt-web/assets/，有没有什么办法能解决呢

**Comment by zhujunsan** [comment]
是否能贴例如详细的Nginx配置上来呢？

**Comment by opsxff** [comment]
> 是否能贴例如详细的Nginx配置上来呢？

        location /chatgpt-web {
            proxy_pass http://172.30.0.7:3002/;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering off;
        }
就这样的，172.30.0.7是chatgpt-web容器

**Comment by zhujunsan** [comment]
第一行试试
`location /chatgpt-web/ {`

**Comment by opsxff** [comment]
> 第一行试试 `location /chatgpt-web/ {`

这个斜杠我加了，不过它这个还没有到反向代理那，它让浏览器请求访问的https://xxx:443/assets/...没有进入到chatgpt-web这个location。我问chatgpt它说是代码返回的url有问题

**Comment by zhujunsan** [comment]
第二行3002后面的斜杠去掉呢？

**Comment by zhujunsan** [comment]
查下Nginx反向代理的写法就好了

**Comment by opsxff** [comment]
还有没有其他办法。这个第一个请求都是成功的，所以不是反向代理路径的问题(之前我就都试过)，是返给浏览器发起的请求没加我的location
![image](https://user-images.githubusercontent.com/62395080/233797160-42d3bff2-f05d-4ef0-b9ad-6197b4d760cd.png)

**Comment by hicaoc** [comment]
这种情况，一般要rewrite下请求的路径，或者后端web要支持部署到chat-web目录，否则后端是将自己的资源路径直接返回给nginx，然后到用户

**Comment by zhujunsan** [comment]
嗯...express 是基于根目录绑定路径的...

如果你要部署的话，需要修改 `service\src\index.ts` 的 L703-704，把 '' 和 '/api' 改成比如 '/chatgpt-web' 和 '/chatgpt-web/api'，然后打包，部署

**Comment by opsxff** [comment]
感谢，我研究下

**Comment by xiechenghua01** [comment]
> 还有其他办法。这个第一个请求都是成功的，所以不是反向代理路径的问题（之前我都试过），是返回给浏览器发起的请求没有加我的位置 ![图像](https://user-images.githubusercontent.com/62395080/233797160-42d3bff2-f05d-4ef0-b9ad-6197b4d760cd.png)


静态文件也需要反向代理，这样可以解决css文件和js文件访问404的问题。

<img width="795" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/110524397/c635c99a-df3b-46cb-b8cf-5b3c738cccd7">

**Comment by opsxff** [comment]
> 

谢谢你，我后头还是选择加了条解析单独代理，懒得弄了
