### ISSUE TITLE
本地部署的时候，配置页面点击保存，一直显示加载中，重启docker也还是这样

### ISSUE THREAD

**Issue by git-gao** [Kerwin1202/chatgpt-web#59]
![image](https://user-images.githubusercontent.com/37399419/233759747-acd4a1d4-6ab5-46d4-92dd-04edad4787d1.png)

**Comment by Kerwin1202** [comment]
什么都没改吗 还是修改了保存  以及你 可以f12 看下控制台有没有报错之类的

**Comment by git-gao** [comment]
问题的出现是这样的，初始给了一个无效的API key，想登陆后再修改，然后去修改key，点击保存就会这样，因为是本地保存，没梯子，可能去查询官网了，网络不通，然后就一直加载中，重启docker 也一样。
目前解决了，我是从后台删除掉chatgpt 的 config ，再重启 docker 就不会再加载了。正如上面说的，如果网络不通，就会一直加载中，导致无法修改配置

**Comment by Kerwin1202** [comment]
那问题不大，加载不出余额，卡主了 也就无法聊天，只能你自己看看网络优化下了
