### ISSUE TITLE
这个项目用的什么数据库？mongodb吗？

### ISSUE THREAD

**Issue by shiliu2023** [Kerwin1202/chatgpt-web#60]

**Comment by huangwb8** [comment]
@shiliu2023  

是的，该项目使用mongodb作为后端。 

我写过一个详细教程介绍这个项目的安装和使用。 感兴趣可以瞄一吓 (ฅ´ω`ฅ) ： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)
