### ISSUE TITLE
数据库写死最高版本，以致硬件要求过高 无法使用

### ISSUE THREAD

**Issue by LB-DotFish** [Kerwin1202/chatgpt-web#65]
大佬   有一些疑问，这个项目是不是写死 mongo5了？
这个项目没有内置数据库，所以要分别进行部署吧，这样的话  是不是没必要版本限制这么严格？

我目前使用的群晖的920+，docker安装mongo 数据库，有以下报错：
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
作为普通的个人用户，是不是对硬件要求过高了。

更换mongo4 数据库后，虽然数据库能正常运行，但是这个项目又有报错
/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/lib/sdam/topology.js:277
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
MongoServerSelectionError: getaddrinfo ENOTFOUND database
    at Timeout._onTimeout (/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/lib/sdam/topology.js:277:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  reason: TopologyDescription {

看报错信息好像是要mongo5 数据库。

关于数据库这个问题  能否做些兼容处理。我觉得我这个配置还是比较大众的。

**Comment by zhujunsan** [comment]
![image](https://user-images.githubusercontent.com/839807/233890217-eb454ebb-e29f-442e-9bb8-9c0d79cab7e6.png)

https://www.mongodb.com/docs/drivers/node/current/compatibility/#mongodb-compatibility

官方 npm 库的说明是，这个 lib 支持最低到 MongoDB 3.6

**Comment by huangwb8** [comment]
@LB-DotFish 

我用的就是MongoDB 3.6。 具体见我的教程： [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by Kerwin1202** [comment]
看提示可以看看 url 格式是否ok 怀疑是 版本不对，url格式旧版本之类不支持 猜测 倒没试过
