### ISSUE TITLE
新用户审核前端有可视化界面吗,还是直接操作数据库

### ISSUE THREAD

**Issue by zxczhai** [Kerwin1202/chatgpt-web#68]
新用户审核打开后提示管理员审核,但是管理员界面看不到通过审核的地方,想问一下是目前没有,要操作数据库还是审核界面我没有找到

**Comment by qsc19971022** [comment]
这个你咋审核的呀

**Comment by zxczhai** [comment]
管理员邮箱会有一封确认邮件

woftsun ***@***.***> 于 2023年4月27日周四 23:42写道：
