### ISSUE TITLE
关于 accessToken 的一些问题

### ISSUE THREAD

**Issue by huoshicang** [Kerwin1202/chatgpt-web#69]
![Screenshot_2023-04-24-23-11-14-51_32cba261fc08a501ce70de75bdbe2575](https://user-images.githubusercontent.com/74391377/234044720-eb73706a-d7f5-4e78-8b71-6337db7fc8f0.jpg)
出现如图所示的问题是不是因为我使用了 accessToken，本人和用户同时使用，请求太快。如果我使用 key 并且添加 HTTP 代理就不会出现这个问题，
另外，回答不完整应该怎么解决
![Screenshot_2023-04-24-23-13-01-00_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/74391377/234045768-abcf9043-431d-47e4-956f-8acc33875321.jpg)

**Comment by huoshicang** [comment]
另外还有用户消息的时间，虽然我理解是什么意思，但是看着有点不太舒服😂关于这个问题影响不大

**Comment by Kerwin1202** [comment]
1. 429 多个人说话 提示的很明确了 就是段时间有人发 accesstoken 和 api有区别 api有时候快些 够频繁也会的
2. 时间改了
3. 消息断了 可以自己打开chat.openai.com 看看，可以自己输入【继续】让他写   以前代码还有个配置让他继续 但是好像无效 我试了官网也断
