### ISSUE TITLE
关于使用CDN会导致聊天室串号

### ISSUE THREAD

**Issue by LanQian528** [Kerwin1202/chatgpt-web#71]
![image](https://user-images.githubusercontent.com/5499636/234263575-a045dd36-a385-4d45-ada2-6f3b6602027c.png)
希望能在chatroom、chathistory、chat的部分加上no-cache的请求头

**Comment by zhujunsan** [comment]
这是不是应该在CDN那边配置不缓存的路径...

**Comment by zhujunsan** [comment]
你用的是哪家的 CDN 呢？应该直接把 `/api/*` 的路径设置成不缓存就可以了

**Comment by LanQian528** [comment]
> 

我使用的腾讯云CDN，好像只能按照文件路径配置缓存。如果我这样写可以吗
![image](https://user-images.githubusercontent.com/5499636/234288634-c62cd144-d488-4875-b945-52af99c4e7b8.png)

**Comment by zhujunsan** [comment]
我也没用过腾讯云的CDN，只能说，看文档+试试看 😝

**Comment by Kerwin1202** [comment]
看上去有的 确实这种要配置cdn 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/16319833/234293569-7fad2536-3ae6-44e6-b173-99b1d0b9fb6d.png">

**Comment by LanQian528** [comment]
> 看上去有的 确实这种要配置cdn <img alt="image" width="405" src="https://user-images.githubusercontent.com/16319833/234293569-7fad2536-3ae6-44e6-b173-99b1d0b9fb6d.png">

好的，感谢两位大佬
