### ISSUE TITLE
注册账号时‘点我验证’按钮无效

### ISSUE THREAD

**Issue by CLemonC** [Kerwin1202/chatgpt-web#72]
docker搭建，配置文件中也设置了域名，能收到邮件但是邮件中‘点我验证’无效

**Comment by Kerwin1202** [comment]
这要具体看下了，如果是浏览器打开的 数标放上去看左下角连接有没有之类的

**Comment by CLemonC** [comment]
> 这要具体看下了，如果是浏览器打开的 数标放上去看左下角连接有没有之类的

对的，目前的情况是F12看了下根本没有指向链接，感到很疑惑
![image](https://user-images.githubusercontent.com/90757951/234295328-8c3bb2c1-a00f-45e6-ae1d-dbe7cdadc8b1.png)

**Comment by Kerwin1202** [comment]
看怎么部署的  看下 模板文件格式是否正确

<img width="936" alt="image" src="https://user-images.githubusercontent.com/16319833/234299631-c3e69fb6-bd0b-44e9-825a-ae9063c886bc.png">

**Comment by CLemonC** [comment]
> 看怎么部署的 看下 模板文件格式是否正确
> 
> <img alt="image" width="936" src="https://user-images.githubusercontent.com/16319833/234299631-c3e69fb6-bd0b-44e9-825a-ae9063c886bc.png">

非常感谢您及时的回复，这是我配置的截图，劳烦您看下，感谢
![image](https://user-images.githubusercontent.com/90757951/234300890-0e74e43a-407c-4aab-8e06-a6e33b257e4f.png)

**Comment by Kerwin1202** [comment]
配置没问题，确实奇怪没看出来，958686489@qq.com 这是我的邮箱 你把域名发我 我测试下

**Comment by Kerwin1202** [comment]
看了下没看出来，如果是 docker 跑 得进去看看 里面的 html 还对不对

**Comment by CLemonC** [comment]
> 看

好的，请问下注册邮件的样板是放在哪个目录的哪个文件中呢

**Comment by Kerwin1202** [comment]
```
docker exec -it 你的容器 sh
cd /app/src/utils/templates 
```

**Comment by CLemonC** [comment]
> ```
> docker exec -it 你的容器 sh
> cd /app/src/utils/templates 
> ```

这是mail.notice.template.html位置的代码样式，看上去是正常的
![image](https://user-images.githubusercontent.com/90757951/234446865-aa87310d-efcd-46bc-9e65-028b37859627.png)

**Comment by CLemonC** [comment]
> ```
> docker exec -it 你的容器 sh
> cd /app/src/utils/templates 
> ```

好消息，我已经解决了问题，貌似直接通过docker-compose down后修改docker-compose.yml并没有真正应用到配置里，最开始我临时使用了一个错误的域名，然后down后进行更改再重启，这使得容器内部并没有重新读取到更改后的真实域名，刚刚在全部删除后重新部署直接填入了正确的域名，再次启动即可正常使用，感谢您的无私贡献及及时的回复与问题解决:)
