### ISSUE TITLE
Bug: 使用Access Token时对话自定义Prompt不生效

### ISSUE THREAD

**Issue by huangwb8** [Kerwin1202/chatgpt-web#73]
如题， 使用Access Token时对话自定义Prompt不生效。 API是正常的。 

不知后面是否可以跟进 (ฅ´ω`ฅ)

**Comment by zhujunsan** [comment]
access token 我记得不能自定义 system prompt 的吧？这个似乎是 ChatGPT 定死的

**Comment by huangwb8** [comment]
@zhujunsan 

这样啊，谢谢提醒哈！
