### ISSUE TITLE
建议 再次打开会话的时候定位到会话底部，目前是定位到最上面的

### ISSUE THREAD

**Issue by xiaoguaishou92** [Kerwin1202/chatgpt-web#74]

**Comment by luckywangxi** [comment]
加一，刚想报告这个BUG，我的是在本地一切正常，滚动到底部，但是上传到服务器就G了，每次刷新都会到顶部，只有新建会话，然后再点回去才是底部
![QQ录屏20230426105122](https://user-images.githubusercontent.com/112324550/234455723-ce57c872-2bd3-4198-ba0d-4568c1732854.gif)

**Comment by Travisss** [comment]
加1

**Comment by EvanDbg** [comment]
这个Bug很诡异，本地没有问题。用Kerwin1202的chatgpt-web镜像就会出现这个问题。

**Comment by luckywangxi** [comment]
> 这个Bug很诡异，本地没有问题。用Kerwin1202的chatgpt-web镜像就会出现这个问题。

是的，啊哈哈哈哈，我还以为是我游览器缓存没清，还特意无痕模式，啊哈哈哈，在本地没问题，上传到服务器就会有这个BUG

**Comment by luckywangxi** [comment]
> > 这个Bug很诡异，本地没有问题。用Kerwin1202的chatgpt-web镜像就会出现这个问题。
> 
> 是的，啊哈哈哈哈，我还以为是我游览器缓存没清，还特意无痕模式，啊哈哈哈，在本地没问题，上传到服务器就会有这个BUG

@Kerwin1202 大佬可以解决吗😎😎😎🙌

**Comment by Travisss** [comment]
> > 这个Bug很奇怪，本地没有问题。使用Kerwin1202的chatgpt-web镜像就会出现这个问题。
> 
> 是的，啊哈哈哈，我还以为是我浏览器没有清，还特意无痕模式，啊哈哈，在本地没有问题，上传到服务器就会有这个BUG

额，本地和上传到服务器是什么意思？

**Comment by luckywangxi** [comment]
> > > 这个Bug很奇怪，本地没有问题。使用Kerwin1202的chatgpt-web镜像就会出现这个问题。
> > 
> > 
> > 是的，啊哈哈哈，我还以为是我浏览器没有清，还特意无痕模式，啊哈哈，在本地没有问题，上传到服务器就会有这个BUG
> 
> 额，本地和上传到服务器是什么意思？

本地编译啊，服务器就是docker pull到服务器
