### ISSUE TITLE
基本配置无法保存

### ISSUE THREAD

**Issue by Fugitive844** [Kerwin1202/chatgpt-web#79]
![image](https://user-images.githubusercontent.com/44861876/234639418-bafdc648-a541-4834-abb7-f0851381178b.png)

如图，当调用/setting-base保存基本配置时，如果没有填写accessToken，不管接口类型选什么都会抛出异常，原因是else if (!isNotEmptyString(accessToken))永远成立。
1、如果接口类型是ChatGPTUnofficialProxyAPI时，未填写进入throw new Error('Missing OPENAI_ACCESS_TOKEN environment variable.')合理。
2、但是如果apiModel === 'ChatGPTAPI'时，就算填写了apiKey，下面的else if (!isNotEmptyString(accessToken))永远成立。

**Comment by zhujunsan** [comment]
可下面的，是 else if 呀，得选了API外加没写api key 才会走到下面诶

**Comment by Fugitive844** [comment]
> 可下面的，是 else if 呀，得选了API外加没写api key 才会走到下面诶

你再看看，选了api时第一个表达式为true，填了apikei时isNotEmptyString(apikey)=true，前面加了感叹号就是false，所以第一行if整体为false，所以会走到else if。
再说，第一行整体是true就会抛出apikey空，  如果第一行整体为fasle，就会走到else if，而当accessToken没有填写过则accessToken恒为空

**Comment by zuozihan** [comment]
Error: OpenAI missing required apiKey 为啥报错这个

**Comment by zhujunsan** [comment]
> > 可下面的，是 else if 呀，得选了API外加没写api key 才会走到下面诶
> 
> 你再看看，选了api时第一个表达式为true，填了apikei时isNotEmptyString(apikey)=true，前面加了感叹号就是false，所以第一行if整体为false，所以会走到else if。 再说，第一行整体是true就会抛出apikey空， 如果第一行整体为fasle，就会走到else if，而当accessToken没有填写过则accessToken恒为空

哦噗哈哈，逻辑太绕了。提个pr呗~~

**Comment by Kerwin1202** [comment]
> Error: OpenAI missing required apiKey

要看配置 是刚部署之后  还是页面保存下之类情况

**Comment by Fugitive844** [comment]
> > Error: OpenAI missing required apiKey
> 
> 要看配置 是刚部署之后 还是页面保存下之类情况

就是在页面点保存按钮，然后页面没有把accessToken提交上去，只要点保存按钮且前端没有传入accessToken，那个地方的逻辑判断百分百会抛异常。

**Comment by Kerwin1202** [comment]
> > > Error: OpenAI missing required apiKey
> > 
> > 
> > 要看配置 是刚部署之后 还是页面保存下之类情况
> 
> 就是在页面点保存按钮，然后页面没有把accessToken提交上去，只要点保存按钮且前端没有传入accessToken，那个地方的逻辑判断百分百会抛异常。

可能就这个issue的问题 你自己部署的画 pull 下再试试看 我目前试了正常的
