### ISSUE TITLE
mongo数据库一直连接出错，提示用户名或者密码错误

### ISSUE THREAD

**Issue by hbytw** [Kerwin1202/chatgpt-web#84]
{"t":{"$date":"2023-04-27T12:07:20.893+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn182","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"chatgpt","authenticationDatabase":"admin","remote":"172.19.0.4:59638","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
{"t":{"$date":"2023-04-27T12:07:20.895+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn182","msg":"Connection ended","attr":{"remote":"172.19.0.4:59638","uuid":"a8820e01-a3d6-4b84-be1a-771368804807","connectionId":182,"connectionCount":0}}
{"t":{"$date":"2023-04-27T12:07:21.396+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.4:59642","uuid":"b6d3006f-ccaf-477e-8c31-076156146bc5","connectionId":183,"connectionCount":1}}
{"t":{"$date":"2023-04-27T12:07:21.397+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn183","msg":"client metadata","attr":{"remote":"172.19.0.4:59642","client":"conn183","doc":{"driver":{"name":"nodejs","version":"3.4.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.18.0-425.19.2.el8_7.x86_64"},"platform":"'Node.js v12.18.3, LE (unified)"}}}
{"t":{"$date":"2023-04-27T12:07:21.399+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn183","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"chatgpt","authenticationDatabase":"admin","remote":"172.19.0.4:59642","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
{"t":{"$date":"2023-04-27T12:07:21.400+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn183","msg":"Connection ended","attr":{"remote":"172.19.0.4:59642","uuid":"b6d3006f-ccaf-477e-8c31-076156146bc5","connectionId":183,"connectionCount":0}}
{"t":{"$date":"2023-04-27T12:07:21.903+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.4:59658","uuid":"15210643-0488-4dac-b492-2fa8fe28eb9f","connectionId":184,"connectionCount":1}}
{"t":{"$date":"2023-04-27T12:07:21.904+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn184","msg":"client metadata","attr":{"remote":"172.19.0.4:59658","client":"conn184","doc":{"driver":{"name":"nodejs","version":"3.4.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.18.0-425.19.2.el8_7.x86_64"},"platform":"'Node.js v12.18.3, LE (unified)"}}}
{"t":{"$date":"2023-04-27T12:07:21.906+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn184","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"chatgpt","authenticationDatabase":"admin","remote":"172.19.0.4:59658","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
{"t":{"$date":"2023-04-27T12:07:21.907+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn184","msg":"Connection ended","attr":{"remote":"172.19.0.4:59658","uuid":"15210643-0488-4dac-b492-2fa8fe28eb9f","connectionId":184,"connectionCount":0}}
{"t":{"$date":"2023-04-27T12:07:22.410+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.4:43206","uuid":"97893e28-c291-48e5-b541-2afc8407cb6d","connectionId":185,"connectionCount":1}}
{"t":{"$date":"2023-04-27T12:07:22.410+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn185","msg":"client metadata","attr":{"remote":"172.19.0.4:43206","client":"conn185","doc":{"driver":{"name":"nodejs","version":"3.4.1"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.18.0-425.19.2.el8_7.x86_64"},"platform":"'Node.js v12.18.3, LE (unified)"}}}
{"t":{"$date":"2023-04-27T12:07:22.414+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn185","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"chatgpt","authenticationDatabase":"admin","remote":"172.19.0.4:43206","extraInfo":{},"error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"}}
{"t":{"$date":"2023-04-27T12:07:22.415+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn185","msg":"Connection ended","attr":{"remote":"172.19.0.4:43206","uuid":"97893e28-c291-48e5-b541-2afc8407cb6d","connectionId":185,"connectionCount":0}}

**Comment by Kerwin1202** [comment]
这个就只能自己检查下帐号密码了。我也没啥办法，，毕竟我也不知道你帐号密码 你也不能共享出来测试。。

**Comment by hbytw** [comment]
我重新按默认设置在安装一遍试试吧

**Comment by huangwb8** [comment]
@hbytw 

我写过比较详细的教程，其中有讲docker-compose.yml文件的帐号/密码的相关细节。 感兴趣可以瞄一下：  [Docker系列 基于OpenAI API和Access Token自建ChatGPT](https://blognas.hwb0307.com/linux/docker/4201)

**Comment by hbytw** [comment]
database:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxx
      MONGO_INITDB_DATABASE: chatgpt

  mongo-gui:
    container_name: mongo-gui
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - '4321:4321'
    environment:
      - MONGO_URL=mongodb://chatgpt:xxxx@database:27017
    links:
      - database
    depends_on:
      - database
默认都没改还是连不上，centos7系统

**Comment by Kerwin1202** [comment]
```
- mongodb:/data/db
```

从这个看 `mongodb`  应该有一个 volum 没数据的话 你把这个删掉然后再运行

**Comment by lszhwxa** [comment]
我也遇到这个问题，应该是数据库映射错了吧，默认是
volumes:
      - mongodb:/data/db
这里要改成自己mongodb路径，比如我的docker-compose.yml文件位于/root/docker/chapgtp/，就要改成
volumes:
      - /root/docker/chatgpt/mongodb:/data/db
 再试下，我就是这样解决的

**Comment by xiaoguaishou92** [comment]
> @lszhwxa 使用你这个方法 数据库起来了，mongo-gui的4321端口可以访问了，但是nginx访问还是500错误。提示500 Internal Server Error 关于nginx的配置都没有动。都是默认的。

这肯定不对，你那个地方后面那个端口要用8081

**Comment by Kerwin1202** [comment]
> @lszhwxa 使用你这个方法 数据库起来了，mongo-gui的4321端口可以访问了，但是nginx访问还是500错误。提示500 Internal Server Error 关于nginx的配置都没有动。都是默认的。

报错也许要对应的 报错信息看下 docker 跑 有docker的log的

**Comment by renwofei423** [comment]
> database: image: mongo ports: - '27017:27017' expose: - '27017' volumes: - mongodb:/data/db environment: MONGO_INITDB_ROOT_USERNAME: chatgpt MONGO_INITDB_ROOT_PASSWORD: xxxx MONGO_INITDB_DATABASE: chatgpt
> 
> mongo-gui: container_name: mongo-gui image: ugleiton/mongo-gui restart: always ports: - '4321:4321' environment: - MONGO_URL=mongodb://chatgpt:xxxx@database:27017 links: - database depends_on: - database 默认都没改还是连不上，centos7系统

改用Ip试试，不要用database
