### ISSUE TITLE
可以用Railway部署吗

### ISSUE THREAD

**Issue by 1030283726** [Kerwin1202/chatgpt-web#85]
我试过直接用 Repo 部署但是会Crash

**Comment by Kerwin1202** [comment]
我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看

https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml

**Comment by 1030283726** [comment]
> 我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看
> 
> https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml

謝謝！已經部署成功了！

**Comment by zhaobudaomingzi** [comment]
> > 我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看
> > https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml
> 
> 謝謝！已經部署成功了！

请问老哥是怎么部署mongodb的，也是在railway上部署的吗

**Comment by 1030283726** [comment]
> > > 我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看
> > > https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml
> > 
> > 
> > 謝謝！已經部署成功了！
> 
> 请问老哥是怎么部署mongodb的，也是在railway上部署的吗

是的，但要手動設置一下

**Comment by zhaobudaomingzi** [comment]
> > > > 我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看
> > > > https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml
> > > 
> > > 
> > > 謝謝！已經部署成功了！
> > 
> > 请问老哥是怎么部署mongodb的，也是在railway上部署的吗
> 
> 是的，但要手動設置一下
> 
> 

谢谢，已经成功部署了

**Comment by JssDream** [comment]
> > > > > 我没测过 但是应该可以的 readme下面的 `Railway 环境变量` 可能我没更新 有漏的， 所以你以这个为准 所有变量设置一次 ，再试试看
> > > > > https://github.com/Kerwin1202/chatgpt-web/blob/main/docker-compose/docker-compose.yml
> > > > 
> > > > 
> > > > 謝謝！已經部署成功了！
> > > 
> > > 
> > > 请问老哥是怎么部署mongodb的，也是在railway上部署的吗
> > 
> > 
> > 是的，但要手動設置一下
> 
> 谢谢，已经成功部署了

railway上部署，mongodb怎么配置的？需要单独部署嘛？

**Comment by Kerwin1202** [comment]
@JssDream 参考 https://github.com/Kerwin1202/chatgpt-web/issues/266

**Comment by wuwuarandhg** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/98201994/8d14fe3e-d503-40c6-b5cb-c4020990fb23)
请问这个报错如何解决

**Comment by Kerwin1202** [comment]
@wuwuarandhg 没看出，你环境变量都设置了吗，猜测是哪个变量少了

**Comment by wuwuarandhg** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/98201994/145572ea-b8a7-4d0d-af60-02da84c1b544)
我设置了这些，还缺啥

**Comment by Kerwin1202** [comment]
还是没看出 感觉是这个 变量有误  MONGODB_URL  自己确认下value  或者删掉重新加试试看
<img width="1046" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/216c64c0-dab2-4670-b0b8-25ed144cee7a">

**Comment by wuwuarandhg** [comment]
![image](https://github.com/Kerwin1202/chatgpt-web/assets/98201994/c92c0b49-a472-423c-9804-489ea8f692c5)
可以了，这里多个空格，导致变量没有生效，感谢
