### ISSUE TITLE
同一个会话过一段时间不会附带对话历史

### ISSUE THREAD

**Issue by RyzeRise** [Kerwin1202/chatgpt-web#86]
举例：
- 情况1：早上9点问“什么是涌现？”，ChatGPT答“涌现是xxx”。下午3点在同一个对话问“举个例子”，ChatGPT答“请问要举关于什么的例子”。我查看docker logs -f 发现，下午3点的sendMessage的那段JSON里没有附带早上9点的历史对话。
- 情况2：但是在同一时间连续对话时，不会出现情况1的问题，sendMessage打印的信息表明历史对话被正确添加。
- 我没有关闭连续对话功能。

请教：
1. 请问历史对话是如何获取的？根据我的理解，应该是查mongoDB，根据parentMessageId往前回溯获取历史对话。但我在项目里没有找到相关代码。
2. 请问历史对话是如何添加到ChatGPTAPI的请求里的？通过const response = await api.sendMessage这一句的options吗？
3. 上述的情况1和情况2经我检查在请求时都传入了正确的parentMessageId，但最终行为有差异，可能是什么其他因素导致的？
4. 能否查看和更改sendMessage函数的定义？该函数会在docker logs里打印信息，我是否可以进行限制？

**Comment by EvanDbg** [comment]
有没有可能是因为OpenAI那边释放了这个parentMessageId。即便你提出了，他在缓存中没有找到，OpenAI的记忆不够长

**Comment by zhujunsan** [comment]
accessToken 我不知道。
就 API 调用来说，带不带历史会话，是由这个项目的依赖包 `transitive-bullshit/chatgpt-api` 决定的。决定的相关代码在[这里](https://github.com/transitive-bullshit/chatgpt-api/blob/431e6f19895b6c5212cd214cf321b6f2939d61d9/src/chatgpt-api.ts#L361)。可以看出，默认使用的是依赖包里的 LRU 缓存记录的历史会话。如果重启服务会丢失，不会用到 Mongo

**Comment by RyzeRise** [comment]
谢谢zhujunsan的解答，经检查是因为服务重启导致LRU缓存丢失。

**Comment by zhujunsan** [comment]
should be fixed in #113
