### ISSUE TITLE
我自己在服务器上部署了一个llm，可以用自己的服务接口而不用chatgpt的api吗？

### ISSUE THREAD

**Issue by Rogerspy** [Kerwin1202/chatgpt-web#87]
rt

**Comment by huangwb8** [comment]
@Kerwin1202 

本质上，这是关于项目是否支持广义上的大语言模型的提问

有点期待大佬的想法 ヾ(≧∇≦*)ゝ

**Comment by zhujunsan** [comment]
讲道理，部署自己的模型，然后把API入参和返回写成和openai一样的，然后改本项目的上游地址，就可以了。我觉得这个项目的scope不应该无限扩大

**Comment by Kerwin1202** [comment]
确实是，本质上，自己部署的 然后接口 和 openai 现在有的接口请求地址以及格式一致 然后修改这个nginx反代 应该就可以
<img width="808" alt="image" src="https://user-images.githubusercontent.com/16319833/235183773-cde471c1-11fc-402e-94d1-e50917177096.png">
