### ISSUE TITLE
API_KEY和ACCESS_TOKEN二选一，没有配置OPENAI_API_KEY却运行不起来

### ISSUE THREAD

**Issue by lszhwxa** [Kerwin1202/chatgpt-web#88]
这是我的docker-compose.yml配置

---------------------------------------------------------------------------------------------------------------------------------------------------

version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web:latest 
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      #OPENAI_API_KEY: sk-17OfntFdASkdh2tm4nt0ET3BlkFJ11ZuylWtZfnWZd0O7oxo6
      OPENAI_ACCESS_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ3ZWl4aW5nYW5AbGl2ZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXVaCI6eyJ1c2VyX2lkIjoidXNlci02TUlkR1R2VY2YmZLaktpYnpvNkJ1OVIifSwiaXNzIjoiaHR0cHM6Ly9hXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY0MTI5N2ZkODM1ODQzM2VlMTlkNGQ0YSIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2OIyNjI0MTMsImV4cCI6MTY4MzQ3MjAxMywYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.ItF0DItpdXWlDyHxkJ2oW-tb8ivfAH3LOpiYjMUh5nThXDfI_RCsSReaTlBvsos-jHI6VsZsV7o2YbiUu64zfSyPi96ImDrSxYiFe02Afuz0rpI4y9_5o8K3HcpPMdx1UVQpMDtBQt4O_PVCvCls6HS6xJ8pHF9paMpv4ea3RlEtWhCgh8aArHVWc3x64FdxMxr3P0FJdHkIGw4FwbKUaqgdC9auLQ1h6zfRbRmSHtlodmEx4-am1IRU4M-AeiSt29PHDtB29AIFV8_S9bJ5pG1_45N-A0n9EjWVK5G9S1oq41cWIHig0DoW_i7hUvdRxUdCO0BBjCudGKQk0RQ
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: 
      # ChatGPTAPI ChatGPTUnofficialProxyAPI
      OPENAI_API_MODEL: 
      # API模型，可选，设置 OPENAI_API_KEY 时可用，https://platform.openai.com/docs/models
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-002
      OPENAI_CHAT_MODEL: 
      # 反向代理，可选
      API_REVERSE_PROXY: http://90.24.21.19:8080/conversation
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST: 
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT: 
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY: 
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: wwww123
      # 网站名称
      SITE_TITLE: chatgpt
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:wwww123@database:27017'
      # 网站是否开启注册
      REGISTER_ENABLED: 'true'
      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
      REGISTER_MAILS: '@qq.com,@sina.com,@163.com,@gmail.com'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: wwww123
      # 开启注册之后 超级管理邮箱
      ROOT_USER: wwww@gmail.com
      # 开启注册之后 网站域名 不含 / 注册的时候发送验证邮箱使用
      SITE_DOMAIN: http://127.0.0.1:3002
      # 开启注册之后 发送验证邮箱配置
      SMTP_HOST: smtp.exmail.qq.com
      SMTP_PORT: 465
      SMTP_TSL: 'true'
      SMTP_USERNAME: noreply@examile.com
      SMTP_PASSWORD: xxx
      # 是否开启敏感词审核, 因为响应结果是流式 所以暂时没审核
    links:
      - database

  database:
    image: mongo:3.6
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - /root/docker/chatgpt2/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: wwww123
      MONGO_INITDB_DATABASE: chatgpt
 

volumes:
  mongodb:

---------------------------------------------------------------------------------------------------------------------------------------------------

docker-compose up -d后，查看docker logs chatgptweb 日志，发现报错，

> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js

Server is running on port 3002
/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:171
      throw new Error("OpenAI missing required apiKey");
            ^

Error: OpenAI missing required apiKey
    at ChatGPTAPI (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:171:13)
    at initApi (/app/build/index.js:9957:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

---------------------------------------------------------------------------------------------------------------------------------------------------

API_KEY和ACCESS_TOKEN不是二选一吗？为什么缺少API_KEY就是运行不起来呢，然后保留API_KEY再注释掉ACCESS_TOKEN是可以运行起来的，请大佬帮忙解决，谢谢。

**Comment by huangwb8** [comment]
有点小建议 (ฅ´ω`ฅ)

docker-compose.yml应该废弃api和access token相关的参数，而只需要在GUI前端配置就好。 因为这些参数是经常变化的。**docker-compose.yml只放一些不经常变化的参数较好**。

这种思路还有另外一个好处，就是如果以后本项目支持多语言模型的时候，在docker-compose.yml中约定好api或access token的方式将会很不灵活。

**Comment by Kerwin1202** [comment]
因为这个没配置 所以导致 默认走 api 
```
OPENAI_API_MODEL: ChatGPTAPI
```
<img width="684" alt="image" src="https://user-images.githubusercontent.com/16319833/235185504-24e68b15-5503-4952-bda1-060935262894.png">

**Comment by lszhwxa** [comment]
> 因为这个没配置 所以导致 默认走 api
> 
> ```
> OPENAI_API_MODEL: ChatGPTUnofficialProxyAPI
> ```
> 
> <img alt="image" width="684" src="https://user-images.githubusercontent.com/16319833/235185504-24e68b15-5503-4952-bda1-060935262894.png">

原来是这样啊，谢谢大佬
