### ISSUE TITLE
MongoDB 连接自定义数据库名

### ISSUE THREAD

**Issue by jamebal** [Kerwin1202/chatgpt-web#90]
希望MongoDB URL能使用自定义数据库名称：
例如：mongodb://chatgpt:password@database:27017/custom_database

**Comment by Kerwin1202** [comment]
不是不可以考虑哈，但是这个意义是？ 因为要自定义就要加配置 目前配置key已经很多了。。

**Comment by jamebal** [comment]
**1.作用**: 如果一台机器里部署多个`chatgpt-web`,只需要开启一个mongodb服务,不同的`chatgpt-web`使用不同的数据名称
2.如果`MongoDB URL`里面有数据库名就用URL里面的数据库名,没有就使用默认的数据库名
3.对原有配置没有任何影响
