### ISSUE TITLE
部署多个项目时，上下文就丢失了

### ISSUE THREAD

**Issue by lework** [Kerwin1202/chatgpt-web#94]
部署多个项目时，mongodb 用同一个，有时候上下文就丢失了

**Comment by Kerwin1202** [comment]
和这个类似的，上下文不是我控制的，目前来说是更底层的维护，除非自己再另外维护一个api  那样的话可以控制 传入的上下文数据 其实也可以考虑的

https://github.com/Kerwin1202/chatgpt-web/issues/86

**Comment by zhujunsan** [comment]
should be fixed in #113
