### ISSUE TITLE
配置未修改点保存时报错的BUG

### ISSUE THREAD

**Issue by Fugitive844** [Kerwin1202/chatgpt-web#95]
![image](https://user-images.githubusercontent.com/44861876/235173583-ade385e8-5637-4228-a999-a8972fef069c.png)
![image](https://user-images.githubusercontent.com/44861876/235175417-d7f83569-eb36-4ea3-ad8e-dc624d5cdb23.png)

如图，当【网站配置】【邮箱配置】【敏感词审核】这三个地方未做任何修改就提交时，数据库更新updateConfig会返回null，然后导致res.send({ status: 'Success', message: '操作成功 | Successfully', data: result.mailConfig })中的 result.mailConfig报错引发空指针异常，前端响应如下：
{"status":"Fail","message":"Cannot read properties of null (reading 'mailConfig')","data":null}

**Comment by Kerwin1202** [comment]
应该之前修复过了
