### ISSUE TITLE
注册后管理邮箱收不到信件

### ISSUE THREAD

**Issue by yefeiyu** [Kerwin1202/chatgpt-web#97]
注册的邮箱能收到来信，点击后注册邮箱提示已验证并发送到管理邮箱，
但打开管理邮箱收不到邮件。

**Comment by yefeiyu** [comment]
重新注册提示“请等待管理员通过”，无法使用该邮箱重新注册

**Comment by luckywangxi** [comment]
> 重新注册提示“请等待管理员通过”，无法使用该邮箱重新注册

看看发件的邮箱是否已正常发送，如已发送，检查一下收件垃圾邮箱是否被拦截
