### ISSUE TITLE
bug小结： v2.12.7

### ISSUE THREAD

**Issue by huangwb8** [Kerwin1202/chatgpt-web#98]
这里总结一些目前我发现的小bug，有一些是历史bug了：

1. 每次更新镜像后，**Access Token模式下部分旧对话中聊天会出现报错**：

```
ChatGPTUnofficialProxyAPI.sendMessage: conversationId and parentMessageId must both be set or both be undefined
```
刷新无效。
但是，某些对话是正常的，并且新建对话正常。该bug在API模式中暂未发现：

![msedge_8njOJEvrf2](https://user-images.githubusercontent.com/35643122/235670726-dedfc06f-8c83-4830-9d41-e89afd4ca3c9.gif)

2. **初次登陆时聊天室内容不显示，要刷新一下才有内容**。这个bug曾经修复，但最近几次更新中又再次出现了：

![msedge_WLPAkob5bf](https://user-images.githubusercontent.com/35643122/235670063-844a06c2-6fa1-40ae-bb06-85087fe02d21.gif)

该bug在API/Access Token模式中均可出现。

**Comment by Kerwin1202** [comment]
第二个问题确实存在 本次忘记修复
第一个问题，从你图中看到 原本存在1句对话，这个是设置accesstoken之后聊天开始的？ 主要之前确实发现如果一开始api聊天 然后切成 access token 这时候无法在原来的对话聊天，只能新建对话。如果是这个情况，我觉得问题也不是很大。毕竟对access token 来说 会在官网有会话的，切过来新开才可以聊天说得过去

**Comment by xiaoguaishou92** [comment]
补充一下，更新go-api镜像也会有这个问题，但是Chanzhaoyu/chatgpt-web不存在这个问题

**Comment by ixxmu** [comment]
大佬能否加个功能，可以给用户是否开启gpt4权限，要是太复杂就算了😄

**Comment by Kerwin1202** [comment]
> 大佬能否加个功能，可以给用户是否开启gpt4权限，要是太复杂就算了😄

这是个模型 不太明白， 这里可以选择
<img width="507" alt="image" src="https://user-images.githubusercontent.com/16319833/236383515-22108334-eb67-4463-a822-a400f53a8a3c.png">

**Comment by 1VeniVediVeci1** [comment]
> > 大佬能否加个功能，可以给用户是否开启gpt4权限，要是太复杂就算了😄
> 
> 这是个模型 不太明白， 这里可以选择 <img alt="image" width="507" src="https://user-images.githubusercontent.com/16319833/236383515-22108334-eb67-4463-a822-a400f53a8a3c.png">

他应该是想要给特定用户分配特定模型，毕竟gpt-4有限额

**Comment by ixxmu** [comment]
> > > 大佬能否加个功能，可以给用户是否开启gpt4权限，要是太复杂就算了😄
> > 
> > 
> > 这是个模型 不太明白， 这里可以选择 <img alt="image" width="507" src="https://user-images.githubusercontent.com/16319833/236383515-22108334-eb67-4463-a822-a400f53a8a3c.png">
> 
> 他应该是想要给特定用户分配特定模型，毕竟gpt-4有限额

是的，毕竟也不想部署两套

**Comment by 1VeniVediVeci1** [comment]
> 

我现在其实也遇到了这个问题，结果就是额外部署了一个原版的chatgpt-web，不想让开的plus的gpt4浪费

**Comment by huangwb8** [comment]
[v2.12.8](https://github.com/Kerwin1202/chatgpt-web/releases/tag/v2.12.8)已经较大程度修复相关bug。
