### ISSUE TITLE
OpenAI missing required apiKey

### ISSUE THREAD

**Issue by LLLLLL223** [Kerwin1202/chatgpt-web#99]
之前用的apiKey调用的,后续切换成OPENAI_ACCESS_TOKEN,项目启动还是会显示 OpenAI missing required apiKey

**Comment by huangwb8** [comment]
@LLLLLL223 

这在某个issue里被回答过。 如果你使用的是latest版本（v2.12.6或以上），需要添加这个参数：

```yaml
# ChatGPTAPI ChatGPTUnofficialProxyAPI
OPENAI_API_MODEL: ChatGPTUnofficialProxyAPI
```
才可以使用Access Token模式。
